.coveragerc, .travis.yml, .yamllint, .yamllint.strict, Makefile, data/housenumber-filters-csilleberc.yaml, data/housenumber-filters-szechenyihegy.yaml, get_reference_housenumbers.py, helpers.py, requirements.txt, setup.cfg, suspicious_streets.py, tests/test_helpers.py, tox.ini, wsgi.py
Különben exceptiont dob házszám frissítéskor, valszeg ez okozza a HTTP 500-at is.
Bug introduced in #13 https://github.com/vmiklos/osm-gimmisn/pull/13/commits/bcaecf154aaaadd081027d49e7ae83bf22ab3699
=> Wsgi error handling: legalább az első commitot fogadd be ASAP

Makefile, data/housenumber-filters.schema.yaml, requirements.txt
A future alternative validator would be `pajv`.
Fixes #23
=> Makefile: validate schema of house number filters using yamale

Makefile, wsgi.py
=> wsgi.py: simplify interface UX, translate to Hungarian

data/housenumber-filters-gazdagret.yaml, data/housenumber-filters-hosszuret.yaml, data/housenumber-filters-madarhegy.yaml
=> Adding new elemenents to filters + reorganize the order of tags

data/relations.yaml
=> Update relations.yaml - vidék

data/housenumber-filters-dobogo.yaml, data/housenumber-filters-ormezo.yaml
Dobogó út élmény volt rollerrel
=> Updating house number filters

data/housenumber-filters-gazdagret.yaml, data/housenumber-filters-kelenfold.yaml, data/housenumber-filters-madarhegy.yaml, data/housenumber-filters-nemetvolgy.yaml, data/housenumber-filters-ormezo.yaml, data/housenumber-filters-orsod.yaml, data/housenumber-filters-spanyolret.yaml
Most már mehet a strict szerver oldalon is
=> Fixing filters.yaml - indents

data/relations.yaml
=> add gellerthegy, belvaros, erzsebetvaros

data/streets-template.txt
second and third part are not running with way(area); searchArea needed
=> Fixing street-template

data/relation-kelenfold.yaml
=>  Update relation-kelenfold.yaml 

data/relation-kelenfold.yaml
=> data: kelenfold: Andor köz, Szádelő, Csorbai, Pajkos

data/relation-farkasvolgy.yaml, data/relation-hegyvidek.yaml, data/relation-istenhegy.yaml, data/relation-svabhegy.yaml, data/relation-szechenyihegy.yaml, data/relation-viranyos.yaml, data/relations.yaml
=> data: farkasvolgy: update Hóvirág út filter

data/relation-lagymanyos.yaml
=> data: lagymanyos: add Október huszonharmadika utca

data/relation-albertfalva.yaml
Bodola Lajos utca
Gerezd utca
Kiskőrös utca
Nyírbátor utca
Pentele utca
Sáfrány utca
Szatmárhegy utca
=> data: albertfalva: add more filters based on survey

helpers.py
=> add more megye in refmegye_get_name

data/relation-kelenfold.yaml
=> data: kelenfold: add Albert utca and more

.coveragerc, data/relation-sashegy.yaml, validator.py
@vmiklos mehet ez a tegnapi a közösbe?
=> validator: win force utf8

data/relation-budafok.yaml
Szűrők: Avar utca, Bem József utca, Hollandi utca, Kossuth Lajos utca, Liszt Ferenc út, Márvány utca, Páva utca, Püspök utca, Rugó utca, Szentkorona utca, Turóci utca
Javítva: Vöröskúti határsor
=> data: budafok: add filters

data/relation-albertfalva.yaml
+ survey result for: Albertfalva utca, Fegyvernek utca, Karcag utca, Kisköre utca
+ Fehérvári 168-178, 182-190 separation in filter is not needed anymore
=> data: albertfalva: extend filters

data/relation-tisztviselotelep.yaml
for test only
probably in the future budapest_08 is enough, suburbs are not needed
=> data: add: tisztviselotelep

data/relation-peterhegy.yaml
Éva utca, Kapolcs utca, Kápolna köz, Kápolna út, Péterhegyi köz, Péterhegyi lejtő
=> data: peterhegy: add filters

data/relations.yaml
Please add Veresegyhaz via this pull request.
=> Adding Veresegyhaz to processed areas.

data/relation-rezmal.yaml
=> data: rezmal: fix Bogár utca

data/relation-rezmal.yaml
Felvinci út 39 -> Kapor utca 3 csere volt
=> data: rezmal: update Felvinci út

data/relation-lipotvaros.yaml
=> data: lipotvaros: add Zoltán utca filter

data/relations.yaml
néhány Békés megyei település hozzáadása.
elkezdtem a "vidéket" megyénként csoportosítani.
=> békés megyei települések ..

data/relations.yaml
=> data: relations: fix kamut & sort pest megye

data/relation-albertfalva.yaml
=> data: albertfalva: filter all remaining invalid, try#1

data/relation-gazdagret.yaml
=> data: gazdagret: filter out invalid simple numbers

data/relation-krisztinavaros.yaml
lesz ma dolog errefelé, lássuk mit dob ki..
=> data: krisztinavaros: housenumber-letters: true

data/relations.yaml
Workflow teszt. Ha rendben megy, jönnek a zuglói kerületrészek is.
=> Zugló felvétele

data/relation-hosszuret.yaml
=> data: hosszuret: filter invalid numbers with letters

data/relation-budaors-lakotelep.yaml, data/relations.yaml
=> data: add budaors-lakotelep

data/relation-krisztinavaros.yaml, data/relation-orbanhegy.yaml
https://github.com/vmiklos/osm-gimmisn/commit/d957ef5cf5e9ce0847e1f1f212a3871722c31979
=> data: review some filters, after errors found in kissvabhegy

data/relation-madarhegy.yaml, data/relation-spanyolret.yaml
=> data: Törökbálinti út filter update

data/relation-budaors-lakotelep.yaml
If the pull request syntax is OK, please merge it.
Information collected using survey. There is no number 29 in Patkó utca@Budaörs
=> Add invalid housenumber in Patkó utca@Budaörs

data/relation-budaors-lakotelep.yaml
House number 164 is just outside of `budaors-lakotelep` area.
=> Fix housenumber upper range limit of Szabadság út

data/relation-csilleberc.yaml
Konkoly-Thege Miklós út
Magas út/Magasúti dűlő
=> data: csilleberc: extend filters

data/relation-budaors-lakotelep.yaml, data/relation-budaors.yaml
🇭🇺 Március 15-ei mapping :) 🇭🇺
=> Add invalid housenumber to Baross utca@Budaörs.

data/relation-posingermajor.yaml
=> data: posingermajor: filter some invalid housenumber letters

data/relation-budaors-belvaros.yaml, data/relations.yaml
=> data: add budaors-belvaros

data/relation-alsorakos.yaml, data/relation-herminamezo.yaml, data/relation-istvanmezo.yaml, data/relation-kiszuglo.yaml, data/relation-nagyzuglo.yaml, data/relation-rakosfalva.yaml, data/relation-torokor.yaml, data/relation-varosliget.yaml, data/relation-zuglo.yaml
A területhatárokon és a kettévágott utcákhoz megcsináltam a .yaml-okat.
=> Zugló városrészek házszám tartományai

.travis.yml
Otherwise it triggers on PR validation too.
=> .travis.yml: only send notification after push to master

data/relation-budapest_12.yaml, data/relation-csilleberc.yaml, data/relation-istenhegy.yaml, data/relation-krisztinavaros.yaml, data/relation-kutvolgy.yaml, data/relation-martonhegy.yaml, data/relation-nemetvolgy.yaml, data/relation-orbanhegy.yaml, data/relation-sashegy.yaml, data/relation-svabhegy.yaml, data/relation-szechenyihegy.yaml, data/relation-viranyos.yaml, data/relation-zugliget.yaml
=> data: budapest 12: big filter review and merge into one

data/relation-budapest_15.yaml
Reverts vmiklos/osm-gimmisn#439
mégsem, a ref nem konzisztens, mégis kell ez
=> Revert "data: budapest 15: fix refstreets"

data/relation-alsorakos.yaml, data/relation-kiszuglo.yaml, data/relation-nagyzuglo.yaml
Pótoltam a kimaradt tartományokat.
=> Zugló átfedő házszám tartományok

data/relation-rozsadomb.yaml, data/relation-szemlohegy.yaml, data/relation-zoldmal.yaml
=> data: budapest 02: fix filters

data/relation-szigetmonostor.yaml
@vmiklos bekommenteltem a nem létezőket, a yaml-ba, hogy hol kellene lennie, a nagy része a vonal alatt szerintem kuka
=> data: szigetmonostor: add street mapping

data/refsettlement-names.yaml
5. és 12. kerület nem kell már, mert csak 1 tagja van
=> data: update settlement filters

data/relation-bogacs.yaml, data/relation-felsotarkany.yaml, data/relation-gyula.yaml, data/relation-pilismarot.yaml, data/relation-szilvasvarad.yaml
=> data: add & fix street mappings

data/relation-pilismarot.yaml
=> data: pilistmarot: add street mapping

data/relation-gardony.yaml, data/wsgi.ini.template
=> data: update reference

data/relation-budapest_21.yaml, data/relation-budapest_23.yaml
bevállt a note létrehozás valaki megfixelte
=> data: drop street mapping of fixed streets

data/relation-gellerthegy.yaml, data/relation-infopark.yaml, data/relation-sasad.yaml, data/relation-sashegy.yaml
need the same settings for housenumber-letters before merging them into one
=> data: bp11: turn on housenumber-letters for the rest

data/relation-sasad.yaml
Oltvány árok -> Birs utca -> Beregszász út -> Háíromszék utca -> Őrség utca -> Domboldal utca -> Ugron Gábor utca -> Dayka tér
=> data: sasad: add more invalid numbers

data/relation-kisoroszi.yaml
=> data: kisoroszi: remove street mappings

data/relation-taban.yaml
=> data: taban: add more invalid numbers

data/relation-balatoncsicso.yaml, data/relation-kelenfold.yaml, data/relation-kelenvolgy.yaml, data/relation-obudavar.yaml, data/relation-sasad.yaml, data/relation-szentantalfa.yaml, data/relation-szentjakabfa.yaml, data/relation-zanka.yaml
100% areas to inactive=true
my previous areas to inactive=true
sasad to inactive=false
=> data: override automatic inactive state of 2020-08 visits data for 100%

data/relation-budapest_05.yaml
=> data: budapest 05: update filters

data/relation-peterhegy.yaml, data/relation-pilisvorosvar.yaml
Pilisvörösvár
Budapest XI. Péterhegy
=> data: update filters

data/relation-budapest_06.yaml
=> data: budapest 06: add mroe invalid numbers

package.json
Change-Id: If7486b842144d75d5238588f81f23a35963d5db4
=> Update eslint to 7.10.0

requirements.txt
Change-Id: I2592eb8ac3e6b71570fee0d91391b2e17362a114
=> Update yamllint to 1.25.0

requirements.txt
Change-Id: I105a3f8b94ed0b96139526aeef4d198de7551723
=> requirements: update flake8 to 3.8.4

data/relation-budapest_17.yaml, data/relation-pilisvorosvar.yaml
=> data: remove street mappings not needed anymore

package.json
Change-Id: I1500fee4ac8513a1e0c55114a35c56307a6b04d8
=> Update eslint to 7.11.0

package.json
Change-Id: I2af334d6e4f81fde6e8dfbadf203e9a46760a0e0
=> Update eslint to 7.12.0

areas.py, tests/test_areas.py
Change-Id: Ib8026190e8d066fc08dec7d464bc0c147f450d07
=> additional streets: take ref-osm name mapping into account

areas.py, doc/README.adoc, tests/data/relation-gazdagret.yaml, tests/test_areas.py, tests/test_cron.py, tests/test_wsgi.py, tests/workdir/street-housenumbers-gazdagret.csv, validator.py
Change-Id: I6fd5cf01c008c073049096a96b1dd73debc54e26
=> additional streets: allow filtering out false positives

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, wsgi.py
Also update the l10n strings as well.
Change-Id: I4826983c3c0082714cdd1cab1b463d8159d67645
=> additional streets: advertise the endpoint on the main page

package.json
Change-Id: I75f96bcee210391a78edcb2a25d9ebc6a8f179e3
=> Update eslint to 7.12.1

additional_streets.py, areas.py, tests/test_areas.py, wsgi.py
Change-Id: I07e472cfa0fd6300899287116a7779e089289e9f
=> get_additional_streets: clean up unused half of return value

data/relation-telkibanya.yaml, data/streets-template.txt
=> data: telkibanya + street-template

data/relation-budapest_05.yaml, data/relation-telkibanya.yaml
=> data: update filtes/refstreets

requirements.txt
Change-Id: Iad1d825a736c493d86551463ff8b0f2c39fd19bb
=> Update pytz to 2020.4

data/relation-godollo.yaml
Podmaniczky Frigyes utca egyeztetése, dűlők/tanyák más alakban már szerepelnek
=> Frissítések

data/relation-budapest_12.yaml
Change-Id: Ie032e5e4ed8f80aacf5f9a7850f5393cd0aa516c
=> data: budapest_12: extend Denevér út filter

README.adoc
Change-Id: I3274231b1703c9efeab11d83bcc82a1374ca4e38
=> doc: update build status badge

doc/README.adoc
Change-Id: I2bdae29113da1478380d583c5f69091f77b343d7
=> doc: add section describing how to use the automerge label on PRs

.github/workflows/tests.yml
Also merge the install deps + make check sections into a single one,
multiple commands are supported for a single step.
Change-Id: I59feb0218d1ebf561912ae31179f9a94f739eaaf
=> GitHub tests workflow: fix indentation

data/relation-budapest_12.yaml
Change-Id: Ia373afe32bc78c8a0857186d8f178f30603f7410
=> data: budapest_12: add Deres utca filter

package.json
Change-Id: Idfe1f52ad3a3f76799a893849664174ae833c704
=> Update eslint to 7.13.0

.github/workflows/tests.yml, tools/ci-build.sh
Change-Id: Iade462fa42edb3b8aaabbade112c2147c862bced
=> CI: try to paralellize the build

.github/workflows/tests.yml, README.adoc
Change-Id: I3abc9ab9163d3804e69bdae6e60f52abdfc94b9e
=> CI: be consistent around Tests vs tests

webframe.py
One less condition, and we have the space for it.
Related to
<https://github.com/vmiklos/osm-gimmisn/issues/688#issuecomment-727200827>.
Change-Id: I6097e0212d55a045942238a8fccdfee31a327a83
=> webframe: show overpass turbo link unconditionally

wsgi.py
Related to <https://github.com/vmiklos/osm-gimmisn/issues/689>.
Change-Id: I3e26bdcdcfda1b09164f350170361eb7162bd71f
=> additional streets: show count on main page if we have the cached count

cron.py, tests/test_cron.py
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/689>.
Change-Id: Ib1a6caf59cde2dc0e3ae53efa37da5ae9e0edf6f
=> additional streets: count this during the cron job

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, wsgi.py
Related to <https://github.com/vmiklos/osm-gimmisn/issues/689>.
Change-Id: I04d8d2f5d3153f2ded80b4ea6a14de685c12846e
=> additional streets: show unit on main page

tests/test_wsgi.py, util.py, wsgi.py
Change-Id: I5e6f80553e11b67a4e90ae1b83f346eeef4766dd
=> main page: add a filter-for variant which accepts a relation id list

.eslintrc, static/stats.js
<https://caniuse.com/?search=await> says we're at >= 90%.
Change-Id: I3385f852118aad5276024062fba9ec214a81435b
=> stats: simplify using await

data/relation-budapest_12.yaml
Change-Id: Ie688b1feef091d83eb1f49bf3aaa19809b08a691
=> data: budapest_12: add Ágnes köz filter

doc/README.adoc
Change-Id: Ie8d9664297ab693b5c9d5788cc2890e4c5c2ffef
=> osm-street-filters: it's the other way around

data/relation-budapest_12.yaml
Change-Id: I9541fb3239dbfb6052b621daae233b21d4300468
=> data: budapest_12: add Rácz Aladár köz filter

.eslintrc, Makefile, static/osm.js, wsgi.py
Mostly fixes <https://github.com/vmiklos/osm-gimmisn/issues/690>.
Change-Id: I249dedca011c5b1d133ea72789d8cc6053436d4e
=> main page: add a "filter by own position" filter mode

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, static/osm.js, wsgi.py
Change-Id: Id61ddbb56a14f40867dc71047a659e028105b4ab
=> filter-based-on-position: add localization

INSTALL.adoc
Change-Id: I0bee37f6919b7250425cdad2c23c8d9645bedbc2
=> doc: install: dev server can be started via 'make run', not server

INSTALL.adoc, Makefile
No need to do this manually.
Change-Id: I4c1661497f9e1cf3c5212da431b8567433d2564c
=> Create wsgi.ini if it's missing

tools/ci-build.sh
Change-Id: Idafd0d73f514d0bd61771bdb160df82e42125f40
=> CI: 'npm install' is now part of make

stats.js
Change-Id: Id4ea15068fef3f344277a2a96509133bcd03e1f3
=> stats: rework to avoid depending on a js global var

data/relations.yaml
Change-Id: Ifac61ebebe43414f26e11728e7c05c8b6e00220c
=> data: add kaskantyu

data/streets-template.txt
avoid:
- underpass: pedestrian
=> data: refine overpass for streets

areas.py, tests/test_areas.py, tests/workdir/street-housenumbers-gh754.csv, tests/workdir/streets-gh754.csv, util.py
Related to <https://github.com/vmiklos/osm-gimmisn/issues/754>.
Change-Id: I0a32a923c37b43b0f9f59484c01c3b1c08736065
=> get_osm_streets: require housenumber -> require housenumber or conscriptionnumber

data/relation-budaors-kertvaros.yaml, data/relation-budaors.yaml
fix Kertváros boundaries
add invalid numbers
=> data: budaors: update filters

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, tests/test_wsgi.py, util.py, wsgi.py
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/759>.
Change-Id: Icd2c478e3939749b616f627089d89cb97aa111b6
=> main page: hide complete areas by default

areas.py, util.py, wsgi.py
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/782>.
Change-Id: I1fa96c22c33dbe284b76e75cded18dd5d23ee7a7
=> additional streets: street type is not always 'way', it can be e.g. relation

data/relations.yaml
Change-Id: I641875114f882bea2aee633303dfd6a673336a7f
=> data: add pahi

osm.ts, stats.ts
Change-Id: Icc8014fb417f0d044e4bd3aef752b80f81fca2e6
=> js: it's enough to register a single DOMContentLoaded listener

wsgi.py
Related to <https://github.com/vmiklos/osm-gimmisn/issues/759>.
Change-Id: Iae4f974729147a1f9587477d55bea64b77fc837e
=> wsgi: complete area means both street + housenr coverage

tests/test_wsgi_json.py, wsgi_json.py
Change-Id: I11fca61d2a27e0d3df3fe513c6c2987287826316
=> wsgi: add a /street-housenumbers/.../update-result.json endpoint

data/relation-budaors-kertvaros.yaml, data/relation-budaors.yaml
=> data: budaors: add more invalid numbers

data/relation-kaskantyu.yaml, data/relation-pahi.yaml
=> data: add street mapping for new areas

tests/test_wsgi_json.py, wsgi_json.py
Change-Id: I8c0a862bdf5ffab93fdfcd79c1e1c34285facdfc
=> wsgi: add a /missing-housenumbers/.../update-result.json endpoint

data/wsgi.ini.template
Change-Id: I862f217af574528923aa20bc4e065e6e24bec94f
=> data: update secondary reference_housenumbers to 20201210

data/relation-dorog.yaml, data/robots.txt
Reverts vmiklos/osm-gimmisn#808
=> Revert "data: dorog: add Szabadság tér filter"

data/wsgi.ini.template
Change-Id: I382d30677673ee8895f7d95221e749278058dfe8
=> data: update ref to 20201218

osm.ts, webframe.py, wsgi.py
... in the missing-housenumber case, in case of a new relation.
Change-Id: Ie9a9f35d485b4f5270bfc18e00c96604a0bf2230
=> wsgi: use the /street-housenumbers/.../update-result.json endpoint

wsgi.py
i.e. return early in the error cases
Change-Id: Ie160402cc43a1a3fc437ee85b192d42f13feca0d
=> missing_streets_view_result: flatten the happy path

tests/test_wsgi_json.py, wsgi_json.py
But not yet actually using it from JS.
Change-Id: I42779228cc2ab223be466b84408916d2690cafd7
=> wsgi: add a /missing-streets/.../update-result.json endpoint

wsgi.py
Change-Id: I852620ac455c478e03d7150f14de1f2cc470b6de
=> additional streets: create initial ref/osm streets using JS

webframe.py, wsgi.py
It had the same value all the time.
Change-Id: I92320484d6ed6a45f966bb8ae587a8a8be22ba8f
=> handle_no_osm_streets: eliminate not needed label param

webframe.py, wsgi.py
Change-Id: I7bf6577dbe7f181c38a390f5928897c845149f66
=> handle_no_osm_housenumbers: eliminate not needed label param

webframe.py, wsgi.py
Change-Id: I4b7bcec903aa8756602db3926182322df89ef40e
=> handle_no_osm_housenumbers: eliminate not needed noscript

webframe.py, wsgi.py
Change-Id: I2df55f93fc0e017b059812c7a93cd57f0eb8f3c2
=> handle_no_ref_housenumbers: eliminate not needed label param

webframe.py, wsgi.py
Change-Id: I812aa4bb32162a46355f490d48f98708141bde0d
=> handle_no_ref_housenumbers: eliminate not needed noscript

webframe.py, wsgi.py
Change-Id: I9b61d929c874d03755eca9360f36d978d3e58b22
=> handle_no_ref_streets: eliminate not needed label param

webframe.py, wsgi.py
Change-Id: I6e4d081e6135c1c804a184814f9c87fe057943e8
=> handle_no_ref_streets: eliminate not needed noscript

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, webframe.py
Not missing ones. Also update l10n.
Change-Id: Ib77c75da3aac3c9e35851524e09f83658de11cc0
=> Reference house numbers can be create from the reference

osm.ts, static/osm.css
Use it every time the text content is set and the label is not an error
message.
Change-Id: I6551ff1bdbca6f3c71647c3b279b7fbc32a767e4
=> Add a loader effect when waiting from JS

data/wsgi.ini.template
Change-Id: I768eefc4cc78aad53259b41a1e594975d89879d0
=> data: update reference to 20201222

webframe.py
Change-Id: Icf4046373a9f8aae3455e83c35678751db04933a
=> js redirect: handle overpass links in the existing streets/housenr pages as well

requirements.txt
Change-Id: I4cefeb5ed168c77d227c7ee753a9d4e799eedf6f
=> requirements: update coverage to 5.3.1

requirements.txt
Change-Id: I23207b1f805158f9e4f05c967bb876962419391e
=> requirements: update unicode to 1.1.2

data/wsgi.ini.template
Change-Id: I1ccee18f48ec11233bf3174eb7e440d81a37a668
=> data: update reference to 20201226

requirements.txt
Change-Id: Ibed1ebb17855ca926e9621f93965484327b5147f
=> requirements: update pytz to 2020.5

data/wsgi.ini.template
Change-Id: I5007553f34fc45fae2b1a82f24dc01fe739b23dc
=> data: update reference to 20201231

package.json
Change-Id: If82de9a4feda6d10043e8675becb0f34e70d7922
=> Update eslint to 7.17.0

data/relation-budapest_12.yaml
Change-Id: I835cc802090d3ff38c6da304742d9472097fed05
=> data: budapest_12: add Evetke út filter

areas.py, po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, tests/test_areas.py, tests/workdir/street-housenumbers-gh830.csv, tests/workdir/street-housenumbers-test.csv, tests/workdir/streets-gh830.csv, util.py, wsgi.py
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/830>.
Change-Id: I4d06b124b564c1754c4ee71b819585ed2272eb0e
=> additional streets: support streets from housenumbers with type=node

areas.py, po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, util.py, wsgi.py
Can be street or housenumber.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/830>.
Change-Id: If2b26b6acb3c57a377f1418a7c8df2c3036c066d
=> additional streets: show source of streets

data/relation-piliscsaba.yaml
add Béla király filter, remove Szent László király mapping
=> data: piliscsaba: királyok

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, webframe.py, wsgi.py
Related to <https://github.com/vmiklos/osm-gimmisn/issues/875>.
Change-Id: Icbd22de604c83c863f0ed51247e8c58f59868546
=> missing housenumbers: move txt/chkl links out of the header

tests/test_wsgi.py, webframe.py, wsgi.py
And move txt output out of the header.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/875>.
Change-Id: Ib3bbc8dfe0506adeb8ec7a079cfee44e6fc9c3ee
=> missing streets: add chkl output

Makefile, tests/test_wsgi_additional.py, wsgi.py, wsgi_additional.py
And split out the "additional" part of wsgi.py to a new module before it
grows too large.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/875>.
Change-Id: I3e2534bd5acf2d6d3f1da7d0d736c42af5f70e37
=> additional streets: add txt output

wsgi_additional.py
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/875>.
Change-Id: Ia2440f3fab21070746ef941251784fb9972a10df
=> additional streets: add chkl output

data/relation-gellerthegy.yaml
Somló út
Somló lépcső
Igló utca
=> data: gellerthegy: add Somló út filter and more

data/wsgi.ini.template
Change-Id: I70c4a4843639ad737895a5acddfe24501b56c576
=> data: update reference to 20210115

TODO.adoc, tests/test_webframe.py, util.py, webframe.py, wsgi.py
So browsers can cache them when not modified.
Change-Id: I8238529cd3de358ffdbff4e57764f101bf645b41
=> wsgi: send Last-Modified header for static files

requirements.txt
Change-Id: I3fe9d280d9b28272cb22c2bf964469cf8dc9b4ea
=> requirements: update coverage to 5.4

parse_access_log.py, requirements.txt
Change-Id: I3cf9a723f93458536101d620eb9e5a864aec0dca
=> requirements: update mypy to 0.800

package.json
Change-Id: Ia61f86f14eabb741facfa325f986ddd23f1bbf63
=> npm: update eslint to 7.18.0

areas.py, tests/data/relation-gazdagret.yaml, tests/test_areas.py, tests/test_wsgi.py, util.py, wsgi.py
- warn if osm name is not in the osm street list
- warn if ref name is in the osm street list
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/784>.
Change-Id: I72ac99a62e4c235b7804bcdf6524d04620c32a9c
=> missing housenumbers: add street mapping

.eslintrc, TODO.adoc, stats.ts
So in case I mistype some key name, the build can now fail.
Change-Id: I4810c4cc6524682658ae8c24632740bc71642b6e
=> stats: replace unsafe json with proper types

requirements.txt
Change-Id: I59fbc1ca460b9e44f41a6692d77e18f966ba5da5
=> requirements: update pyyaml to 5.4.1

data/relation-budapest_12.yaml
Change-Id: Id30914669066e3aad4a2155310417c1bf3deb491
=> data: budapest_12: add Agancs út filter

package.json
Change-Id: I5fa6b9176e4ef65413e35e15fb4834e9530478bf
=> npm: update eslint to 7.19.0

requirements.txt
Change-Id: Ibec394ee6c02b6eff66b1334e1c0bdf9dadd4204
=> requirements: update pytz to 2021.1

areas.py, tests/test_areas.py, tests/test_cron.py, tests/test_wsgi.py, tests/test_wsgi_json.py, tests/workdir/street-housenumbers-gazdagret.csv
And all the other columns which is there for real street-housenumber CSV
files.
Towards parsing street-housenumber CSVs by header name.
Change-Id: Ice01610db63d8bda47aecf8b37678d5ba7538fa1
=> tests: add @type to tests/workdir/street-housenumbers-gazdagret.csv

areas.py, util.py
So new cols can be added without problems.
Change-Id: I42abda6f5adcd5d4f483d8e61d26d7d958ad494a
=> Parse street-housenumber CSVs by header name

requirements.txt
Change-Id: I2f286e699f7c0f7da5a082b38a1c452313f7e2a8
=> requirements: update yamllint to 1.26.0

Makefile, po/hu/osm-gimmisn.po, po/osm-gimmisn.pot
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/978>.
Change-Id: I4c3ad351df2798ce6b1ecdb61afbb193614f3dcf
=> gettext: check wsgi_additional.py for l10n strings

package.json
Change-Id: I637d5ff6f2e7f61ae21fa68165d11b027d3bf33b
=> npm: update @types/chart.js to 2.9.30

data/street-housenumbers-template.txt
Related to <https://github.com/vmiklos/osm-gimmisn/issues/964>.
Change-Id: Iec57aed5ee0fb29a0583cd095c04454fcd259b8f
=> data: fix street-housenumbers template for addr:place

areas.py, tests/workdir/streets-gazdagret.csv
get_osm_streets() will sort it later anyway.
Change-Id: Ie1358e42aa99321221bfd5f854e18d9ea3011a24
=> areas: don't bother sorting the osm street list

tests/test_util.py, util.py
Towards elinimating split_street_line(), which hardcodes column indexes
in street CSVs.
Change-Id: Id3206d535f998c3e4ea617cb447552b7d2c7c00a
=> Drop now unused process_csv_body()

tests/test_util.py, tests/workdir/street-housenumbers-gh964.csv, util.py
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/964>.
Change-Id: I5928db467189be6b58407379a7d19f34c723cf59
=> get_street_from_housenumber: consider addr:place when addr:street is empty

parse_access_log.py, requirements.txt
It got type hints. \o/
Change-Id: I40fc37ed06c3bef30c7f812997585e834fbfb2d2
=> requirements: update unidecode to 1.2.0

data/street-housenumbers-template.txt
removing fields not needed in search block
=> data: simpify street-housenumbers template

tests/test_util.py, util.py
Change-Id: I4ca1c06c17e8000682fc85d0e2fdaced6d9a9591
=> Remove unused sort_housenumbers()

tests/test_util.py, util.py
And whatever is a fallout from that: 2 more functions and an import.
Change-Id: I9aec3ff1d612e87e6326daa33b9eddc13ccc9ab6
=> Remove unused sort_streets()

data/relation-gellerthegy.yaml
=> data: gellerthegy: add more invalid numbers

package.json
Change-Id: I8669b078d62015f9c6f59ea720f51848b1c54c26
=> npm: update @typescript-eslint/eslint-plugin to 4.15.0

package.json
Change-Id: Ieb8d40d062f0f34e01e3af6808f6b6f05c95bedc
=> npm: update @typescript-eslint/parser to 4.15.0

package.json
Change-Id: I522042dbf45c737acb86a7af5e18797af3ad3dee
=> npm: update @types/node to 14.14.27

main.ts, package.json
Horrors, TS 4.1 changes Position -> GeolocationPosition.
Change-Id: I48b80ba5fea04a1bf4c1129078b08df4985895ee
=> npm: update typescript to 4.1.5

package.json
Change-Id: Ie21b41f1f4ced900d02ce7ae027305e0c2feb6e7
=> npm: update eslint to 7.20.0

main.ts
These would be "any" by default, implicitly.
Change-Id: I556789e349222c5429b643f5cc2181ccfbc2f859
=> filter by position: add type check for overpass and own relation list json responses

tests/test_wsgi.py, webframe.py
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1025>.
Change-Id: Icf39c178a0eb5dac90091275b9d8338105ea2f9c
=> invalid refstreets: add UI to list all problematic relations

requirements.txt
Change-Id: Ife1c343df07510eef8ed854f348df6b8469ff80f
=> requirements: update mypy to 0.812

tests/test_wsgi.py, webframe.py
Related to
<https://github.com/vmiklos/osm-gimmisn/issues/1025#issuecomment-784018959>.
Change-Id: Ic21fb5ec0d01c9d42779d7a3ab42e18105307d85
=> invalid refstreets: make relation name clickable

data/wsgi.ini.template
Change-Id: I0719d208f914e625feccf3aa6d9c2d154d01eb7a
=> data: update reference to 20210226

areas.py, po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, tests/test_util.py, util.py, webframe.py
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1048>.
Change-Id: I32d9701723a16c3f232476b2abce0cb7d91b289f
=> invalid-relations: flag filter key names which are not OSM street names

requirements.txt
Change-Id: I52ce303e60962faa0fecc5b413ef85c0e28f0a48
=> requirements: update pylint to 2.7.2

package.json
Change-Id: I761b3e6c042aa62cdd10c22fac81133d3f5edd23
=> package.json: update typescript to 4.2.3

wsgi.py
Related to <https://github.com/vmiklos/osm-gimmisn/issues/1048>.
Change-Id: I8b75fef78680e6237751aef15081f06fa8b25df1
=> invalid-relations: show filter key name check results in relation pages as well

data/relation-albertfalva.yaml, data/relation-budakeszierdo.yaml, data/relation-budaors-belvaros.yaml, data/relation-budaors-kertvaros.yaml, data/relation-domos.yaml, data/relation-gardony-agard.yaml, data/relation-gardony-kozpont.yaml, data/relation-lagymanyos.yaml, data/relation-pilismarot.yaml, data/relation-rakospalota-oregfalu.yaml, data/relation-szemlohegy.yaml, data/relation-torokor.yaml, data/relation-vizafogo.yaml
process /housenumber-stats/hungary/invalid-relations results
=> data: fix typos and remove unnecessary filters

requirements.txt
Change-Id: I4a08e69f54ffda67fb4ad0f9c99fe6045fa0c13f
=> requirements: update coverage to 5.5

package.json
Change-Id: Id43b7eb22b025c9b8a4f52c46daae1c94d142113
=> package.json: update eslint to 7.22.0

data/relation-budapest_12.yaml
Change-Id: I77ea94710f72366c06fbb7cb8abb1f7c4e1616c3
=> data: budapest_12: add Ágnes utca filter

data/relation-budapest_12.yaml
Change-Id: I11eb80ff35fc287362da8587840f394bfbea2802
=> data: budapest_12: fix út vs utca typo

data/wsgi.ini.template
Change-Id: I9de7913f3f97867c0423ca499e7ae89d90f675eb
=> data: update reference to 20210312

data/relation-kamaraerdo.yaml, data/relations.yaml
=> data: add kamaraerdo

data/relation-kaposztasmegyer.yaml, data/relation-megyer.yaml, data/relation-nepsziget.yaml, data/relation-ujpest.yaml
=> data: budapest 04: update filters

data/relation-budapest_04.yaml
=> data: budapest: remove street mapping not needed

INSTALL.adoc, Makefile, package.json, tests/test_wsgi.py, wsgi.py
* wsgi.py: refer to endpoint as `refcounty/<value>/whole-county`
* package.json: bump versions
* INSTALL.adoc: mention npm
* Makefile: refine targets so they can run faster
* Fixes #1146
=> Refcounty endpoint everything

data/relation-sasad.yaml
=> data: sasad: add Érdi út invalid housenumbers

tools/issue.sh
Helps when commit messages refer to github issues and github is down.
Change-Id: Ife2a679d32e123ba6b6b34ac5c6a0a996e6a1078
=> tools: add script to easily download issues & open them offline

data/relation-budapest_12.yaml
Change-Id: I7aa1cfebb59450f85818c9ddddaa08526ab96b8d
=> data: budapest_12: add Sárospatak út filter

data/relation-tokodaltaro.yaml
=> data: tokodaltaro: add filters

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, tests/test_wsgi.py, webframe.py, wsgi.py
<http://localhost:8000/osm/> still loads the main page, but
<http://localhost:8000/asdf> now gives 404.
Fixes <https://github.com/vmiklos/osm-gimmisn/issues/1114>.
Change-Id: Idc8d96df8ec14fa1933fca4063d22f92c6524297
=> wsgi: add a 404 not found page

HACKING.adoc
Change-Id: I03e86a4dfb6ac8bb8829b77ca0e547f359bf9aab
=> HACKING: document the intentional lack of noscript tags

data/relation-budapest_12.yaml
Change-Id: I9d7b4864f586e60c439484b2e8e672ea4f74d8dc
=> data: budapest_12: add Diós árok filter

wsgi.py
Fixes <https://github.com/vmiklos/osm-gimmisn/issues/1117>.
Change-Id: Ic744945c9398c3e4b0b6a4eea808b2e677cda02d
=> wsgi: defer loading of bundle.js

data/relation-budapest_14.yaml
commit 7601d26cb624d8c4b975756d1da27cd90e0d8544
Author: Yogurt2 <yogurt4dev@gmail.com>
Date:   Wed Mar 31 10:58:32 2021 +0200
data: budapest_14: filter streets
commit 3117b5dde527be9c292acfa04e902d095d0934c2
Merge: 7a83dcd 183efc6
Author: Yogurt2 <yogurt4dev@gmail.com>
Date:   Wed Mar 31 10:56:43 2021 +0200
Merge branch 'master' of https://github.com/Yogurt4/osm-gimmisn
commit 183efc6401ecbbf6b339741cc60a92f4e2261d6a
Merge: 216c8b8 ecc2205
Author: Yogurt2 <yogurt4dev@gmail.com>
Date:   Tue Jun 16 12:11:41 2020 +0200
Merge branch 'master' of https://github.com/Yogurt4/osm-gimmisn
commit ecc2205535b8548a10c29a4d1b28b78f69bd27ef
Author: Yogurt2 <yogurt4dev@gmail.com>
Date:   Thu May 7 14:39:24 2020 +0200
Házszám tartomány javítása
23/b és 23/c között van a határ.
commit …
=> Squashed commit of the following:

data/relation-sashegy.yaml
=> data: sashegy: add more invalid numbers

requirements.txt
Change-Id: Ifd03427bb6139413980aea63f615b1eef82374e0
=> requirements: update pylint to 2.7.4

Makefile, requirements.txt
Change-Id: Ic8622308d597ddf4066cbf3a4a4a011e143e73c5
=> requirements: update flake8 to 3.9.0

data/relation-orsod.yaml
=> data: orsod: add more invalid numbers

data/relation-bajna.yaml
=> data: bajna: add Vértes utca filter

data/relation-budapest_12.yaml
Change-Id: I7adc3ce194cc821dfc64322b1caed253335e3eaa
=> data: budapest_12: add Rőzse utca filter

cron.py
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1209>.
Change-Id: I43358c465bc15d9fd726de2486e3db2c4206ea58
=> cron: also cache localized missing housenumbers html output

data/relation-bajot.yaml
=> data: bajot: add filters

data/relation-nagykovacsi.yaml, data/relation-remeteszolos.yaml
@Yogurt4 
- osm-street-filters-be kell kerüljön a "Karcsi útja" 
- street-fitler ami ref-ben van és nincs osm-ben
-
=> data: nagykovacsi-remeteszolos: fix filter keys

requirements.txt
Change-Id: Ibec4aab8e24157b6b4ee6e1722a72a0c704814ad
=> requirements: update yamllint to 1.26.1

data/relation-budapest_12.yaml
Change-Id: I9ab607357489cb5a6e4ebd5f8dd7446d8d881f5a
=> data: budapest_12: add Rőzse köz filter

requirements.txt
Change-Id: Ib4082cb8abb344400fdfa938e89a7c1f872f5d0a
=> requirements: update flake8 to 3.9.1

TODO.adoc
The only item it had is done.
Change-Id: I5c9d3a45a6a32183711a805facce78b57ccc7b1e
=> Remove outdated TODO

data/wsgi.ini.template
Change-Id: Ife016cc51013295b7977f4fd70178f50cc986cd2
=> data: update reference to 20210420

data/relation-nyergesujfalu.yaml
=> data: nyergesujfalu: add more invalid numbers

data/relation-visegrad.yaml
=> data: visegrad: add Mátyás király utca filter

data/relation-visegrad.yaml
=> data: visegrad: add Áprily Lajos Völgy filter

data/relation-visegrad.yaml
=> data: visegrad: add Rigó utca filter

data/wsgi.ini.template
Change-Id: Icb1b9054a73db5811d9c824966bd249b70c0d26b
=> data: update reference to 20210422

po/hu/osm-gimmisn.po
Change-Id: Ie32366fc6f77bb28399296155173eb2c0589f8b2
=> Fix translation

data/relation-budaors-belvaros.yaml
=> data: budaors-belvaros: add Baross utca filter

data/relation-budapest_12.yaml
Change-Id: I7ae1a91f7c129ab00d959d6e857bad681f05d08a
=> data: budapest_12: add Trencséni utca filter

data/relation-budaors-belvaros.yaml, data/relation-budaors.yaml
=> data: budaors-belvaros: add more invalid numbers

data/relation-budaors-belvaros.yaml, data/relation-budaors.yaml
fix Vasvári Pál utca filter
add Ady Endre utca invalid numbers
=> data: budaors-belvaros: update filters

data/relation-nagymaros.yaml
=> data: nagymaros: add Zöldfa utca filter

data/relation-budapest_03.yaml
=> data: budapest_03: add Igló utca filter

tests/test_util.py, util.py
Fixes <https://github.com/vmiklos/osm-gimmisn/issues/1140>.
Change-Id: Ie38109dfd98c109b1a9cbe323bf939570bb1aefa
=> street-housenumbers: sort by street name then by house number

data/relation-esztergom-kozpont.yaml, data/relation-esztergom.yaml
=> data: esztergom: add Petőfi Sándor utca filter

overpass_query.py, requirements.txt
Change-Id: Ib11d65d4a86b79eccfddcacc77ad7ca89cd71f4b
=> Use 'with' for resource-allocating operations

Makefile, additional_housenumbers.py, areas.py, cron.py, tests/test_areas.py, util.py, wsgi.py, wsgi_json.py
Only the core functionality + a cmdline tool.
Web interface, filters, etc still has to be done.
Change-Id: Iebddd9b8df5c4050f8af2532aeb854d8f070831b
=> additional housenumbers: add initial support

data/relation-budapest_11.yaml
found: Neszmélyi út 33, Vizsla utca 6
not found: Thallóczy Lajos utca 25b
=> data: budapest 11: update filters

data/relation-budapest_03.yaml
=> data: budapest_03: add Bivalyos utca filter

data/relation-budapest_12.yaml
Change-Id: Icdccfe748a5e4ab0ccbe32d8e977a76e3e2ae328
=> data: budapest_12: add Lóránt út filter

data/relation-esztergom-kozpont.yaml, data/relation-esztergom.yaml
=> data: esztergom: add Bánomi út, Sugár út, Táti út filter

data/relations.yaml
Requested-by: sd_ciastko
Change-Id: I74e856f1ded878301024358f8e1d34504e3f1758
=> data: add budakalasz and pomaz

data/relation-esztergom-kozpont.yaml, data/relation-esztergom.yaml
=> data: esztergom: add more invalid numbers

data/relation-esztergom-kozpont.yaml, data/relation-esztergom.yaml
=> data: esztergom: add Tegedy Csanád utca filter

data/wsgi.ini.template
Change-Id: Icc6eb7402fb6611481b0803891624e8246e7162c
=> data: update reference to 20210503

data/relation-nagymaros.yaml
=> data: nagymaros: filter streets

.gitignore, Makefile
Also put generated dirs to .gitignore
Change-Id: Icda4db5bd798e8a896100697d279d5d38151d359
=> make clean: remove generated JS and the mypy cache

requirements.txt
Change-Id: Ia5d69f112cc0b04107d751508b6fdb76f371c9b3
=> requirements: update flake8 to 3.9.2

data/relation-esztergom-kozpont.yaml, data/relation-esztergom.yaml
=> data: esztergom: remove street mapping

data/relation-budapest_12.yaml
Change-Id: I8baf94f63c53c4dd6d7ce657e402eee8bda87879
=> data: budapest_12: add Szamóca utca filter

data/relation-budapest_12.yaml
remove steets in ref
filter paths
=> data: budapest 12: filter streets

data/relation-budapest_10.yaml
=> data: budapest 10: filter streets

data/wsgi.ini.template
Change-Id: Ia6ea4c09e8f0f692542f8ebeb91ee35676aa8735
=> data: update reference to 20210516

doc/README.adoc
Change-Id: I09b38810a150283df86aa4a9922b1d741b2fb7cf
=> doc: update from osm for missing-housenumbers no longer redirects

package.json
Change-Id: Id944147244cfb4a7c4a8ba8c3b7466ecbe174fde
=> Update JS dependencies

areas.py, cache.py, cron.py, invalid_refstreets.py, tests/test_areas.py, webframe.py, wsgi.py, wsgi_additional.py, wsgi_json.py
One class would grow towards a God object, but lots of free functions
manually passing 'self' around is not ideal, either.
Change-Id: I441d7f4203ce8f9b8e49f5c19bb43608eddcb879
=> areas: split Relation into a base class + extend it

webframe.py, wsgi.py
Change-Id: I007b1805cb8684edffaf310571039a39d3b74dec
=> additional housenumbers: link the output from the main page + toolbar

doc/README.adoc, po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, tests/test_wsgi_additional.py, wsgi.py
To avoid double translation for the same thing.
Change-Id: I8396d9c36830fbcb61de7b1967f13e0257e63748
=> Settle down on "additional house numbers", not "additional housenumbers"

HACKING.adoc, data/relation.schema.yaml, data/relations.schema.yaml
Perhaps this will be better than the yamale that was removed in the
past?
Change-Id: I3f1f757ee35728c40e98193c5957d2d05f615173
=> Add yaml schema experiment

additional_housenumbers.py, additional_streets.py, config.py, cron.py, get_reference_housenumbers.py, get_reference_streets.py, invalid_refstreets.py, missing_housenumbers.py, missing_streets.py, parse_access_log.py, tests/test_areas.py, tests/test_cache.py, tests/test_cache_yamls.py, tests/test_cron.py, tests/test_get_reference_housenumbers.py, tests/test_get_reference_streets.py, tests/test_missing_housenumbers.py, tests/test_missing_streets.py, tests/test_parse_access_log.py, tests/test_util.py, tests/test_webframe.py, tests/test_wsgi.py, tests/test_wsgi_additional.py, webframe.py, wsgi.py
Which means that now workdir is no longer a mutable global state.
Change-Id: Ib5f6add8151a3edf547762b182a625a12f2afa06
=> Port to config.Config2.get_workdir()

cherry.py
'make run' was working, but not the systemd service.
Change-Id: Idd49cb54e8d475acf821ea464f58c5aa029449b5
=> sync cherry.py with wsgi.py

config.py, cron.py, get_reference_housenumbers.py, tests/test_cron.py, wsgi.py, wsgi_json.py
Avoids shared mutable state.
Change-Id: I8d5a851bb0fe95d9b3f97c36f6d75709685afc0c
=> Port to config.Config2.get_reference_housenumber_paths()

config.py, cron.py, get_reference_streets.py, wsgi.py, wsgi_json.py
Change-Id: I4fdede4ab6e1f2f0ee4847b0a71a387bc69da2bc
=> Port to config.Config2.get_reference_street_path()

config.py, cron.py, tests/test_cron.py, util.py, webframe.py
Change-Id: I9a15565a674ff19212df616f558914796c0ba161
=> Port to config.Config2.get_reference_citycounts_path()

config.py, cron.py, tests/test_config.py, tests/test_wsgi.py, util.py, wsgi.py
Change-Id: I7797da32016c5cbd62abf7f623185ad916c74af5
=> Port to config.Config2.get_locale()

config.py, tests/test_webframe.py, tests/test_wsgi_additional.py, webframe.py, wsgi.py
Which means Config.has_value() is now unused.
Change-Id: Ia8a20aa6d749183e95eda6e68342e56388544d23
=> Port to config.Config2.get_timezone()

.pylintrc, cache.py, config.py, cron.py, tests/test_cache.py, tests/test_util.py, tests/test_webframe.py, tests/test_wsgi.py, tests/test_wsgi_additional.py, tests/test_wsgi_json.py, util.py, webframe.py, wsgi.py, wsgi_additional.py, wsgi_json.py
Change-Id: I6f82d4db4c149d45a64ddd340767569cd5aa2289
=> Port to config.Config2.get_uri_prefix()

cherry.py, config.py, wsgi.py
Testsuite exec time goes from 3.999s to 1.369s.
Change-Id: I28218bbf41754756538bdabb6f0d3523a354b4ef
=> config: avoid calling out to git

data/relation-budapest_12.yaml
Change-Id: Ia0322e63ef7ad40fcb1b617b086eb017bfcb3c74
=> data: budapest_12: add Szamóca köz filter

cherry.py, config.py, wsgi.py
Change-Id: I91efdfcf10a135232e5cdc04ae0cd8d683e4c987
=> Port to config.Config2.get_tcp_port()

config.py, cron.py, overpass_query.py, tests/test_cron.py, tests/test_overpass_query.py, tests/test_util.py, util.py, wsgi.py, wsgi_json.py
Change-Id: Iddfecddc449f8b8516cdbdb4005b3ddbc5e86ad4
=> Port to config.Config2.get_overpass_uri()

cache.py, cherry.py, config.py, cron.py, overpass_query.py, parse_access_log.py, tests/test_areas.py, tests/test_cache.py, tests/test_cache_yamls.py, tests/test_cron.py, tests/test_get_reference_housenumbers.py, tests/test_get_reference_streets.py, tests/test_missing_housenumbers.py, tests/test_missing_streets.py, tests/test_overpass_query.py, tests/test_parse_access_log.py, tests/test_util.py, tests/test_webframe.py, tests/test_wsgi.py, tests/test_wsgi_additional.py, tests/test_wsgi_json.py, util.py, webframe.py, wsgi.py, wsgi_additional.py, wsgi_json.py
Change-Id: Ib64d52809983e0bfc441faed29ab1311f9cfa3a8
=> config: rename Config2 back to Config

tests/test_cache.py, tests/test_config.py
Change-Id: I81eb16759509beb5c7762e3c79752a2aec2676b4
=> Drop redundant conf.get_abspath() test

tests/test_cron.py, tests/test_get_reference_housenumbers.py, tests/test_get_reference_streets.py, tests/test_missing_streets.py, tests/test_overpass_query.py, tests/test_util.py, tests/test_webframe.py, tests/test_wsgi.py
Avoids duplication.
Change-Id: I0b6520e15c25be5b34e256da76cb06aae99d6ea5
=> tests: define the test dir name at a single place

accept_language.py, tests/test_accept_language.py, util.py
So that cast in util.py can be removed. Also remove locale support, just
language + quality is what we need.
Change-Id: I212652cce66291e84cb642d9604ccc131011ec61
=> accept_language: rework to return a typed class

HACKING.adoc
Change-Id: I0e3339b4c331c4bcf92bb468155404f3c298b287
=> Update dev doc after config changes

config.py, requirements.txt, tests/test_wsgi.py, util.py
I didn't consider that icu is not available on both public instances,
it's not that important.
Change-Id: I645bd516eff66e50cc09c7855c9eb96d4bc640ce
=> Avoid icu after all

tests/test_areas.py
Change-Id: I18892d48124b9aeb4ff1427a17573598ffdab9c0
=> test_areas: remove not used import

cache.py, config.py, tests/test_cache.py, tests/test_config.py
And reorder TestFileSystem a little to allow multiple kinds of test
values.
Change-Id: I280579df2a26c6db1b1925ef6299d055ad5fc9a0
=> test_cache.TestIsMissingHousenumbersHtmlCached.test_osm_housenumbers_new: avoid mocking

tests/test_cache.py
Change-Id: Ic52dd1c50c619cac4dcbbadf943998fcf908d41a
=> test_cache: kill remaining mocking

tests/test_validator.py, validator.py
Change-Id: Id2f8c3bcd26d618041afcf56e19e3922c2251f55
=> test_validator: kill mocking

cache_yamls.py, tests/test_cache_yamls.py, tests/test_config.py
Change-Id: I12467d7c476c10a62610fa5426bd2bdd827beaf5
=> test_cache_yamls: kill mocking

missing_housenumbers.py, tests/test_missing_housenumbers.py
Change-Id: Ie557f922af2e003239a004a8d172892e66fe241d
=> test_missing_housenumbers: kill mocking

tests/test_i18n.py
Change-Id: I52908d3401a37d974eea3ae304ee5c74d19f42f2
=> test_i18n: remove unused import

requirements.txt
Change-Id: Ide2bc8fe7a2730fd25455f115cdb25dcfb72c747
=> Update pylint to 2.8.3

config.py, cron.py, stats.py, tests/test_config.py, tests/test_stats.py
Change-Id: I75ee4de4b4f40068ab5bea29552fa0cccdfe07ab
=> test_stats.TestHandleProgress.test_happy: avoid mocking

tests/test_stats.py
Change-Id: I4fb0394bb162dc08ae756e15530660b6ba83e228
=> tests.test_stats.TestHandleProgress.test_old_time: avoid mocking

stats.py, tests/test_stats.py
Change-Id: Ie3ce62873898c45aa275f8ea61a311342695168a
=> test_stats.TestHandleTopusers: avoid mocking

config.py, parse_access_log.py, stats.py, tests/test_cron.py, tests/test_parse_access_log.py, tests/test_stats.py
Change-Id: Ifc24c5b23d41f8c4581d57955a8e30e14e577ef0
=> test_stats.TestHandleTopcities: avoid mocking

stats.py, tests/test_stats.py
Change-Id: I2f79913c8f7feb682a706575a606bc70f73af103
=> test_stats.TestHandleDailyNew: avoid mocking

stats.py, tests/test_stats.py
Change-Id: I405eaf08d12691350ad27e64e34400b8f3a9ed8b
=> test_stats.TestHandleMonthlyNew: avoid mocking

tests/test_config.py, tests/test_cron.py, tests/test_parse_access_log.py, tests/test_stats.py
Change-Id: Ib5d49316c17009dc3b4a006fdb5a8cbc9375b6c5
=> test_config: make test function for today is enough

tests/test_util.py, tools/ci-build.sh, util.py
Change-Id: Ibe6ede6608bf419dbce9f8db5431d6c37a89a118
=> CI: try to setup Hungarian locale

data/streets-template.txt
Otthon tér
Solt Ottilia tér
Alföldi József tér
Károly Róbert tér
Papp László tér
Téglagyár tér
Takarék köz
Nagyparkoló tér
Hősök tere
Pálos utca
Expo tér
Széchenyi tér
Belvárosi udvar
Madách Imre tér
Weidlich udvar
Alkotmány tér
Alkotmány tér
Kerbarátok tere
Templom tér
=> data: street-template: include amenity parking with valid street name

stats.py, tests/test_stats.py
Change-Id: Ie2bdf9e2d566c3c5f49c91da2a54528cd149fb6b
=> test_stats.TestHandleUserTotal: avoid mocking

stats.py, tests/test_stats.py
Which means that test_stats is now mock-free.
Change-Id: I4c5339375df532b0d6b1cdacf0c907e8d416ac90
=> test_stats.TestHandleMonthlyTotal: avoid mocking

tests/network/overpass-streets-gazdagret.csv, tests/test_wsgi_json.py
Change-Id: Idcd0f7e5f73aa896705d909e3397c837d46d2f77
=> test_wsgi_json.TestJsonStreets.test_update_result_json: avoid mocking

tests/test_cron.py
Change-Id: Ice60b8583cc00cbce37ccf325bf0c318866bcb47
=> test_cron.TestUpdateOsmStreets.test_happy: avoid mocking

config.py, cron.py, overpass_query.py, tests/test_config.py, tests/test_cron.py, tests/test_overpass_query.py, tests/test_util.py, util.py, wsgi.py, wsgi_json.py
Which requires a bit of rework, now we no longer raise a HTTP error on
network problems, rather we return a bytes, error tuple.
Change-Id: I802119ec17f25179668b69ad658fcc6f38f51ec2
=> test_cron.TestUpdateOsmStreets.test_http_error: avoid mocking

tests/test_cron.py
Change-Id: If1c25313ec5f41eaea754cb96edb804e7c70affb
=> test_cron.TestUpdateOsmHousenumbers.test_http_error: avoid mocking

tests/test_cron.py
and actually assert that stats.json gets updated
Change-Id: I611b1bded395d19253d677df4567f5b05e0bfee4
=> test_cron.TestUpdateStats.test_http_error: avoid mocking

config.py, parse_access_log.py, tests/test_config.py, tests/test_parse_access_log.py
Still 69 calls to unittest.mock.patch() remains.
Change-Id: I13f0d2f572603d4289230d133e144530223c076a
=> test_parse_access_log.TestMain.test_happy: avoid mocking

data/wsgi.ini.template, tools/sync-ref.sh
Change-Id: Idcb74dbfcbc22855747a5309651ec5a0665bbb23
=> Update reference to 20210629

tests/test_wsgi_additional.py, wsgi_additional.py
Change-Id: Ice36debd953d03b1f969363b6cc9149180d4c2e9
=> test_wsgi_additional.TestAdditionalStreets.test_no_osm_streets_well_formed: avoid mocking

tests/test_wsgi_additional.py, wsgi.py, wsgi_additional.py
Change-Id: I2fa29064281073a259f214bd176ace43f900f448
=> test_wsgi_additional.TestStreets.test_view_result_txt_no_osm_streets: avoid mocking

config.py, tests/test_wsgi.py
Which was the last module invoking urllib unconditionally.
Change-Id: I4ea3e5c228c31ec925f58eef70b76cab903dd18f
=> test_wsgi: avoid mock_urlopen

tests/test_parse_access_log.py
Change-Id: I2cd8ad4ad786ee25849567c4d2e185e8219a6621
=> test_parse_access_log: remove unused MockDate

data/relation-nemesgulacs.yaml
=> data: nemesgulacs: fix mapping

data/relation-balatongyorok.yaml
=> data: balatongyorok: fix mapping

config.py, parse_access_log.py, tests/test_config.py, tests/test_wsgi.py, webframe.py
Change-Id: Iad7f7882c7d696c42a97019d543afbe2991c85a4
=> test_wsgi.TestWebhooks.test_github: avoid mocking

data/wsgi.ini.template
Change-Id: Ifdd515260ffbe0df9335bc83926aa1fbfb4e26d9
=> Update reference to 20210703

tests/test_config.py, tests/test_wsgi.py
Change-Id: Ib1d6057f8df3553ed0d5551ae85688c391618e3f
=> test_wsgi.TestWebhooks.test_github_branch: avoid mocking

config.py, tests/test_config.py, tests/test_wsgi_additional.py, webframe.py
Change-Id: Ib606eafbd12cc327fda32606323cac2134c7d9af
=> test_wsgi_additional: avoid remaining mocking

ranges.py, tests/test_areas.py, tests/test_ranges.py, util.py
This won't fly in Rust.
Change-Id: Ifeba1e7e7c82c685488a36f89e6c285cc30a72a1
=> ranges: avoid interpolation default arg

tests/test_wsgi.py
Change-Id: Idb16de897d661cb6521b16107b2c5862faa7f8a4
=> test_wsgi.TestWebhooks: avoid mocking

area_files.py, areas.py, util.py, wsgi.py
Otherwise config.FileSystem can't mock these in tests.
Change-Id: Ieec222b5137f21d0d7166abdc270da9a36d77bd5
=> ref streets: switch to binary IO

area_files.py, areas.py, cache.py, cron.py, stats.py, wsgi.py
Change-Id: I48cae291c00db454bf7bcfd10b782cfbe14a5555
=> Convert the remaining non-stdout usage of TextIO to BinaryIO

area_files.py, areas.py, tests/test_wsgi.py, wsgi.py
Change-Id: Ia5fae06e35f92ed6e3c6344a9a45cb775510e157
=> test_wsgi.TestMissingHousenumbers.test_view_result_chkl_even_odd_split: avoid mocking

areas.py, cache.py, cherry.py, config.py, cron.py, overpass_query.py, parse_access_log.py, tests/test_parse_access_log.py, tests/test_webframe.py, tests/test_wsgi.py, tests/test_wsgi_json.py, util.py, webframe.py, wsgi.py, wsgi_additional.py, wsgi_json.py
Config now has all sorts of abstractions (filesystem, network, etc),
extract the actual .ini reading code into an own class.
Change-Id: Icb8e1a9d8f5a3d7ffcd6e0bc239552ae21242dab
=> config: extract Ini from Config

stats.py, tests/test_stats.py
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1463>.
Change-Id: I9a0c2b69e66e9f06a7b07d7de96c39677171ccf4
=> stats: handle missing files in get_topcities()

data/relation-budapest_12.yaml
Change-Id: I661e0b69f91e3ee6a4cd69a699e13efc3c886ae4
=> data: budapest_12: add Ada utca filter

tests/test_util.py
Still 26 to go.
Change-Id: I63ec670a5408991bec5cafbfe21b83d16745bbef
=> test_util.TestHandleOverpassError: avoid mocking

data/relation-budapest_12.yaml
Change-Id: Ie9b71b96dc83502b2a2459dbf384ee3268b46c4a
=> data: budapest: add Csipke út filter

tests/test_util.py
Still 24 to go.
Change-Id: I22a907e4fc2668263cd623866881741cae175655
=> test_util.TestSetupLocalization: avoid mocking

context.py, cron.py, tests/test_context.py, tests/test_cron.py
Still 17 to go.
Change-Id: I115aaa85dded4a6f0df6bb51605214026dae124e
=> test_cron.TestOverpassSleep: avoid mocking

.pylintrc, area_files.py, areas.py, cron.py, tests/test_areas.py, tests/test_context.py, tests/test_cron.py, wsgi.py, wsgi_json.py
Still 9 to go.
Change-Id: If0b1bbb075ccf20bf5bc1b3e3cf2a02c551ac776
=> test_cron.TestOurMain: avoid mocking

cron.py, tests/test_cron.py
Still 3 to go.
Change-Id: I2612e22f2dc4226c59d443f8cfbb02f1b239656e
=> test_cron.TestMain.test_happy: avoid mocking

context.py, cron.py, tests/test_context.py, tests/test_cron.py
Still 2 to go.
Change-Id: I2b00996c1544f4a3e5e5821c65752b99bdb89eca
=> test_cron.TestMain.test_error: avoid mocking

.pylintrc, tests/test_context.py, tests/test_webframe.py, tests/test_wsgi.py, webframe.py, wsgi.py
Still 1 to go.
Change-Id: Ie6cd12e2bea0e25997dd1cfddc969f43df2f35bf
=> test_wsgi.TestMain.test_application_exception: avoid mocking

area_files.py, areas.py, context.py, requirements.txt, tests/test_context.py, tests/test_cron.py, tests/test_util.py
Change-Id: I51213e10ab5a4af42d84f4421bcd3f23221471ca
=> Update pylint to 2.9.3

areas.py, tests/test_util.py, util.py, webframe.py
Towards typed input/output for these functions.
Change-Id: I4de6baa1e28d64d9490a16756d63de0ba0cb5668
=> util: make get_only_in_first/get_in_both require a Diff subclass

tests/test_wsgi_json.py
Change-Id: I5c86c5abc28ee1bf705b84cc46303887fe7a72d0
=> wsgi_json.TestJsonStreetHousenumbers.test_update_result_json: write to memory

tests/test_wsgi_json.py
Change-Id: Id3d65cc10145a2bc66789afad9eedc4e7b0e2716
=> test_wsgi_json.TestJsonMissingStreets.test_update_result_json: write to memory

tests/test_wsgi_json.py, tools/read-only.sh
Change-Id: If5c792ace21f94ad97625915d637888c4d9c183e
=> test_wsgi_json.TestJsonMissingHousenumbers.test_update_result_json: write to memory

tests/test_wsgi_additional.py
Change-Id: I6e1b360f3757a438a3bc19592aef84af17ff1883
=> test_wsgi_additional.TestAdditionalStreets.test_well_formed: write to memory

tests/test_wsgi_additional.py
Change-Id: Ic29bda091323597b355ad927a2533f167ee9cfde
=> test_wsgi_additional.TestAdditionalStreets.test_street_from_housenr_well_formed: write to memory

tests/test_wsgi.py, tests/test_wsgi_additional.py
Change-Id: I280c07ab9cba9d9c2a4272a0ff0b1a9569513cdb
=> test_wsgi.TestStreets.test_update_result_well_formed: write to memory

tests/test_wsgi.py
Change-Id: I49befc19d922b779d696ed3fe9f7efac42b41a31
=> test_wsgi.TestStreets.test_update_result_missing_streets_well_formed: write to memory

tests/test_wsgi.py
Change-Id: I25186c2c243a41407d238e2c2e160f99e7e098b1
=> test_wsgi.TestStreetHousenumbers.test_update_result_well_formed: write to memory

tests/test_wsgi.py
Change-Id: I3a166ebb00e44d27eef7222953c07f939d00cb26
=> test_wsgi.TestMissingStreets.test_well_formed_compat: write to memory

tests/test_wsgi.py
Change-Id: I77425f9b78fa79ad746d4f320d7ff9e102c025d0
=> test_wsgi.TestMissingStreets.test_well_formed: write to memory

tests/test_wsgi.py
Change-Id: Id86dd11d6b14dcf8b5e0bc9513791fa151044cac
=> test_wsgi.TestMissingStreets.test_update_result: write to memory

.pylintrc, area_files.py, areas.py, cache.py, context.py, cron.py, stats.py, tests/test_context.py, wsgi.py
Which allows removing unsafe casting in area_files.py and
tests/test_context.py.
Change-Id: Ie8a087f24f24fe48a1b28ec1eca3420f12bcb306
=> context: add typed opener for read and write

.github/workflows/tests.yml
Change-Id: Idebcae500dcda9701dfd7feb959a31dbf30db6dc
=> CI: update Node to 14

tests/test_wsgi.py
Change-Id: I4336fa1b5f5fcdaeabaf9aab7b25b9d4dc45deee
=> test_wsgi.TestMissingHousenumbers.test_update_result_link: write to memory

tests/test_wsgi.py
Change-Id: Ic8cd0984e291e8853d2c26119ff42cc26ffeb3c1
=> test_wsgi.TestMissingHousenumbers.test_well_formed_compat: write to memory

tests/test_areas.py
Change-Id: Ia6bfa8b6d8ea0f97b246751602a65d12fe17a2ef
=> test_areas.TestRelationFilesWriteOsmHousenumbers.test_happy: write to memory

tests/test_areas.py
Change-Id: I0c0da919fd0472db5b79931d8cd317a5e6221088
=> test_areas.TestRelationFilesWriteOsmStreets.test_happy: write to memory

tests/test_areas.py
Change-Id: If4b5dd860f884368bd95e71215399e0eb7a3f3bc
=> test_areas.TestRelationWriteMissingHouseNumbers.test_empty: write to memory

tests/test_areas.py
Change-Id: I954762130b6104bfd6cb5b1664e26e1d1bc5075f
=> test_areas.TestRelationWriteMissingHouseNumbers.test_happy: write to memory

tests/test_areas.py
Change-Id: I9be65cb9138afc700602e7bf4f0b856eb878f9b7
=> test_areas.TestRelationWriteMissingHouseNumbers.test_interpolation_all: write to memory

tests/test_areas.py
Change-Id: I0f1d0975d7de73e45d19a16f3db26b4491ab5195
=> test_areas.TestRelationWriteMissingHouseNumbers.test_sorting: write to memory

tests/test_areas.py
Change-Id: I0d8e655b77e3a25afbb7c389582792c489747e7c
=> test_areas.TestRelationWriteMissingStreets.test_happy: write to memory

tests/test_areas.py
Change-Id: Idac52cb6c8e626ef5f34b1c3985b27daf0950658
=> test_areas.TestRelationWriteRefHousenumbers.test_happy: write to memory

data/wsgi.ini.template
Change-Id: Ie07822b2430afc41a66225e75ab176fb89fd05b8
=> data: update reference to 20210801

NEWS.adoc, README.adoc
Change-Id: I372733eb4df18ca5ac84f0a7b9576215ce356f4d
=> osm-gimmisn 7.2

.pylintrc, Cargo.toml, Makefile, ranges.py, rust.pyi, setup.cfg, src/lib.rs, src/ranges.rs
Change-Id: Iae92167706c6fb9bd63945f27102cd5d0b744226
=> Port ranges.py to Rust

rust.pyi, tools/dump-deps.sh, yattag.py
yattag.py is now just a stub.
Change-Id: I3187f71d89363c5e1cf25ced78504eb37bbcf02c
=> Finish porting yattag.py to Rust

accept_language.py, tests/test_accept_language.py, util.py
So that the API is closer to what
https://crates.io/crates/accept_language/ provides.
Change-Id: I0fdb5f35188181c2f0083e19ac0553d04ef838c6
=> accept_language: simplify

Makefile
Change-Id: Ib87efcd45010ac46f2e34b256e223244dcd5ce48
=> make: rebuild when context.rs changes

data/relation-budapest_12.yaml
Change-Id: Ia3f3fe8cd9df1933d219bfa0b25418b76823737f
=> data: budapest_12: add Városkúti köz filter

Cargo.toml, api.py, context.py, rust.pyi, src/context.rs, src/lib.rs, tests/test_context.py, tests/test_stats.py
Change-Id: I08d34b4cf08de1392a36fdc00cb5e08e49b96852
=> Port context.StdTime to Rust

api.py, context.py, parse_access_log.py, rust.pyi, src/context.rs, src/lib.rs, tests/test_context.py, tests/test_parse_access_log.py, tests/test_wsgi.py
Change-Id: I81d813c769b6dbb04edc491010e2c46d8d819751
=> Port context.StdSubprocess to Rust

api.py, context.py, rust.pyi, src/context.rs, src/lib.rs, tests/test_context.py
Change-Id: Ib022a8f698816bd37c1be08bab16395a38f123e6
=> Port context.StdUnit to Rust

Cargo.toml, src/context.rs
Change-Id: Iabff15458d274903f462fc16456de9a58c2ec927
=> Replace home-grown BoxResult with the anyhow crate

Cargo.toml, context.py, rust.pyi, src/context.rs, src/lib.rs
Change-Id: I8a30930a05d8c0dddebf8ad1a3d1924fd48eedb3
=> Port context.Ini to Rust

context.py, rust.pyi, src/context.rs, src/lib.rs
Also get_ini().
Change-Id: I56db4f7f1346dd6ec0f2a77ccad0afd8b8baffe6
=> Port context.Context.get_abspath() to Rust

context.py, rust.pyi, src/context.rs, src/lib.rs
Change-Id: I41b51676a15a63d0c5dfaa7126fdeddb54bd46aa
=> Port context.Context.get/set_subprocess() to Rust

context.py, rust.pyi, src/context.rs, src/lib.rs
Change-Id: I9caa75a2c95766872432e4b249875653b4af538d
=> Port context.Context.get/set_unit() to Rust

data/relations.yaml
Change-Id: Id760f2008dd688c63f6ee808f8f91fa463af3b58
=> data: add Eger

context.py, rust.pyi, src/context.rs, src/lib.rs
Which requires a FileSystem impl backed by Python, also a Read and a
Writer impl backed by Python.
Change-Id: I973b4938332bdf701a290bfaf3fd300ea3537fdc
=> Port context.Context.get/set_file_system() to Rust

data/wsgi.ini.template
Change-Id: I5cd9296cee3c6e0dfaf3d7a2203ba9d4999722ea
=> data: update reference to 20210818

data/relation-balatonszemes.yaml
=> data: balatonszemes: drop osm-street-filters after ref update

src/context.rs, tools/dump-deps.sh
Change-Id: I3b420fa706db5f9b160bfb172abe90cb6e830e32
=> Fix warnings about unclosed Python files

data/relation-szigetmonostor.yaml
Change-Id: I9fd19cffe04888830e26a33e05c5d3bf33d28491
=> data: szigetmonostor: add Madách tér filter

data/relation-szigetmonostor.yaml
Change-Id: I433457c72c26c60654ece069d0dd0f2543caa09c
=> data: szigetmonostor: add Kossuth tér filter

Cargo.toml, context.py, overpass_query.py, rust.pyi, src/overpass_query.rs, tools/dump-deps.sh
What remains is just a stub.
Change-Id: Ic4f8a8f055abf523a6d54cea7182a9168962b6b6
=> overpass_query: port the rest to Rust

areas.py, rust.pyi, src/util.rs, src/yattag.rs, tests/test_areas.py, tests/test_util.py, util.py, webframe.py
And add a new from_string() static method to avoid the need for argument
default values in the constructor, which isn't working on the Rust side.
Change-Id: Iaf693e08b96766f8c2ba6a9c0e00298bddcb8c82
=> util: port Street to Rust

areas.py, rust.pyi, src/util.rs, src/yattag.rs, tests/test_util.py, util.py, webframe.py, wsgi.py, wsgi_additional.py
Also port html_escape().
Change-Id: Ie4a4d864b4774772e1d8f9fb518d88d7db03bdfe
=> util: port parse_filters() to Rust

Makefile, po/hu/osm-gimmisn.po, rust.pyi, src/i18n.rs, src/overpass_query.rs, src/util.rs, tests/test_util.py, util.py, wsgi.py
Which is the first Rust function that provides a string for l10n.
Also port setup_localization() and gen_link().
Change-Id: I79dee186c5f080003aeb05aed6ad7bf8af44a9ff
=> util: port handle_overpass_error() to Rust

.github/workflows/tests.yml, Makefile, areas.py, rust.pyi, src/lib.rs, src/util.rs, src/yattag.rs, util.py
Also process_template(), should_expand_range() and
html_table_from_list().
Finally make the clippy linter be part of make check.
Change-Id: If0aaf4f0b509741371252e8bd6eb9502e919c18c
=> util: port write_html_header() to Rust

areas.py, parse_access_log.py, rust.pyi, src/ranges.rs, src/util.rs, util.py, webframe.py, wsgi.py, wsgi_json.py
Also get_housenumber_ranges(), git_link() and sort_numerically().
Finally minimize the amount of places where utf-8 is mentioned for
string <-> bytes conversion.
Change-Id: Idce3fd4bdfb89f45bdd04d1e5ccc4132160bae55
=> util: port get_street_from_housenumber() to Rust

rust.pyi, src/ranges.rs, src/util.rs, tests/test_areas.py, tests/test_cron.py, tests/test_util.py, util.py, webframe.py, wsgi.py
Also port get_in_both(), get_content() and get_normalizer().
Change-Id: If274e2758da3198b11251e6738e704a47e6e7f6d
=> util: port get_only_in_first() to Rust

Cargo.toml, cache.py, cron.py, rust.pyi, src/context.rs, src/ranges.rs, src/util.rs, tests/test_util.py, util.py, webframe.py, wsgi.py, wsgi_additional.py
Also get_city_key(), get_lexical_sort_key() and get_valid_settlements().
Change-Id: I943ba08815a23cc6024b3e7f0815714144293c49
=> util: port split_house_number_by_separator() to Rust

rust.pyi, src/i18n.rs, src/util.rs, tools/dump-deps.sh, util.py
Change-Id: Id21a634d11345f1f5f29138621b4ee8e24f96695
=> Finish porting util.py to Rust

Makefile, areas.py, rust.pyi, src/areas.rs, src/lib.rs
Change-Id: Ie20620ddba52f5d173fa0cd958cc1d9311013b71
=> Start porting areas.py to Rust

areas.py, missing_housenumbers.py, rust.pyi, src/areas.rs
Change-Id: I8184d2b85655b50d26c4d02156923b3b50936993
=> Port up to areas.RelationConfig.get_alias()

data/relation-piliscsaba.yaml
=> data: piliscsaba: filter Bartók Béla utca 28.

areas.py, cache.py, rust.pyi, src/areas.rs, src/util.rs, tests/test_areas.py, wsgi.py
Change-Id: I984930035ee3eb540b2c8a73fe530f95952d29ef
=> Port up to areas.RelationConfig.set_filters()

areas.py, cache.py, rust.pyi, src/areas.rs, tests/test_areas.py, wsgi.py
Change-Id: Ib35972ba66547bcc7c52dfd6dc2e6383a637d959
=> Port up to areas.RelationConfig.should_show_ref_street()

areas.py, rust.pyi, src/areas.rs, tests/test_areas.py
Change-Id: Ic38ac2305618cd1f0c707edcda47716c25b184fc
=> Port up to areas.get_osm_street_from_ref_street()

.pylintrc, areas.py, rust.pyi, src/area_files.rs, src/areas.rs, src/context.rs, src/util.rs, tests/test_areas.py, tests/test_cron.py, wsgi.py
Change-Id: I656aab2d7012e3cfdf7556c14d95d7586f5084c1
=> Port up to areas.Relation.get_street_ranges()

areas.py, rust.pyi, src/area_files.rs, src/areas.rs, src/util.rs, tests/test_areas.py
Change-Id: Idb6f3476373912c01bd34b3d03066953e1780012
=> Port up to areas.Relation.get_osm_streets_query()

Cargo.toml, areas.py, rust.pyi, src/areas.rs, src/util.rs, tests/test_areas.py
- port normalize_housenumber_letters()
- port normalize()
Change-Id: I878d572bec4fd6ae66f92eca49377a71e9df1dd9
=> Port up to areas.Relation.get_osm_housenumbers()

areas.py, rust.pyi, src/area_files.rs, src/areas.rs, src/util.rs
Change-Id: I15c690cf553790e1b373e58980e6b4a399f396e8
=> Port areas.Relation.write_ref_streets()

areas.py, rust.pyi
Change-Id: Icbe94afa93bf90ddb02cd91f73c5e7694fd52576
=> Port areas.Relation.get_ref_streets()

areas.py, cache_yamls.py, rust.pyi, src/area_files.rs, src/areas.rs, src/util.rs
Change-Id: I745b29487907d7d8feb7b298da74d5315c00ea84
=> Port up to areas.Relation.get_missing_housenumbers()

areas.py, rust.pyi, src/areas.rs, src/util.rs
Change-Id: I6616d1d1b988f06df72bb61ce87bacb6005b23fa
=> Port areas.Relation.get_missing_streets()

Makefile, areas.py, rust.pyi, src/area_files.rs, src/areas.rs, src/util.rs, tests/test_areas.py, util.py, wsgi_additional.py
Change-Id: Ieb8b140237cb64806d5e1b898e0588ea230a9340
=> Port up to areas.Relation.get_street_valid()

Makefile, areas.py, rust.pyi, src/area_files.rs, src/areas.rs, src/util.rs, src/yattag.rs, tests/test_areas.py, tests/test_util.py, util.py
Change-Id: I6345c5191936d24d931d857025180c63d5260f42
=> Port up to areas.Relation.get_invalid_refstreets()

areas.py, rust.pyi, src/areas.rs, src/context.rs, src/util.rs, tests/test_areas.py, tests/test_util.py, tests/test_wsgi_additional.py, util.py
Change-Id: I8fc8829079dc01612d6842ec642def92f9566312
=> Port up to areas.Relations.get_workdir()

areas.py, rust.pyi, src/areas.rs, tests/test_areas.py, tests/test_cron.py
Change-Id: I8e7c8591662b965108fd6b78e7c8fd4c1c345723
=> Port up to areas.Relations.get_relations()

areas.py, rust.pyi, src/areas.rs
Change-Id: I31785805fb4880024659ed6f72ce2939ee74c1cb
=> Port up to areas.Relations.refcounty_get_refsettlement_ids()

Cargo.toml
Change-Id: I83aa51a60e2e1e60329f957a7b0f36d6c60a1b58
=> Update rust_icu to 1.0.1

data/relation-budapest_16.yaml
=> data: budapest 15: remove osm-street-streets

data/relation-budapest_16.yaml
=> data: budapest 16: remove osm-street-streets

HACKING.adoc, areas.py, rust.pyi, src/areas.rs
Change-Id: I524219368c118833b1fb8e026eaadcaf7e5511ed
=> Port up to areas.Relations.get_aliases()

data/relation-budapest_14.yaml
=> data: budapest 14: remove osm-street-streets

Makefile, rust.pyi, src/areas.rs, src/webframe.rs, tests/test_webframe.py, webframe.py, wsgi.py
Change-Id: I959cf910e2326bb22d5313070355be352eeb4654
=> Port up to webframe.get_toolbar()

Cargo.toml, rust.pyi, src/areas.rs, src/util.rs, src/webframe.rs, tests/test_areas.py, util.py, webframe.py, wsgi.py, wsgi_json.py
Change-Id: I93bd286067fb5a7f3d886d2606ec83a37d47790c
=> Port up to webframe.send_response()

cron.py, rust.pyi, src/area_files.rs, src/areas.rs, src/util.rs, src/webframe.rs, src/yattag.rs, tests/refdir/varosok_count_20190717.tsv, tests/test_areas.py, tests/test_webframe.py, webframe.py, wsgi.py
Change-Id: Ie0d4fa8113cf43d2c91c8fffa22eb80419cde250
=> Port up to webframe.format_timestamp()

rust.pyi, src/areas.rs, src/webframe.rs, tests/test_areas.py, webframe.py, wsgi.py
Change-Id: Ifa46dee6605d6858c6ece65d860f73f5b9756ab0
=> Port up to webframe.check_existing_relation()

rust.pyi, src/areas.rs, src/webframe.rs, tests/test_areas.py, webframe.py
Change-Id: I4ee41411d45f994743efe41ed130ed3fdcba060a
=> Port webframe.handle_no_osm_streets()

rust.pyi, src/webframe.rs, webframe.py
Change-Id: I3a054f776edca60d18587d74cdc7e9ad375e1b75
=> Port webframe.handle_no_osm_housenumbers()

rust.pyi, src/webframe.rs, webframe.py
Change-Id: Ife24b5ce41360fbe0dc3d0dffafdee55d1d661aa
=> Port webframe.handle_no_ref_housenumbers()

Makefile, cache.py, cache_yamls.py, cron.py, rust.pyi, src/area_files.rs, src/areas.rs, src/cache.rs, src/context.rs, src/lib.rs, src/util.rs, tests/test_areas.py, tests/test_cache_yamls.py, tests/test_cron.py, tests/test_util.py
Change-Id: Ib6d9b5de81a0fea87400258f28588880fe81a9dd
=> Port up to cache.is_additional_housenumbers_html_cached()

Makefile, cache.py, rust.pyi, src/area_files.rs, src/areas.rs, src/cache.rs, src/util.rs, tools/dump-deps.sh, wsgi.py, wsgi_json.py
Change-Id: I0b1917e7336a64929479e0c32663e866fe61abd5
=> Port up to cache.get_missing_housenumbers_txt()

data/relation-biatorbagy.yaml
=> data: biatorbagy: fix street mapping

Makefile, rust.pyi, src/area_files.rs, src/areas.rs, src/context.rs, src/lib.rs, src/wsgi_json.rs, wsgi_json.py
Change-Id: I4fa3eae83e32fe85f3a09fda484e3020dff9ff67
=> Port up to wsgi_json.missing_streets_update_result_json()

data/wsgi.ini.template
Change-Id: I15ee07734efbfc5d0cd10cac8d7d0d536f1b7cda
=> data: update reference to 20210930

Makefile, rust.pyi, src/area_files.rs, src/areas.rs, src/cache.rs, src/lib.rs, src/util.rs, src/webframe.rs, src/wsgi_additional.rs, src/wsgi_json.rs, tools/dump-deps.sh, wsgi_additional.py, wsgi_json.py
Change-Id: I072d937f67fd3138d3d013e7d73929b42c5d0178
=> Port up to wsgi_additional.additional_housenumbers_view_result()

Makefile, areas.py, rust.pyi, src/areas.rs, src/lib.rs, src/util.rs, src/webframe.rs, src/wsgi.rs, src/wsgi_additional.rs, tools/dump-deps.sh, wsgi.py, wsgi_additional.py
Change-Id: I0c8553cbec69a45d359ba019ec3442596d825ae2
=> Port up to wsgi.missing_housenumbers_view_turbo()

Makefile, rust.pyi, src/areas.rs, src/cache.rs, src/util.rs, src/webframe.rs, src/wsgi.rs, util.py, webframe.py, wsgi.py
Change-Id: I0b0b6439d2c909219c7e00a9ed195d37a721f610
=> Port up to wsgi.missing_housenumbers_view_chkl()

Makefile, rust.pyi, src/areas.rs, src/wsgi.rs, wsgi.py
Change-Id: Ia178c203fc5ffeadfcc3551c5fc646674afee15d
=> Port up to wsgi.handle_missing_housenumbers()

HACKING.adoc, rust.pyi, src/areas.rs, src/wsgi.rs, src/wsgi_additional.rs, wsgi.py, wsgi_additional.py
Change-Id: I223c53ca3765ee8f2704146c6aeebc029442111a
=> Port up to wsgi.handle_additional_housenumbers()

Makefile, rust.pyi, src/area_files.rs, src/util.rs, src/webframe.rs, src/wsgi.rs, util.py, webframe.py, wsgi.py
Change-Id: I43fbbe7f3b72949f5b7ecd98a5032fa4fef1eaf7
=> Port up to wsgi.handle_main_housenr_additional_count()

cherry.py, rust.pyi, src/areas.rs, src/util.rs, src/webframe.rs, src/wsgi.rs, src/wsgi_json.rs, tests/test_wsgi.py, tests/test_wsgi_json.py, webframe.py, wsgi.py
Change-Id: I5e1786c9d848af53a345bfc1f0ecb54964f80ff0
=> Port up to wsgi.get_html_title()

data/relation-dorog.yaml
=> data: dorog: modify Puskin utca filter

data/relation-budapest_12.yaml
Change-Id: I4c6958a0218c897ac20f1cd606efb3aa5f8c4750
=> data: budapest_12: add Dániel út filter

src/wsgi.rs, tests/test_wsgi.py
Change-Id: I2dd0ddf3233d7ed7f3720989d0bf395fcb7d6704
=> Port up to tests.test_wsgi.TestMissingHousenumbers.test_view_result_txt()

rust.pyi, src/areas.rs, src/cache.rs, src/context.rs, src/wsgi.rs, src/yattag.rs, tests/test_wsgi.py
Change-Id: I56cfc405b48f732de2fec6ebe9d0d16ebec047c6
=> Port up to tests.test_wsgi.TestMissingHousenumbers.test_view_result_chkl_even_odd_split()

rust.pyi, src/areas.rs, src/util.rs, src/wsgi.rs, tests/test_wsgi.py
Change-Id: I0fda9d0eddaa7f3dcde772db0d418ff5b7e77224
=> Port up to tests.test_wsgi.TestMissingStreets.test_no_osm_streets_well_formed()

rust.pyi, src/area_files.rs, src/areas.rs, src/cache.rs, src/lib.rs, src/webframe.rs, src/wsgi.rs, src/wsgi_additional.rs, tests/test_wsgi_additional.py
Change-Id: I52f6513b6cf8d9f20df4bb52b15efb95f4923aaf
=> Port up to tests.test_wsgi_additional.TestStreets.test_view_turbo_well_formed()

NEWS.adoc, rust.pyi, src/area_files.rs, src/bin/rouille.rs, src/wsgi.rs, src/wsgi_json.rs, tests/test_wsgi_json.py
Change-Id: I5f3a8356c762042c74a23bbc922dd56d50606653
=> Port up to tests.test_wsgi_json.TestJsonStreetHousenumbers.test_update_result_error_json()

rust.pyi, src/context.rs, src/validator.rs, validator.py
Change-Id: Ib8f46d8179f0e6e822bac2c130b0d06a9afe1cb1
=> Port up to validator.validate_filters()

Makefile, requirements.txt, rust.pyi, src/bin/validator.rs, src/lib.rs, src/validator.rs, tests/test_validator.py, validator.py
Change-Id: I4b66e47bcfdd914e916ca5b9637f36677cbe71a3
=> Finish porting validator.py

rust.pyi, src/areas.rs, src/context.rs, src/validator.rs, tests/test_validator.py
Change-Id: Ib0e19b20d5091102ef32e0b4c16f93ca35e5cb96
=> Port up to tests.test_validator.TestValidatorMainFailureMsg1.test_relation_refstreets_bad_value_type()

rust.pyi, src/areas.rs, src/context.rs, src/validator.rs, tests/test_context.py, tests/test_validator.py
Change-Id: I345987bb05edb2d54ab5923e5af012c57da08b3b
=> Port up to tests.test_validator.TestValidatorMainFailureMsg1.test_relation_filters_ranges_bad()

src/validator.rs, tests/test_validator.py
Change-Id: If119c7840bee9153d32b59d87319bb1b3f97c1c6
=> Port up to tests.test_validator.TestValidatorMainFailureMsg.test_relation_housenumber_letters_bad()

Makefile, parse_access_log.py, src/bin/parse_access_log.rs, src/lib.rs, src/parse_access_log.rs
Change-Id: If9f3b9f8337e368d8e0d19d8213c89a4a2cdfc10
=> Finish porting parse_access_log.py

.yamllint
Change-Id: I40fb721cc6f725a9f67819166dd5bad49869f549
=> Drop unused yamllint config

api.py, parse_access_log.py, rust.pyi, src/area_files.rs, src/areas.rs, src/context.rs, src/lib.rs, src/parse_access_log.rs, tests/test_context.py, tests/test_parse_access_log.py
Which allows removing PyAnyFileSystem and a number of other wrappers.
Change-Id: If7a1161bc3851214f210b23dc42696bc574a1581
=> Port test_parse_access_log.TestCheckTopEditedRelations

.gitignore, HACKING.adoc, INSTALL.adoc
Also update dev/install docs after porting.
Change-Id: I159fa1d589c8b59a22a932093bd1afedb647b670
=> Update .gitignore: remove old Python entries, add Rust ones

src/cron.rs
Related to <https://github.com/vmiklos/osm-gimmisn/issues/1839>.
Change-Id: Iabfe006a4fb5cd3ab7ffd2322de6de31769e64ac
=> cron: start writing daily .zipcount files

src/context.rs, src/parse_access_log.rs, src/webframe.rs, src/yattag.rs, tools/dump-deps.sh
It was only needed for Python.
Also link the yattag website & update dump-deps.sh.
Change-Id: Ie17443a4d379a98e009982da1926fe1eaf179b52
=> context: remove unused env arg from Subprocess::run()

.github/workflows/tests.yml
Change-Id: I7501d34637ab1dff8c5ceeea01e40ec3ec618ee7
=> CI: update to Rust 1.56

src/areas.rs
And remove error handling where we know the json value will be an
object, since the validator ensures that (in get_filter_street() and
get_street_valid()).
With this, 100% line coverage is reached in areas.rs.
Change-Id: I4e5986e5455ece4ed4fa6b92f4223a7f4911d00e
=> areas: get_osm_streets(): test the 'we got garbage, give up' case

src/wsgi.rs
This also helps 'cargo tarpaulin' to understand that the code in
question is covered with tests... I should file a bugreport in their
issue tracker about this to fix the root of the problem.
Change-Id: I0959f2e9735135e52f12dcba9dfa52d6c5be85e0
=> wsgi: factor out get_housenr_additional_count() to make it easier to read

tools/ci-build.sh
=> CI: don't build cargo-tarpaulin from source

src/bin/rouille.rs, src/wsgi.rs
This allows simplifying the untested code in src/bin/rouille.rs.
Change-Id: I95f2b18dad68044ecc4fe942d25aae7a9d4222a2
=> wsgi: take a rouille::Request in application()

src/wsgi.rs
This allows simplifying wsgi::application() further.
Change-Id: I2dd0a43ee1e34a2e10168d39027b5b36df7f9dde
=> wsgi: take a rouille::Request in our_application()

data/relation-pilisszentivan.yaml
=> data: pilisszentivan: add invalid numbers

src/util.rs, src/wsgi.rs
Allows simplifying wsgi::our_application().
Change-Id: I3644ee4e63931c15bfdb8884d9695a5508eb76ca
=> util: take a rouille::HeadersIter in setup_localization()

src/webframe.rs, src/wsgi.rs
Allows simplifying wsgi::our_application().
Change-Id: I6a48c8d5d747963281688c41167c1009860acee2
=> webframe: take a rouille::Request in handle_github_webhook()

src/webframe.rs, src/wsgi.rs
Allows simplifying wsgi::our_application().
Change-Id: I4da3829cb41b35094dfe7d89298e11a37222dae9
=> webframe: take a rouille::Request in get_request_uri()

src/bin/rouille.rs, src/webframe.rs, src/wsgi.rs, src/wsgi_json.rs
Converting the number to string, then back to number makes no sense.
Change-Id: Idfb8772fa7793b7aa46fff7520de336143dff295
=> wsgi: return a numeric static code in application()

src/bin/rouille.rs, src/webframe.rs, src/wsgi.rs
Allows simplifying the untested code in src/bin/rouille.rs.
Change-Id: Ifd43c9273eeaa3afe98b519023225a3b323c5daf
=> wsgi: return a rouille::Response in application()

src/webframe.rs, src/wsgi.rs
Allows simplifying application().
Change-Id: Ib7c73c5fa769f2f29ce05cf61d103bd3742bca2e
=> wsgi: return a rouille::Response in our_application()

src/webframe.rs
Avoid the fake javascript content type, also the explicit
Content-Encoding header handling is not needed.
Change-Id: I7f0a7bd658c78160e1674d83f1267f47cf369d46
=> webframe: simplify compress_response()

src/webframe.rs, src/wsgi.rs, src/wsgi_json.rs
Use rouille::Response instead.
Change-Id: I908750dba08b442561c8d377efe85dfc4f774e91
=> webframe: refactor to avoid an own Response

src/util.rs, src/webframe.rs
It was a duplicated type.
Change-Id: I55926653fe9fa5ce5286428e26c8b800aab927d8
=> webframe: fold util::HttpHeaders into Headers

src/yattag.rs
Eliminates 7 lock() calls which are not needed, since this is
single-threaded code.
Change-Id: I6bd983738e987bd55b083df8627963cb4ac5688d
=> yattag: refactor to avoid locking

data/relation-pilisvorosvar.yaml, data/relation-szob.yaml
=> data: szob: add more invalid numbers

src/area_files.rs, src/areas.rs, src/cache.rs, src/cache_yamls.rs, src/context.rs, src/cron.rs, src/parse_access_log.rs, src/stats.rs, src/util.rs, src/webframe.rs, src/wsgi.rs, src/wsgi_additional.rs, src/wsgi_json.rs
So far all of this code is single-threaded, just rouille handles each
requst on its own thread. So replace Arc<Mutex<>> with Rc<RefCell<>>
which is enough for us and is cheaper.
Change-Id: Ibcfb7fe28909cb209400b0d212d648a693c83286
=> Refactor to avoid locking

src/areas.rs
Its key are all untyped.
Change-Id: I852289abd94d5f0d570a25d94a4f48ef1c0ab55a
=> areas: use typed json for the toplevel relations.yaml file

src/areas.rs
And the same for:
- alias
- filters (partially)
- housenumber_letters
- inactive
- missing_streets
- osm_street_filters
- osmrelation
- refcounty
- refsettlement
- refstreets
- street_filters
Change-Id: I0ef1c59750ab8342f78721012f13469aeb5648c6
=> areas: give relation.additional_housenumbers a type

src/areas.rs
Which limits the keys and values of the filters object build-time.
Change-Id: I2af609f4da9c5ebb9a0ec8a119bcb52d32744ab0
=> areas: use typed json for relation-<name>.yaml -> filters

src/areas.rs
Which was the last untyped json usage in areas.rs (ignoring the global
yaml cache, which is intentionally not typed).
Change-Id: Ic51b56926ff4159bbbb6c198a16441cd7ec4a006
=> areas: use typed json for relation-<name>.yaml -> filters -> ranges

src/areas.rs
Replace it with proper error handling, now that we don't have to
manually check the type of each&every json field.
Change-Id: I7dbbd4a4ef205e33e22f15a6868a8d9e8e9b9ea3
=> areas: rework to avoid some unwrap() calls

src/cache_yamls.rs
anyhow::Result gives an error and the caller can decide how to handle.
unwrap() aborts immediately.
Change-Id: I22ece55832c524a8d6a88e7f969541441ce837fd
=> cache_yamls: replace some unwrap()s with error handling

src/wsgi_json.rs
Properly return the errors, don't just abort on failure.
Change-Id: I1aa25db78848203beefca9bf07cb6528014509b8
=> wsgi_json: improve error handling in non-test code

package.json
everything except the incompatible chart bits
Change-Id: Id9ba86725d26060b6210453e5578dc4ed115ce63
=> typescript: update dependencies (2021-12)

src/areas.rs, src/util.rs
Towards eliminating the --test-threads=1 flag when running tests.
Change-Id: I68eec67ac183b021fa961a52086ac23a1f7fe865
=> util: make build_street_reference_cache() use context::FileSystem

src/areas.rs
- fix areas::tests::test_relation_config_get_street_is_even_odd
- fix areas::tests::test_relation_config_is_active
- fix areas::tests::test_relation_config_should_check_missing_streets_default
- not needed, remove: test_relation_config_should_check_missing_streets_empty
- fix areas::tests::test_relation_config_should_check_missing_streets
- fix areas::tests::test_relation_config_should_show_ref_street
- fix areas::tests::test_relation_files_write_osm_housenumbers
- fix areas::tests::test_relation_files_write_osm_streets
- fix areas::tests::test_relation_get_additional_housenumbers
=> Make more tests work without a tests/data/yamls.cache file

data/relation-veroce.yaml
=> data: veroce: add Brassói út mapping

src/areas.rs
This allows an empty cache in case test code would just create a cache
with an empty "relations.yaml" key and no value.
E.g. areas::tests::test_relation_get_osm_streets_bad_overpass passes
without changes after this, even if tests/data/yamls.cache is missing.
Still 106 tests to fix.
Change-Id: Ic678567a3d8de8b6c198f03246a4a2811d760607
=> areas: tolerate missing cache entries in Rleations::new()

data/wsgi.ini.template
Change-Id: Ie461c4b3ed94dfd5086d124d75aaac29ca1e5758
=> data: update reference to 20220113

data/wsgi.ini.template
Change-Id: Ia34bd47453c8a9853cd9a52bbf8854e17b9eac11
=> data: update reference to 20220114

src/webframe.rs
So that it's possible to test it without interacting with the
filesystem.
Change-Id: I8fbbf0dd6bd915b1e388412942cdec544e996ea6
=> webframe: rework get_content_with_meta() to avoid std::fs

src/wsgi.rs
So that it's possible to set the minifized CSS in TestFileSystem.
Still 60 tests to fix.
Change-Id: I25f243b4924ecdeef1b458df92899fd6f7104d06
=> wsgi: avoid std::fs::read_to_string() in write_html_head()

src/stats.rs
This is the server-side of the change, now the cronjob places a new
"capital-progress" key into stats.json, next to the existing "progress"
one.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/2009>.
Change-Id: I97d086709b5c72554911f4440f26941ca65c73e4
=> stats: add progressbar for the capital to stats.json

NEWS.adoc, po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/browser/stats.ts, src/webframe.rs, src/wsgi.rs
Also localize the hardcoded "Reference" English string on the
whole-country progressbar if we're at it.
Addresses to <https://github.com/vmiklos/osm-gimmisn/issues/2009>.
Change-Id: I2a1b3a9a66f17e313b80530aa8f512dbf2ed8d73
=> stats: add progressbar for the capital to the web interface

.github/workflows/tests.yml
Change-Id: Ie52c509171576b7f0770487ec800ba3cb48d444b
=> Update to Rust 1.58

data/relation-lipotmezo.yaml
pass #2
follow new ref street name changes
=> data: update street mapping

data/wsgi.ini.template
Change-Id: I1da8f1b7b557fff7d90e0d62b5df889bdd1f76c2
=> data: update reference to 20220123

data/wsgi.ini.template
Change-Id: I528117596b3c90167d0051f585fa6df7767cdffa
=> data: update reference to 20220124

data/relation-budapest_11.yaml
=> data: swap start and end tag in ranges

data/wsgi.ini.template
Change-Id: I670916038857730e95c6e5f5a809d13e52ca999d
=> data: update reference to 20220125

data/wsgi.ini.template
Change-Id: I80e0b7434e4ebe7e1e93bd511524c02ee3de9b14
=> date: update reference to 20220128

package.json
Everything except the incompatible chart bits.
Change-Id: I726dbbd8869e6a3e27669b73e8fc46a3c3f68ea9
=> typescript: update dependencies (2022-01)

data/relation-hosszupalyi.yaml
=> data: hosszupalyi: remove street mapping

NEWS.adoc, README.adoc
Change-Id: I6e50d4c85274270951566b77e6cb3b7dc5f74317
=> osm-gimmisn 7.3

tests/data/relation-empty.yaml, tests/data/relation-inactiverelation.yaml, tests/data/relation-nosuchrelation.yaml, tests/data/relations.yaml
- same for nosuchrefsettlement
- same for nosuchrefcounty
- same for test
- same for empty
- same for nosuchrelation
Change-Id: I60319ce317d6b76f35a537189ebe5022025237ab
=> test data: remove no longer needed 'inactiverelation'

src/wsgi/tests.rs
Make sure that a missing pre-calculated file results in a simple empty
string and not in a fatal error.
This was only implicitly tested by tests/data/relation-budafok.yaml,
i.e. nobody asserted that the behavior is correct.
Change-Id: I01655805f03e636a852afe5fe34eb375e9894ab8
=> wsgi: add test for get_housenr_additional_count()

data/wsgi.ini.template
Change-Id: I1478a1aaf8b963fb343ed2590f2407ee3a6b132f
=> data: update reference to 20220213

src/cron/tests.rs
- Make sure that the relation that is supposed to fail is registered
- Assert that in case the osm street input is junk, then the ref
housenumbers output is empty
With this only wsgi.rs has missing test coverage when
tests/data/yamls.cache is removed.
Change-Id: Ie1dabb5d2f0295232339b39547092aad080b96b1
=> cron: improve test_update_ref_housenumbers_xml_as_csv()

Makefile, src/areas.rs, src/cache.rs, src/cron.rs, src/util.rs
We no longer need this to have full line coverage in tests.
Change-Id: Iafcef08d3e966f8ed589123666d9b40a492747ec
=> Stop creating a test favicon.ico

.github/workflows/tests.yml, Makefile
We no longer need this to have full line coverage in tests.
Change-Id: I59ac58f26cf3ed6450b9868e5868e1e3a096bbaf
=> Stop creating a test favicon.svg

data/wsgi.ini.template, tools/sync-ref.sh
Change-Id: I9d55995331700de330da3f146baccee7c4958f8f
=> data: update reference to 20220305

data/relation-budapest_11.yaml
other part is from Oltvány utca
=> data: budapest 11: remove range from Harta utca

src/cron/tests.rs
Change-Id: Ia32b73394342e9e18d7b1ec81e8bd9d3b6f35cb8
=> cron::tests::test_main: mock ref.count

data/relation-budapest_02.yaml
https://www.openstreetmap.org/note/2505642
=> data: budapest 02: filter Maci köz

src/cron/tests.rs
Change-Id: I205db3b98492fb8e4b82044fc487cc6173cadd1c
=> cron: improve test_update_stats_http_error()

src/cron/tests.rs
Change-Id: I7550b01586c2b491e228aae51aea4b9cc5f89a61
=> cron: improve test_update_stats_no_overpass()

src/cron/tests.rs
Change-Id: I7ce8bf898c69689ed136b9ef9d7a4e21bec0a664
=> cron: improve test_update_stats()

src/cron/tests.rs
Change-Id: Ief88408ba5c427199c9f6c9da345800e03ec7cfa
=> cron: improve test_our_main_stats()

data/relations.yaml
Change-Id: Ie97d4f1c3ff20afabea1d2953fbcb1188e0b085d
=> data: add gyor

src/areas.rs
motivation.
Change-Id: I8538fb38e8484be1d02f96051d8931ea3a3e98f5
=> areas: avoid std::path::Path

src/cron.rs, src/i18n.rs, src/i18n/tests.rs, src/util.rs, src/util/tests.rs, src/wsgi.rs
motivation.
Change-Id: I4a9060a28cf6f42e04e5691b3498c943f97ec25c
=> i18n: avoid std::path::Path

src/validator.rs
motivation.
Change-Id: Ia6f06eec296fe254279941a60b92d6208b3dff44
=> validator: avoid std::path::Path

data/relation-budapest_12.yaml
Change-Id: I5970f689d6c49fa6add50f1bb3e0e39529d938ec
=> data: budapest_12: add Tündérkert utca filter

Makefile
This was forgotten when test code moved out to separate files.
Change-Id: I5bf45481fc717d44593dcad97bbf63534b68cd5a
=> Re-run clippy/fmt on test changes

src/stats.rs
motivation.
Change-Id: I00bbc63705f9cbbbe37fe9fe2f5a0e02579918b2
=> stats: avoid std::path::Path

src/areas/tests.rs, src/util/tests.rs
Change-Id: Ie5022b3c6b24678ff7eb4be97441ee09e335f909
=> areas: improve test_relation_build_ref_streets()
