vmiklos/osm-gimmisn

src/cache/tests.rs
Change-Id: I044a6707afc52c6c6740c3f56d52730d3e5d522a
=> cache: improve test_is_missing_housenumbers_html_cached_no_cache()

src/cache/tests.rs
Change-Id: Ib7b89d53b24d9e60b354638a0ebfeb1cde3a6f94
=> cache: improve test_is_missing_housenumbers_html_cached_osm_housenumbers_new()

src/cache/tests.rs, src/parse_access_log/tests.rs
Change-Id: Ib5f0f7d95dbb691eebbb035371d496795151fba8
=> cache: improve test_is_missing_housenumbers_html_cached_relation_new()

src/util/tests.rs
Change-Id: I98fc8ae66b2c00f38e99c5543a7d9819e9ab6388
=> util: improve test_build_street_reference_cache_cached()

src/util/tests.rs
Change-Id: I9e0302eac2ad66c2f57972fcac06803f6f4afba2
=> util: improve test_build_street_reference_cache()

src/util.rs, src/util/tests.rs
Change-Id: I2c7fd198622ac1d40597f0596baedaf3c3ff6bee
=> util: improve test_build_reference_cache_cached()

src/stats.rs, src/stats/tests.rs
Change-Id: I462711b90129f57460f9ce11721dd23178021ffb
=> stats: improve test_handle_progress_old_time()

src/stats/tests.rs
Change-Id: I72df5a654e69b8cbb75b9cd576764e926a2144aa
=> stats: improve test_handle_progress()

src/wsgi.rs
No need to return a Result here.
Change-Id: Id61e13b9a42812d6aa344f1f0e1fe500d65a6bed
=> wsgi: simplify get_streets_last_modified()

HACKING.adoc, src/context.rs, src/context/tests.rs
Don't silently ignore errors while reading wsgi.ini.
Change-Id: Ib78ff0d40d136cbd55b0c2f567f7737a72906495
=> context: improve Ini::new()

data/wsgi.ini.template
Change-Id: I12ee6a9adeaf30c0aab5fe825ab6ad38f5beeda0
=> data: update reference to 20220410

.github/workflows/tests.yml, Cargo.toml
Also fix the version number in Cargo.toml.
Change-Id: I8efa1bd16aee96c7404327c5d836178eafc7b32e
=> Update to Rust 1.60

src/areas.rs
So no need to generate code to be able to clone.
Change-Id: Ib9402adec19a09529843bc5a114a57c8c6a1d9ea
=> areas: Relations are never cloned

data/relation-budapest_12.yaml
Change-Id: Ied001d17d6dbb96b7009011f296d437d5ffd3a23
=> data: budapest_12: add Tearózsa utca filter

src/areas/tests.rs
Change-Id: I152063066d334a7718d002a5d11e0e01f004393c
=> areas: test get_osm_streets() with non-well-formed CSV

data/relation-budapest_11.yaml, data/relation-torokbalint.yaml
=> data: budapest 11: add Prielle Kornélia filter

src/areas/tests.rs
Even cargo llvm-cov now says areas.rs has complete line coverage.
Change-Id: I1bff1398a67141f72085c223b6f7e092246ab5dc
=> areas: test get_osm_streets() failing in get_street_from_housenumber()

src/areas.rs
normalize() was quite long and expanding 2-6 to 2, 4, 6 is somewhat
self-contained.
Change-Id: I9c9a3945adf6934de7a9ff8ea08d0c3ae1c3dfb0
=> areas: extract normalize_expand() from normalize()

src/context/tests.rs
This way it's possible to test their behavior.
Change-Id: Ie8d58b45cd92b4e034d6b27f3d817ecb1b5bc9bc
=> context: don't assert, return error on open_write() / unlink() failure

data/relation-pilisszentivan.yaml
=> data: pilisszentivan: filter streets

src/cron.rs
Make it easier to examine the formatted string in a debugger.
Change-Id: I363ab0426126ac7fec61897b703c9ebeb36abb22
=> cron: clean up our_main() a little

src/cron/tests.rs
Make sure the error is handled locally, instead of failing the whole
cron process.
Change-Id: I0d6ece7009fcc91474b650e9c2060cfe182bbd20
=> cron: test what happens when the daily whole-country CSV is in fact XML

src/cron.rs
To help debugging.
Change-Id: I0bb3b2d310d40736cf0fc92e67d5ad42eb7f0503
=> cron: show log output in tests

src/util.rs
This was the last place that hardcoded \t as a delimiter instead of
using CsvRead::new().
Change-Id: I9b553ba3787074a787a981f28d767142f6e25d8b
=> util: use a CSV parser in build_street_reference_cache()

data/wsgi.ini.template
Change-Id: Icaad401a589a3c60ba4747a600300f5bf4c00769
=> data: update reference to 20220513

src/cron/tests.rs
Add multiple users, assert sorting.
Change-Id: I04796e0d71f202300aee6672303171b2936ff294
=> cron: improve test_update_stats_topusers()

data/relation-budapest_12.yaml
Change-Id: Ibde3b23e8a5db51058550dd641180bea47fd7013
=> data, budapest_12: add Mese köz filter

src/ranges/tests.rs
Pointed out by llvm-cov missing line coverage.
Change-Id: I175665d33519b5541a855f6f52cf16890ac03cd6
=> ranges: add more tests

data/wsgi.ini.template
Fixes <https://github.com/vmiklos/osm-gimmisn/issues/2270>.
Change-Id: I93e64e1c9f8400da429d181400789af6e91ffb08
=> data: update reference to 20220517

src/util.rs
It's less code and does the same.
Change-Id: I43fdd1fd02a62e4e978505d59ce31f99682b1ab8
=> util: execute regex only once in normalize_letter_suffix()

data/relation-dunaalmas.yaml, data/relations.yaml
=> data: add dunaalmas

data/relation-budapest_12.yaml
Change-Id: Ie93e03e0df20aa157e44bf20627b90afeaea68fd
=> data: budapest_12: add Mese utca filter

src/util/tests.rs
Change-Id: I9f3f44149ca9bee6f492f8d68b9d922ed94f0a0d
=> util: test get_valid_settlements() error handling

src/util/tests.rs
As reported by cargo llvm-cov.
Change-Id: Iba2a8e6b44e52a855237697a1dfd5e5ce1910fa7
=> util: add remaining tests to have complete line coverage

src/wsgi/tests.rs
Change-Id: I54282c711464ced16b3a3a188890876b65f8e894
=> webframe: test that relation is not mentioned when all invalid lists are empty

src/webframe.rs
Change-Id: I915c76068adad5851ca9133c3e85eb2ae9c5fe03
=> webframe: return early when there is no data in handle_github_webhook()

src/webframe.rs, src/wsgi/tests.rs
Change-Id: I2a284dda4ce0a9d5b25b9556c6e5a73fda5e34b3
=> webframe: test sorting in test_handle_stats_cityprogress_well_formed()

data/refcounty-names.yaml
=> Added Csongrád-Csanád megye

src/wsgi/tests.rs
Change-Id: Ic9264da05bd688edcdc8b251bfff1ec611e8cd6b
=> webframe: test sorting in test_handle_stats_zipprogress_well_formed()

src/wsgi/tests.rs
Change-Id: If0317483093562fcbb9c43ebf9824905c041ec30
=> wsgi: test sorting in missing_streets_view_txt()

data/relations.yaml
=> data: add dag

.github/workflows/tests.yml
Change-Id: I4e77c7f4e9a2b33645123bcc243a56b6bbadbf2a
=> Update to Rust 1.61

data/relation-budapest_12.yaml
Change-Id: I615017474ba05bf37b0c3a5813dc6a8958f3a4ad
=> data: budapest_12: add Dániel köz filter

data/wsgi.ini.template
Change-Id: I5e1d7385414a82c7ede396d901995fdf57c3e13e
=> data: update reference to 20220605

data/relation-budapest_11.yaml, data/relation-tokod.yaml
=> data: budapest 11: filter streets

src/validator/tests.rs, tests/data/relations-missing-osmrelation/relations.yaml
The test file contents should not be visible to other tests.
Change-Id: I54263a0cacf9bdd114d628bf369e8749591d5c71
=> validator: test_relations_missing_osmrelation: fold test file into code

src/validator/tests.rs, tests/data/relations-missing-refcounty/relations.yaml
Change-Id: I7fcbeefb3ad7009cbec81e2160bfed626b283bc6
=> validator: test_relations_missing_refcounty: fold test file into code

src/validator/tests.rs, tests/data/relations-missing-refsettlement/relations.yaml
Change-Id: I964f7bb9feb68ddb492b35553f534d8570c632b0
=> validator: test_relations_missing_refsettlement: fold test file into code

src/validator/tests.rs, tests/data/relation-gazdagret-housenumber-letters-bad.yaml
Change-Id: Iae1ee619305aed4537fc9cb518655de3039c7b6f
=> validator: test_relation_housenumber_letters_bad: fold test file into code

data/relation-budapest_12.yaml
Change-Id: I3dfd38b507de0bf26c2cd1a4b69749da096ea615
=> data: budapest_12: add Járőr utca filter

src/validator/tests.rs, tests/data/relation-gazdagret-filters-bad.yaml
Change-Id: I26c4f8c278d3d9f65bfcaa8dc731dc7cb7f3b4b7
=> validator: test_relation_filters_bad_type: fold test file into code

data/wsgi.ini.template
Change-Id: I08d6dcf994d92d378e5c0379442fe7183be22d06
=> data: update reference to 20220623

src/validator/tests.rs, tests/data/relation-gazdagret-refstreets-bad-value.yaml
Change-Id: I7c4fff46f7a0fccf5033eea2b18f5e466036e1c8
=> validator: test_relation_refstreets_bad_value_type: fold test file into code

Cargo.toml, package.json
Change-Id: I6834d70224784c433da51e08aa0acde450376e6f
=> Update dependencies (2022-06)

data/relation-alsorakos.yaml, data/relation-aquincum.yaml, data/relation-balatonszemes.yaml, data/relation-budaors-gazdasagi.yaml, data/relation-budaors-hegyvidekek.yaml, data/relation-budaors-nyugat.yaml, data/relation-budaors-szallasok.yaml, data/relation-budaors-szilvas.yaml, data/relation-budaors.yaml, data/relation-budapest_13.yaml, data/relation-budapest_16.yaml, data/relation-budapest_20.yaml, data/relation-dunaalmas.yaml, data/relation-eger.yaml, data/relation-epleny.yaml, data/relation-gyor.yaml, data/relation-hosszupalyi.yaml, data/relation-monostorpalyi.yaml, data/relation-pasaret.yaml, data/relation-szekszard.yaml, data/relation-visegrad.yaml
Suggested 18 removals and 3 additions.
Change-Id: I3a800ae39823fc8560e2180c945baa5da63d0f36
=> Update list of active relations based on 2022-05 visits data

src/validator/tests.rs, tests/data/relation-gazdagret-refstreets-quote.yaml
Change-Id: Ica95c3f978209df2122d03b567d42a3cfa8456ce
=> validator: test_relation_refstreets_quote: fold test file into code

data/relation-balatonszemes.yaml
=> data: balatonszemes: remove Nyár utca mapping

data/relation-balatonszemes.yaml
=> data: balatonszemes: filter Nyár utca

data/relation-budapest_12.yaml
Odd end is not 99, it's 17.
Change-Id: I263cbd68650c56f1480b9e5c0e724dcd68433f66
=> data: budapest_12: improve Árnyas út filter

data/wsgi.ini.template, tools/sync-ref.sh
Change-Id: I065315ad2f63268d58c536ac4729b88f3516befd
=> data: update reference to 20220704

src/validator/tests.rs, tests/data/relation-gazdagret-filter-bad.yaml
Change-Id: I811acc002fbd51e82d521f7abf775ce3d2aed310
=> validator: test_relation_filters_bad_subkey: fold test files into code

src/validator/tests.rs, tests/data/relation-gazdagret-filter-invalid-bad2.yaml
Change-Id: Ieb980e7d0e812b3c13886be5ccf0d2546e4a105e
=> validator: test_relation_filters_invalid_bad2: fold test file into code

src/validator/tests.rs, tests/data/relation-gazdagret-filter-invalid-bad-type.yaml
Change-Id: I7257cb59f871356605291825794ee769228e2af5
=> validator: test_relation_filters_invalid_bad_type: fold test file into code

.github/workflows/tests.yml, .gitignore
Change-Id: Ib7c2339ad094e6b2267e0b8e42e70e995f07281f
=> target-cov was for cargo-tarpaulin, no longer needed

src/main.rs
Mostly to get an 'osm-gimmisn --help' for free and it's less code.
Change-Id: I6187ae7db112da00d5cbf92eafb6bad70d8d5ba5
=> main: switch to clap

src/validator/tests.rs, tests/data/relation-gazdagret-filter-range-bad.yaml
Change-Id: I0440cb9b5a2a7d2fd22cc30947b87fd174817910
=> validator: test_relation_filters_ranges_bad: fold test file into code

src/validator/tests.rs, tests/data/relation-gazdagret-filter-range-bad-end.yaml
Change-Id: If56f4f9b88571e459870c6b2cdc4ac9bb56b832a
=> validator: test_relation_filters_ranges_bad_end: fold test file into code

.github/workflows/tests.yml
Change-Id: Ib38e27c651b530a0b650a08b818bc3231c4001ec
=> Update to node 16

src/validator/tests.rs, tests/data/relation-gazdagret-filter-range-start-end-swap.yaml
Change-Id: I9cb57852d619bf089f3f66cbc6da9000909a38ec
=> validator: test_relation_filters_ranges_start_end_swap: fold test file into code

src/validator/tests.rs, tests/data/relation-gazdagret-filter-range-start-end-even-odd.yaml
Change-Id: If37398b157ab016b56da25498a669d3f580dfa3b
=> validator: test_relation_filters_ranges_start_end_even_odd: fold test data into code

src/validator/tests.rs, tests/data/relation-gazdagret-filter-range-bad-start.yaml
Change-Id: I207a85af78ac85819b0506b1c39e3b91c09c45ca
=> validator: test_relation_filters_ranges_bad_start: fold test file into code

src/validator/tests.rs
Change-Id: I8cb8b7227af78eaffea27650a74e97b5ca508695
=> validator: test_relation_filters_ranges_missing_end: fold test file into code

data/wsgi.ini.template
Change-Id: I1550b2b75a448a4a720ac07ca36f339229f64d26
=> data: update reference to 20220727

NEWS.adoc, README.adoc
Change-Id: I733eb10d184dea5321552e5c44085b480c13813f
=> osm-gimmisn 7.4

src/validator/tests.rs, tests/data/relation-gazdagret-filter-show-refstreet-bad.yaml
Change-Id: I0945417986f46ea8f94df18f489dbfa022a94e6b
=> validator: test_relation_filters_show_refstreet_bad: fold test file into code

data/relation-csomor.yaml
https://www.openstreetmap.org/note/3294306#map=19/47.54885/19.22138
=> data: csomor: remove Jókai Mór út mapping

data/relation-balatonkenese.yaml
https://www.openstreetmap.org/note/3237921
=> data: balatonkenese: remove Rigóvölgyi út mapping

src/validator/tests.rs, tests/data/relation-gazdagret-refstreets-bad-map.yaml
Change-Id: Ic0c971f23eef4fdc32956db81d633083934e15d0
=> validator: test_relation_refstreets_bad_map_type: fold test file into code

src/validator/tests.rs, tests/data/relation-gazdagret-filter-valid-bad2.yaml
Change-Id: I592f2af014027d0d4667d116bf85d5cc84e9155d
=> validator: test_relation_filters_valid_bad2: fold test file into code

src/validator/tests.rs, tests/data/relation-gazdagret-filter-valid-bad-type.yaml
Change-Id: Ib4f305923348db521d3c02e95680d4c72326f88f
=> validator: test_relation_filters_valid_bad_type: fold test file into code

data/relation-budapest_11.yaml, data/relation-csomor.yaml
#szuletesnap2022 #OpenStreetMap18
=> data: csomor: fix mapping

data/relations.yaml
Change-Id: Ib0b8b69944246aa6e967c4dbac8d11150ff0b6ff
=> data: add morahalom

src/validator/tests.rs, tests/data/relation-gazdagret-filter-range-bad-start2.yaml
Change-Id: Icedb08dd8bee06649836db12344d4f6b1354dd7d
=> validator: test_start_whitespace: fold test file into code

data/relation-csomor.yaml
#szuletesnap2022 #OpenStreetMap18
=> data: csomor: add more invalid numbers

src/validator/tests.rs, tests/data/relation-gazdagret-filter-range-bad-end2.yaml
Change-Id: I08d8b55e71dc6742b227efc4a17d04c8068f1584
=> validator: test_end_whitespace: fold test file into code

data/relation-siofok.yaml
=> data: siofok: fix mapping

tests/data/relation-gazdagret-filter-range-missing-start.yaml
Change-Id: I17247ec06047bc8b56870784987bcd2f3083d56c
=> Remove unused relation-gazdagret-filter-range-missing-start.yaml

src/validator/tests.rs, tests/data/relation-gazdagret-filter-valid-good2.yaml
Change-Id: Id371f0b5154968aa0e152033b1f7b11597927834
=> validator: fold tests/data/relation-gazdagret-filter-valid-good2.yaml into code

src/validator/tests.rs, tests/data/relation-gazdagret-filter-valid-good.yaml
Change-Id: I8247c410ff1ecffe34cae09000370791436a9ae1
=> validator: fold relation-gazdagret-filter-valid-good.yaml into code

data/relations.yaml
Change-Id: I50a84dcfacac4a0e65cd4553e2de8a7dc2fed3d2
=> data: add szomod

src/wsgi.rs, src/wsgi/tests.rs, tests/data/robots.txt
Allows specifying the contents from test code.
Change-Id: Id5dee56d4ff8d52819bef8af25261bc2f5766f96
=> wsgi: stop reading robots.txt directly from the filesystem

data/relation-balatonakarattya.yaml
=> data: balatonakarattya: remove mapping

data/relation-balatonvilagos.yaml
=> data: balatonvilagos: add Hétvezér utca mapping

data/relation-balatonfoldvar.yaml
=> data: balatonfoldvar: remove mapping, filter streets

data/relation-szantod.yaml
=> data: szantod: add Vörösmarty, Kisfaludy mapping

data/relation-balatonszarszo.yaml
=> data: balatonszarszo: filter streets

data/relation-balatonboglar.yaml
=> data: balatonboglar: review mapping

data/relation-balatonboglar.yaml
=> data: balatonboglar: fix mapping

src/areas/tests.rs, src/cron/tests.rs, src/wsgi/tests.rs, src/wsgi_json/tests.rs, tests/data/streets-template.txt
- test_relation_get_osm_streets_query: don't depend on tests/data/streets-template.txt
- fix test_json_streets_update_result
- fix test_json_streets_update_result_error
- fix test_handle_streets_view_query_well_formed
- fix test_handle_streets_update_result_well_formed
- fix test_handle_streets_update_result_missing_streets_well_formed
- fix test_handle_streets_update_result_error_well_formed
- fix test_update_osm_streets_xml_as_csv
- fix test_update_osm_streets
- fix cron::tests::test_our_main
Change-Id: Id2a3c9f719604394cf405ae4af8bf891a2394c8d
=> Fold tests/data/streets-template.txt into code:

data/relation-budapest_12.yaml
Change-Id: Ieb9135c0b87d53f08e9f4de84b77f4e2d4fc828f
=> data: budapest_12: add Magas út filter

src/areas/tests.rs, src/cron/tests.rs, src/wsgi/tests.rs, src/wsgi_json/tests.rs, tests/data/street-housenumbers-template.txt
- fix wsgi_json::tests::test_json_housenumbers_update_result_error
- fix wsgi_json::tests::test_json_housenumbers_update_result
- fix wsgi::tests::test_housenumbers_view_query_well_formed
- fix wsgi::tests::test_housenumbers_update_result_well_formed
- fix wsgi::tests::test_housenumbers_update_result_error_well_formed
- fix cron::tests::test_update_osm_housenumbers_xml_as_csv
- fix cron::tests::test_update_osm_housenumbers
- fix cron::tests::test_our_main
- fix areas::tests::test_relation_get_osm_housenumbers_query
Change-Id: I7c56d15cd804003ac54b6381d3720f5542906a13
=> tests: fold data/street-housenumbers-template.txt into code

data/wsgi.ini.template
Change-Id: Ia0be8bf770e15df3c801deec70a3f7917917d0dc
=> data: update reference to 20220919

src/validator/tests.rs
Serde checks this for us.
Change-Id: Idd82142d88e8fd7a200fa5223d294127f8b993b8
=> validator: remove redundant test_relation_filters_show_refstreet_bad()

src/validator/tests.rs
Serde checks this for us.
Change-Id: Id736ac8e6aa4379b6d191ac9437c0f03d7ad5260
=> validator: remove redundant test_relation_filters_bad_type()

data/relation-budapest_12.yaml
Change-Id: I6963271df04dc72dee0deda4d3b7b4747808083a
=> data, budapest_12: add Nagykapos utca filter

data/relations.yaml
Change-Id: I996fa270f146a920ea5b2e11a4a26357f49c6487
=> data: add dunaharaszti

Cargo.toml, package.json
Change-Id: I9c40d9b8cb9d4973e83038c6871e728b6848247d
=> Update dependencies (2022-09)

data/relation-kecskemet.yaml
=> data: kecskemet: filter streets

data/wsgi.ini.template
Change-Id: I917d5d7d721bca68a632ef27752690ce21195830
=> data: update reference to 20221001

.github/workflows/tests.yml, src/areas.rs
Change-Id: I547f0d5f73d28f47309cb8e27347ae8039396a2e
=> Update to Rust 1.64

data/wsgi.ini.template
Change-Id: I8cf3f6f9d0c2ab293dc0d71d1eaca3032a84a086
=> Update reference to 20221015

Cargo.toml, src/main.rs
Handles the update of data/wsgi.ini.template, before tools/sync-ref.sh
can be invoked.
Change-Id: I31b1d4d8c07dc4d00066763ade43dc3e1d1e6d60
=> Add a new sync-ref subcommand

INSTALL.adoc, data/wsgi.ini.template, src/context.rs, src/main.rs, tests/wsgi.ini
And document the default.
Change-Id: I0c3bcd36159ff0a3e56dd27ac34f5e0c8d5526c0
=> Clean up overpass_uri from wsgi.ini.template

INSTALL.adoc, data/wsgi.ini.template, src/main.rs
And document the default.
Change-Id: Id109a7edf006cc41136b239f12669a085e4b4ee4
=> Clean up cron_update_inactive from wsgi.ini.template

src/main.rs
So it'll be easier to test this later.
Change-Id: Ic2d24631f04ee2517b832f974ac4ffca48746ee8
=> sync-ref: use context::FileSystem

data/wsgi.ini.template
Change-Id: Ic7023499987fd119a4cfd44598f9643c0e780974
=> Update reference to 20221102

Makefile, src/fixtures/network/sync-ref.html, src/lib.rs, src/main.rs, src/sync_ref.rs, src/sync_ref/tests.rs
And add tests for it.
Change-Id: Ifc49578fa95a5c61f7b770976ea5c4dd75292233
=> sync-ref: move this to a library

src/sync_ref.rs
E.g. strip_suffix() can tell us if the string has a given suffix, no
need to use ends_with() + assert.
Change-Id: I27e5515813449ac46d77346df7247826f91c53e3
=> sync-ref: improve error handling

src/context.rs, src/context/system.rs, src/context/tests.rs, src/cron.rs
It's less code and is good enough for our needs.
Change-Id: Ie6247b632bc4f30d4cc9622aa10c500024b2dc2e
=> context: automatically create parent dirs on file write

.github/workflows/tests.yml, src/context/system.rs
Change-Id: I5573a2ccfedec5c4722d37ebd13acf21f27710c6
=> Update rust to 1.65

tools/ci-build.sh
Again, we use ICU today for this.
Change-Id: Ic8ce0a25cd25b050e826bcf121506edb29a53414
=> CI: no need to install locales, either

data/wsgi.ini.template
Change-Id: I5df8aeca104cc95cd201f469d7d18e688feaf008
=> Update reference to 20221201

INSTALL.adoc
Change-Id: I0985ec61d5bf2a61410569f1e1dbbc3029c2b27a
=> sync-ref: document reference download cmdline

data/relation-budapest_12.yaml
Change-Id: I4d0f09624dd31c7483fa485c1cc002018a263068
=> data: budapest_12: add Hollós út filter

src/webframe.rs, src/wsgi.rs, tools/ci-build.sh
Change-Id: I071158a322048ac4bf900225ed116847e9d84e68
=> webframe: format_timestamp() may return an error

src/wsgi_additional.rs
Return an error at many places instead of aborting on failure.
Change-Id: Ied5e34f8aa7e6ff5bec44d23c7f46645742c9864
=> wsgi_additional: improve error handling

src/wsgi.rs
Mostly when parsing the URL, which is user-provided input, so we should
not abort when something goes wrong, rather we should return an error to
the caller.
Change-Id: Ibaf506b722c98824cb631c05b8dbf43223c0bcc8
=> wsgi: avoid some unwrap()

data/relation-budapest_12.yaml
Change-Id: Ib71e6ebb14c9f4b3199103d1a7a3ae781924b106
=> data: budapest_12: add Németvölgyi út filter

src/wsgi.rs
- return the error to the caller (instead of abort) in most cases
- simply ignore non-int relation ids in create_filter_for_refcounty()
- use split_last() instead of a len() check + last() + unwrap() in
our_application_txt() / our_application()
Change-Id: Ia0972b2f4c19e33e1ea0aebacc249da4de8508e2
=> wsgi: improve error handling, avoid the remaining unwrap() calls

src/context/system.rs, src/context/tests.rs, src/cron.rs
Right now we use both, this is towards settling down on just time.
Change-Id: I45ba54598d9880d8c9f1076d3b6492737253f3f7
=> context: switch from chrono to time

src/cron.rs, src/cron/tests.rs
Towards settling down on just time.
Change-Id: I3e1876fc85cee7a282ef45fd75b340e3bd736c78
=> cron: switch from chrono to time

data/relation-budapest_12.yaml
Change-Id: I1fbca72ccfcc4b82b1475285718149276440bf3f
=> data: budapest_12: add Kissvábhegyi út filter

src/webframe.rs
Towards settling down on just time.
Change-Id: If0811f91e5a1b6dc4316f93ea3f37c66070e179a
=> webframe: switch from chrono to time

.github/workflows/tests.yml, Cargo.lock, Cargo.toml, src/util.rs
Change-Id: Ib79473f36dd2c001a34bb67f4329dd0f41795076
=> util: replace hack in format_percent() with ICU

HACKING.md
Towards merging the documentation and the website into a single,
markdown-based guide.
Change-Id: Iff8cd7aa25132ad3e4f55805848dd06f39733cba
=> HACKING: asciidoc -> markdown

HACKING.md
Change-Id: Id921102da9c309c1aa045852fde8384a8b4ef755
=> Typo: heading 1 -> list item

INSTALL.md
Towards merging the documentation and the website into a single,
markdown-based guide.
Change-Id: Ib539b29c483d198de3462c263f747b90d8031e33
=> INSTALL: asciidoc -> markdown

doc/README.md
Towards merging the documentation and the website into a single,
markdown-based guide.
Change-Id: I5cb9d312fe915d49f01f6f805ad416ebb0d62b02
=> doc: adoc -> md

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot
Change-Id: I302bb2b807f3d9ecc64cb712c510c023f2dd9c0a
=> po: update po template & Hungarian translation

guide/src/contributors.md
Change-Id: Ie858318e730ee00cbf8d811f2801b1d61a1aeec0
=> guide: credit the contributors

src/cron.rs, src/stats.rs, src/util.rs, src/webframe.rs
It's less code due to less manual error handling.
Change-Id: I478c3917a26773fab4d7fcab02676a4d8c8c19b7
=> Switch to typed CSV parsing for refdir/city_count_<DATE>.tsv

src/webframe.rs
Change-Id: I11f01ba2f813534a3d470c7cf7b937550d6ca526
=> webframe: switch to typed CSV parsing for zipcount.csv

src/util.rs
It's less code due to less manual error handling.
Change-Id: I55ef6a3f5757160415777136cd719c5410eaa9ac
=> util: use typed CSV parser for reference streets

src/util.rs
Which was the last reference CSV we parsed without deserialize().
Change-Id: Ib156206c571a7f83314c7057c8607ecd22eab400
=> util: use typed CSV parser for reference housenumbers

src/areas.rs, src/util.rs, src/util/tests.rs, tests/workdir/street-housenumbers-test.csv
Change-Id: I4c00d567c3e6f43bc423b25ac08393068dc88c0b
=> util: switch to typed CSV parsing for OSM housenumbers

src/util.rs
Relevant for the Windows build.
Change-Id: I5b7e79269f9cddc6a69c45c80abb16189392d001
=> util: fix building without ICU

Cargo.lock, Cargo.toml, guide/src/README.md, guide/src/news.md
Change-Id: I67bd44d7f4f05eea7216f7fece7501dbab5d257c
=> osm-gimmisn v7.5

src/wsgi_json.rs
Change-Id: I2ec6cce5ecff93e97f895eb0ee9ff761b38154cc
=> wsgi_json: use variables directly in the format string

data/wsgi.ini.template
Change-Id: Iffb8f63da50e79c77dcf360a51ba8c4a2f9c7f10
=> Update reference to 20230206

.github/workflows/tests.yml
Change-Id: Ibe33010e611b23f682d663667601d1837e1e008a
=> Update Rust to 1.67

src/stats/tests.rs, tests/workdir/stats/2020-05-10.citycount
To make it more obvious what is the single test that needs it.
Change-Id: I9cc23753655cdebcacf217883b0aa80f2485eefa
=> stats: move workdir/stats/2020-05-10.citycount into code

data/relation-budapest_12.yaml, data/relation-var.yaml
Also switch "my" active relation to this from budapest_12.
Change-Id: If2832a21874a16eaa3b83efb646fc05f0b8d28dd
=> data: add Úri utca filter

data/relation-var.yaml
Change-Id: Iddefbcd8d34e05ad9522c18c9f5eb6bf01fec8f9
=> data: var: add Táncsics Mihály utca filter

src/cron.rs, src/cron/tests.rs
Change-Id: I2d13607c1eb5e61a7a5ad7ed255a88a36853d122
=> cron: write missing header for .citycount CSV files

src/cron.rs, src/cron/tests.rs
Change-Id: I5bd95ea16ce5fc4ccd8523be349cb33f67ff84af
=> cron: write missing header for .zipcount CSV files

.github/workflows/tests.yml
Which matches the version in Fedora 37
Change-Id: I67ebb84d3c44f8f8b96396ac9939f495f9392328
=> CI: update to node 18

data/relation-var.yaml
Change-Id: I3e2b896ed3260e430d2a119d841fe92ff5eec2f9
=> data: var: add Hess András tér filter

src/cron.rs
Much less code this way.
Change-Id: I22c697db15db0d8cb79821dd6f194237786a6c4f
=> cron: can use util::OsmLightHouseNumber for CSV parsing at one more place

src/stats.rs, src/stats/tests.rs
Change-Id: Ic187435289bf626f70b1a5fd1f312347f67d1be3
=> stats, handle_capital_progress: use typed CSV parsing

src/parse_access_log/tests.rs, src/stats.rs, src/stats/tests.rs
Change-Id: I8b31a024b1a2799edd1eb3cf30569d8f6f5e0c00
=> stats, get_topcities: use typed CSV parsing

src/webframe.rs
Change-Id: Ie40e08fa80b3c75becd5ff98569f22fc6d9ab98b
=> webframe: use typed CSV parsing in handle_stats_cityprogress()

src/webframe.rs
Change-Id: Idcf3bf72b6721b3e3d7dd318f44b582c8fa62f57
=> webframe: use typed CSV parsing in handle_stats_zipprogress()

src/util.rs, src/util/tests.rs
Change-Id: Ic88ad8fe861eea3e62c088fb968d5c1e34b9a4e7
=> util: switch to typed CSV parsing in get_valid_settlements()

src/cron.rs, src/overpass_query.rs, src/overpass_query/tests.rs, src/wsgi.rs, src/wsgi_json.rs
One less not needed clone().
Change-Id: Ifded3c84596678ccfef5a58ccfa140fe39102171
=> overpass_query: no need to pass query by value

src/cron.rs, src/stats.rs
So make sure we store the diff as signed.
Change-Id: I4bb7932132170fb86167f140b1a45b0e6d7f9024
=> stats: get_topcities: housenumbers in a city may decrease

guide/src/installation.md, tools/container/init.sh
Probably the easiest way to try this out locally, given that
podman/docker also works easily on Windows/macOS.
Change-Id: I957e96bb89fe43608e23127ab5fb9d52df8bea69
=> tools, container: document this

data/relation-esztergom-kozpont.yaml, data/relation-esztergom.yaml
=> data: esztergom: remove Madách Imre út mapping

guide/src/installation.md, tools/container/build.sh, tools/container/run.sh
docker works after minimal changes, and these don't break podman.
Change-Id: Ic2e0db74f539b6f554677a94cb638afdc4c2d957
=> tools, container: tweak podman invocation to also work with docker

src/sync_ref.rs, src/validator.rs, src/wsgi.rs, src/yattag.rs
Change-Id: Ifbd5ef80a72fefc6b224a1801a696eb3c2e32371
=> Avoid some unneessary cloning

data/relation-var.yaml
None of the remaining results are valid, these are from surrounding
streets / squares.
Change-Id: I44016c29a8672fdf3adfc2d573218e844127660b
=> data: var: add Szentháromság tér filter

data/relation-tahitotfalu.yaml
=> data: tahitotfalu: add Kossuth Lajos utca filter

data/relation-szigethalom.yaml, data/relation-tahitotfalu.yaml
=> data: tahitotfalu: add more invalid numbers

data/relations.yaml
Change-Id: I3c227cf838de4aa7c809caaadedfbe9e0f92bd1c
=> data: add nagybajcs

src/sync_ref.rs
I want to extend this further to see if the home-grown JSON cache can be
replaced by sqlite indexes.
Change-Id: Id16a47d07c1142a17d57eb64ddac2f09e4c67d72
=> sync-ref: extract download code to a separate function

Cargo.lock, Cargo.toml, src/sync_ref.rs
No actual insert of data yet.
Change-Id: I713fb7ed270c32abafc84fa7ddbd4f0f55796430
=> sync-ref: create indexed table on download

src/sync_ref.rs, src/sync_ref/tests.rs
Just build the indexed data, don't use it yet.
Change-Id: Iebe9bd5938621700008b994f83dcc17413cd1097
=> sync-ref: insert housenumbers / ext housenumbers into indexed sql

src/sync_ref.rs, src/sync_ref/tests.rs, src/util.rs
Move this from sync_ref so later areas can use it.
Change-Id: I1340abaca853f8397b11a3d7b6c88db7cae47f5a
=> util: add sql version of build_reference_cache()

.github/workflows/tests.yml, guide/src/hacking.md, guide/src/news.md
- don't forget to update rustc itself with the monthly dependency update
- document ref-housenumbers update speedup
Change-Id: If09ea1bdf489c079ab820e2741673964e79defe0
=> guide: update hacking and news sections

guide/src/installation.md, tools/container/Containerfile
rusqlite just takes what is provided by the system, so need to install
it explicitly.
Change-Id: I26c9c9096e48e8011d6143ad47f38d32193d9551
=> Document sqlite3 dependency

data/relation-budapest_01.yaml
=> data: budapest 01: import and merge suburb filters

src/areas/tests.rs, src/cron/tests.rs, src/wsgi/tests.rs, src/wsgi_json/tests.rs
Change-Id: Ibe93ff44e742b134f7283fa36611770c82bf9bc9
=> Clean up tests after moving ref street cache to sql

data/relation-budapest_01.yaml
Change-Id: I98629e52d7d3518977a222d7885839d88bdadf01
=> data: budapest_01: add Ostrom utca filter

src/context.rs, src/context/tests.rs, src/cron/tests.rs, src/overpass_query/tests.rs, src/sync_ref/tests.rs, src/util/tests.rs, src/wsgi/tests.rs, src/wsgi_json/tests.rs
Similar to 83d640b94701eb55bf21f361470fc14db6c4e9de (No need to hold
FileSystem by Arc, 2023-04-15).
Change-Id: I192cc7c19fc01478e85ed9230f9901f817377d6d
=> No need to hold Network by Arc

src/cache_yamls/tests.rs, src/context.rs, src/cron/tests.rs, src/missing_housenumbers/tests.rs, src/wsgi/tests.rs
Similar to 83d640b94701eb55bf21f361470fc14db6c4e9de (No need to hold
FileSystem by Arc, 2023-04-15).
Change-Id: I32eb9b40e0a069bc9658ad4dbd39f507b30d9075
=> No need to hold Unit by Arc

src/util.rs, src/webframe.rs
util already had one, that's enough.
Change-Id: Idfc50245d218b487483a38e133fc1504db1d9650
=> webframe: remove duplicated ZipCount

data/relation-budapest_10.yaml
=> data: budapest 10: add street mapping

data/relation-balatonalmadi-kaptalanfured.yaml
=> data: kaptalanfured: filter József Attila út

.github/workflows/tests.yml, Cargo.lock, Cargo.toml, package.json
Change-Id: I473e1ae7b18c3effb62253eb07f794ef37cdbd87
=> Update dependencies (2023-05)

src/validator.rs
Only handle the error locally in main()
Change-Id: I974795a6b6a99c9189784184aa1477a2fff22b91
=> validator: improve error handling

data/wsgi.ini.template
Change-Id: I0153214a35bd967f8a191c25e62934a39970357c
=> Update reference to 20230509

src/context.rs, src/cron.rs, src/cron/tests.rs, src/fixtures/network/overpass-stats.csv, src/stats.rs, src/stats/tests.rs, src/util.rs
Tis is just the cronjob part, the result still has to be exposed on the
web interface.
Change-Id: I91105cd93580a5e1b2906fa2ba482d3691a69865
=> cron, stats: collect invalid addr:city values

guide/src/news.md, po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/webframe.rs, src/webframe/tests.rs
New endpoint + refer to it.
Change-Id: I98cc592dd5d8e9662de1424fe5766480a5a6417d
=> webframe, stats: expose invalid addr:city values

data/streets-template.overpassql
=> data: street template: remove duplicated birdge filter

data/relation-budapest_02.yaml, data/relation-sulysap.yaml
=> data: budapest 02: fix mapping + sulysap filter streets

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/webframe.rs
Similar to e.g. missing housenumbers.
Change-Id: I20a9b35f0627148ba3f1c33e46761734ed5ce874
=> stats, invalid-addr-cities: add counter at the top of the web interface

data/relation-balatonkenese.yaml, data/relation-tarnok.yaml
=> data: data: filter streets, add mapping

guide/src/news.md, src/webframe.rs, src/webframe/tests.rs, src/wsgi/tests.rs
This was mixed, settle down on whole-country, since there are no plans
to support multiple countries within the same instance.
Change-Id: Ia2802dc32623724b3aa2fb2c7533ecf452745a29
=> stats: fix hungary vs whole-country inconsistency

src/context.rs, src/stats.rs
So that later the web interface can show this.
Change-Id: I9014b1ecd4747b1364cc7f24a9a4a7f4afc1924f
=> stats, invalid-addr-cities: track the time of the last update

src/stats.rs, src/webframe.rs, src/webframe/tests.rs
cron already stored this, display the value in the web interface.
Change-Id: I41084c663a69b2ecd2fb170500307a35d88c751d
=> stats, invalid-addr-cities: show last modified date

data/relation-nagymaros.yaml
=> data: nagymaros: remove Villa sor street mapping

data/wsgi.ini.template, src/sync_ref.rs
Change-Id: Ie258c19257ea5b63ffb7ba5d43c5abd2b1443ffd
=> Update reference to 20230518

data/relation-koszarhegy.yaml
=> data: koszarhegy: review mapping, filters

data/relation-budapest_01.yaml
Change-Id: I79af17a9b5be551a4551fca7f8a19eccc78c10ec
=> data, budapest_01: extend Batthyány utca filter

data/relation-vac.yaml
=> data: vac: remove Külső Rádi út mapping

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/areas.rs, src/util.rs, src/webframe.rs, src/webframe/tests.rs, src/wsgi/tests.rs
And also test that we don't list relations when they have no errors.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/2994>.
Change-Id: I0a66b9fa097ea9ab12c2d745db6c2a29fb7b5962
=> areas: find ref-not-in-reflist problems in Relation.get_invalid_refstreets()

guide/src/news.md
Change-Id: I672d59aab02fdc26771abcaeddce071de8fae192
=> guide: update news.md

data/street-housenumbers-hungary.overpassql
=> data: street-housenumbers-hungary.overpassql: add timestamp, fixme

data/relation-vac.yaml
source:	https://www.vacarchivum.hu/storage/dokumentumok/Utcanevek_Abonyi_Petertol_2022_02_24.xlsx
=> data: vac: add new comment and mapping for new ref streets

src/wsgi.rs
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3040>.
Change-Id: Ice29837e82ccc7dd4b1aa8a32f0f288da247034e
=> missing housenumbers HTML output: no ref streets is a non-fatal error

src/sql.rs, src/sql/tests.rs
Allows adding new columns to existing tables in a next commit.
Change-Id: Ibe68d9fb7392d2a529598ce55fa0d0754d2c0e20
=> sql: create initial tables based on pragma user_version

src/cron/tests.rs, src/fixtures/network/overpass-stats.csv, src/stats/tests.rs, src/util.rs
Change-Id: I482a7675bb7b420812b09de5ee801d616b25d70e
=> util: take timestamp/fixme from CSV when parsing to memory

src/areas.rs
As pointed out by the new clippy 1.70.
Change-Id: If062f1db43ae046958cf14aaf971d6380ee45f2c
=> areas: remove not needed clone()

src/sql.rs
This just adds the table; still need to populate it from cron + show it
on the web interface once we collected enough data.
Change-Id: I40daea30cd2d3dfa3264bdedda02b33d7f6ba26a
=> sql: add a new stats_invalid_addr_cities_counts table

data/wsgi.ini.template
Change-Id: Id75e948983d7750acc7b3c51d60f4ca219e9746f
=> Update reference to 20230611

data/wsgi.ini.template
Change-Id: If014f9506350b333b9b968aa0d42dc1ad34ef157
=> Update reference to 20230618

data/streets-template.overpassql
=> data: streets-template.overpassql: fix duplication in squares

data/wsgi.ini.template
Change-Id: I1f1818a78754593590cf17ff4ff30ffada3b6874
=> Update reference to 20230621

data/relation-szentkiralyszabadja.yaml
Change-Id: I2f05708ddf556e91796bc51039bd4cb6880c524f
=> data: szentkiralyszabadja: add filters

data/wsgi.ini.template
Change-Id: I18a3b597071e01cc1d93c65fee7397f933019481
=> Update reference to 20230625

data/relation-leanyfalu.yaml, data/relation-szentkiralyszabadja.yaml
=> data: leanyfalu: add more invalid numbers

data/relation-leanyfalu.yaml
=> data: leanyfalu: add street mapping

data/wsgi.ini.template
Change-Id: Ie653cd72bcbc1874392c73f916c70ff57249ebb3
=> Update reference to 20230703

data/relation-budapest_01.yaml
Change-Id: I76aee346cf45c9d4dfc4a617b9daa4baa4d324c1
=> data: budapest_01: extend Hattyú utca filter

data/wsgi.ini.template
Change-Id: Ib4979e028a56f16dd469f91394b67119edeea333
=> Update reference to 20230712

data/wsgi.ini.template
Change-Id: I3ac7e300682cec9f4d093f4803e21446e74e02eb
=> Update reference to 20230724

data/wsgi.ini.template
Change-Id: Ia7bc6151ddcbb9ac268fd02c0e9e6f5e954eea84
=> Update reference to 20230729

Cargo.lock, Cargo.toml, guide/src/README.md, guide/src/news.md
Change-Id: I3a5a1c5b611d2658beefe8dbfdb61fe5a9825e09
=> osm-gimmisn v7.6

data/relation-budapest_01.yaml
Change-Id: I5b67881c9a6c880b0e4cf5c0da0d5f6221600167
=> data: budapest_01: add Toldy lépcső filter

data/wsgi.ini.template
Change-Id: I27b550595fc993063c5f88a44a60bafa892b1bfd
=> Update reference to 20230815

data/wsgi.ini.template
Change-Id: I7d5e4dee898acf969e96f56a18a3cce788c1012d
=> Update reference to 20230819

data/relation-leanyfalu.yaml
=> data: leanyfalu: remove Szendrey Júlia utca street mapping

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/wsgi.rs, src/wsgi/tests.rs
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3073>.
Change-Id: Icce13dc67b3089704c63f293bb7e252a8fc4a0e3
=> wsgi: add initial UI for per-relation lints

data/relation-budapest_11.yaml
=> data: budapest 11: clean up filters, part 1

data/wsgi.ini.template
Change-Id: I3221c1f0a80cd8193b9514cb12d2839f642579c2
=> Update reference to 20230827

src/areas.rs, src/areas/tests.rs
Similar to the already existing RelationLintSource.
Change-Id: If5dc9d6e04e0f8c31d4e1978cc56ac79f6ec05f8
=> Add stronger type to RelationLint::reason

src/areas.rs, src/util.rs
As pointed out by clippy-1.72.
Change-Id: Idc373377d441710c25fe6800f7abcb661123f204
=> areas, util: use an array directly

data/relation-budapest_11.yaml
=> data: budapest 11: clean up filters, part 3

data/wsgi.ini.template
Change-Id: Ife5ad8fe158ef0a5187ec860b1f0db938e123edf
=> Update reference to 20230829

data/wsgi.ini.template
Change-Id: Ic17606f85233ddf803b4ad18ab4f4e59b05e7d5c
=> Update reference to 20230830

.github/workflows/tests.yml, Cargo.lock, Cargo.toml, package.json
Change-Id: I23cd8755002067e12db24b79f1c4dd760d88acb1
=> Update dependencies (2023-09)

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/areas.rs, src/areas/tests.rs, src/wsgi.rs, src/wsgi/tests.rs
Similar to what was done for the lint source.
Change-Id: Id7a8b806f12035300665de15dfd6b27bdd1fe911
=> relation lints: implement l10n for reason

src/wsgi.rs, src/wsgi/tests.rs
Change-Id: I25c29ab35589559591e8641474cbceaa67a79985
=> relation lints: test that the reason values in the table are the expected ones

data/wsgi.ini.template
Change-Id: I62f8aa2424edec6e6f8136f93c909546ba616188
=> Update reference to 20230903

data/wsgi.ini.template
Change-Id: Ieae72c285d1ba6af6832bee7dfd1c9798218d19b
=> Update reference to 20230906

data/relations.yaml
Added Pásztó to relations.yaml. Hopefully it will work.
=> Update relations.yaml, new town: Pásztó

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/areas.rs
- ignore empty street name
- ignore 0 "house number"
- add missing l10n for the new source
Change-Id: Ia6f59e4dce605b916eef0ae5f5014984007bc7c4
=> relation lints: improve the range source a bit

data/relation-budapest_11.yaml
=> data: budapest 11: clean up filters, part 4

data/relation-budapest_11.yaml
=> data: budapest 11: clean up filters, part 5

data/relation-budapest_11.yaml
=> data: budapest 11: clean up filters, part 6

data/wsgi.ini.template
Change-Id: I27f638645a5f085e228b15ab15939abe4bd54326
=> Update reference to 20230911

src/wsgi.rs
This means /missing-housenumbers/.../view-result and
/missing-housenumbers/.../view-lints is now updated similarly: a
change to data/relation-....yaml will automatically trigger an
update of the lints, no need to work things around by:
1) updating from OSM
2) visiting the /view-result page
3) visiting the new /view-lints page
anymore.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/3073>.
Change-Id: I50ea26be8d9004e9d6f04e0e1d407507b040cb11
=> relation lints: update lints automatically if the missing housenumbers json is outdated

src/areas.rs, src/areas/tests.rs, src/sql.rs, src/util.rs, src/util/tests.rs, src/wsgi.rs
Related to <https://github.com/vmiklos/osm-gimmisn/issues/3073>.
Change-Id: I2a325737a78e66c416c8d30714235f087087dc8f
=> relation lints: add OSM link for the range + created-in-osm case

Makefile
> sh: 1: eslint: not found
> make: *** [Makefile:147: src/browser/main.eslint] Error 127
> make: *** Waiting for unfinished jobs....
Change-Id: I9cd261bd1ac7450b8610460d138c99e4f41b3011
=> Fix missing eslint dependency

data/relation-budapest_11.yaml
Based on https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/budapest_11/view-lints and resurvey
=> data: budapest 11: review ranges

data/wsgi.ini.template
Change-Id: I423658368bbfacb7e97f7c5c1d478e67e29598ce
=> Update reference to 20230914

src/wsgi_additional.rs, src/wsgi_additional/tests.rs
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3288>.
Change-Id: I2103c74e799b597274c8b04fc9915c1a17fdf984
=> additional streets gpx: handle nodes

data/wsgi.ini.template
Change-Id: Id7b8e10a8628844b0df4e4a6b4108d556f759311
=> Update reference to 20230916

data/relation-pilisszanto.yaml
=> data: pilisszanto: modify mapping

data/wsgi.ini.template
Change-Id: Ia289024b473b8e60ee1858ce7b70f41448662bf6
=> Update reference to 20230919

data/relation-budapest_01.yaml
Change-Id: I1670c75269dc3dd445fd42c1d778493c0dc1dda8
=> data: budapest_01: add Szalag utca filter

data/wsgi.ini.template
Change-Id: Ice4b930264a0a63b4392bf7fd920204f4823dd0d
=> Update reference to 20230924

Cargo.lock, Cargo.toml
Change-Id: Ie9fec5c92a0ded62bb9d5122c438ab1c8c6770ee
=> Switch to bundled sqlite, fixes the Windows build

data/wsgi.ini.template
Change-Id: I643bc48a4b681eb1fa6842b85047eef2cfac31e6
=> Update reference to 20230928

data/relation-csongrad.yaml
Reverts vmiklos/osm-gimmisn#3327
=> Revert Gróf ->Gr.

data/relations.yaml
Change-Id: Id34b87e11acc01eef2b2b230615a48646dc73ace
=> data: add baja

data/wsgi.ini.template
Change-Id: I690715791e29ada764d7ed6aad483d0d9b058b7f
=> Update reference to 20231006

src/areas.rs, src/areas/tests.rs, src/wsgi/tests.rs
Change-Id: Iec04e69081bb1ef025bebb1a7711f90e60185936
=> relation lint, web ui: make out-of-range work without housenumber-letters as well

data/wsgi.ini.template
Change-Id: Iee7e49c9c90e45ca409b334455f56624cdbc2313
=> Update reference to 20231011

data/relation-budapest_11.yaml
Based on https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/budapest_11/view-lints and resurvey
=> data: budapest 11: review filters

data/relation-budapest_01.yaml
Change-Id: I0462acbc59d604e184ef247f970074125bdc8f6d
=> data: bp01: remove unused invalid items

data/relation-esztergom.yaml
Based on https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/esztergom/view-lints
=> data: esztergom: review filters

data/wsgi.ini.template
Change-Id: Ifb8b0213b9d5f14893cbc993d1fafb7dd27191c4
=> Update reference to 20231017

src/stats.rs, src/stats/tests.rs
3 more to go.
Change-Id: I96c9e274e4bfc78ff87cd0fd63a94cb299996269
=> stats: port handle_daily_total to sql

src/stats.rs, src/stats/tests.rs
2 more to go.
Change-Id: I4cd5d6b6da92c7fbb48671e33b0058112b27340b
=> stats: port handle_daily_new to sql

data/relation-budapest_01.yaml, data/relation-budapest_05.yaml, data/relation-budapest_06.yaml, data/relation-budapest_12.yaml
Turn on house number letters in districts of Budapest where completeness > 99%.
=> data: budapest: turn on house number letters

src/stats.rs, src/stats/tests.rs
1 more to go.
Change-Id: Ia2594b75f3c2ee086f404df103bde516cb230cd5
=> stats: port handle_monthly_new to sql

src/cron/tests.rs
Everything is in SQL now.
Change-Id: I12d539ae6b7f1d587433f10d4e65bdef6bd7c654
=> cron: remove last traces of <date>.count files

src/stats.rs, src/stats/tests.rs
Change-Id: I977a150bb29a50eaa926661c69414a94af4078ae
=> stats: port handle_user_total to sql

src/cron.rs, src/cron/tests.rs
Change-Id: I529e757c05a4fff6f281fe8c2d6de3f466a32c00
=> cron: stop producing .usercount files

src/cron/tests.rs
Everything is in SQL now.
Change-Id: If47e758622adad4e4d35c294648a23926639bc6f
=> cron: remove last traces of <date>.usercount files

data/wsgi.ini.template
Change-Id: I665ab5e2217cb05081a16ec4d7ce64703e899273
=> Update reference to 20231031

.github/workflows/tests.yml, src/areas.rs, src/cron.rs
It's less code and does the same.
Change-Id: I4650dbe7c499e16e863d322b8f1f0a80f438369f
=> Use of 'or_insert_with' to construct default value

src/webframe.rs, src/wsgi/tests.rs
Change-Id: I77ad3cd80bea2b6a30af2d69e1afcd5c9f1d2b2a
=> webfame: port handle_stats_zipprogress to sql

src/cron.rs, src/cron/tests.rs
Nobody consumes them anymore.
Change-Id: Ia51dc293a43a6bdf76b4c0221116aaf3b04ec9ce
=> cron: stop writing .zipcount files

data/wsgi.ini.template
Change-Id: I25dd520a526add4aad9c3dd8c5e2c78ce697b3fd
=> Update reference to 20231109

data/wsgi.ini.template
Change-Id: I7d4bfa17120535d430f03971720e7af36033a5f8
=> Update reference to 20231111

data/relation-balatonalmadi.yaml
=> data: balatonalmadi: review filters

src/sql.rs
Change-Id: I35f2a0bf0e955b998f3e848cae1f2df8b3c3381d
=> sql: add table to track OSM streets

data/wsgi.ini.template
Change-Id: Ife4ec6ecf68f7a914790add02b41194f14772103
=> Update reference to 20231112

data/wsgi.ini.template
Change-Id: Ie5e0ac2f0db0437c2e405658f23e2c356c8f58fc
=> Update reference to 20231118

src/stats.rs, src/stats/tests.rs, src/util.rs, src/util/tests.rs, tests/workdir/refs/varosok_count_20190717.tsv
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3456>.
Change-Id: I07072a267d5c0a991d2619abbe307d74e410df40
=> /lints/whole-country/invalid-addr-cities: make this case-sensitive

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/stats.rs, src/wsgi.rs
- same for /missing-streets/.../view-result
- same for /additional-streets/.../view-result
Related to <https://github.com/vmiklos/osm-gimmisn/issues/3105>.
Change-Id: Ia573b77ca1e7754e35be6a82eb2714722100b968
=> wsgi: show osm+areas time for /streets/.../view-result

tools/container/Containerfile
Make sure the instructions continue to work.
Change-Id: Ie47f70360f641ef20f24e13cb766e6f9ab6fc5ee
=> tools, container: update to Fedora 39

data/wsgi.ini.template
Change-Id: Iebcc654b4d64144b3e862831ba8df28166100374
=> Update reference to 20231126

data/relation-budapest_09.yaml
Angyal utca, Dandár utca, Gát utca, Határ út, Ipar utca, Köztelek utca, Ligeti György utca, Liliom utca, Lónyay utca, Pipa utca, Zsil utca
=> data: budapest_09: add filters

data/relation-esztergom.yaml
=> data: esztergom: remove Gróh József utca mapping

data/relation-budapest_08.yaml
Múzeum utca, Nagy Fuvaros utca, Rákóczi tér, Salétrom utca, Sárkány utca, Vásár utca
=> data: budapest_08: filter streets

src/wsgi_additional.rs, src/wsgi_additional/tests.rs, tests/workdir/streets-gh611.csv
Change-Id: Ia46bb06356543d7710cff526becd6ff095f12cc3
=> wsgi, additional housenumbers, html: take osm streets from sql

data/relation-vizivaros.yaml
Change-Id: Ia9d54f4671cc51ecf29c30d68c12f678cf97bb13
=> data: vizivaros: extend Toldy lépcső filter

src/areas.rs, src/areas/tests.rs
Change-Id: I74ca75d30d98b02fcdc9c176ad676371fb1d034a
=> areas: port Relation::is_new() and is_invalid() to sql

src/cache.rs, src/cache/tests.rs, src/cron/tests.rs
Change-Id: I5509742495be753161afa0264f3030744ddda14c
=> cache: port osm street mtime from csv to sql

src/cron/tests.rs
Change-Id: If18fe2a40b88d6633efa828d1d7157a49967d74c
=> cron: port test_update_osm_streets() to sql

data/wsgi.ini.template
Change-Id: Ic335e6f882d875341c9e12434dce71076ec20dd4
=> Update reference to 20231212

src/cron/tests.rs
13 to go.
Change-Id: I48e3b89bfe6654f825206e2e5972f30997be21a1
=> cron: port test_update_osm_streets_xml_as_csv() to sql

src/webframe.rs, src/webframe/tests.rs, src/wsgi/tests.rs
12 to go.
Change-Id: Id56b882a20b06ddb8ad1ca37699ff36b21f945c2
=> webframe, handle_invalid_refstreets: port to sql

data/relation-vizivaros.yaml
Change-Id: I8decae4c1fae19155635025965b1920523cce1ef
=> data: vizivaros: extend Szalag utca filter

src/wsgi.rs, src/wsgi/tests.rs
11 to go.
Change-Id: Ib1865edb330b64fefa450cd0ef52c3f492853ee3
=> wsgi, missing streets: port osm streets to sql

src/wsgi.rs, src/wsgi/tests.rs
6 to go.
Change-Id: I9467364c3e0ca1c6e16b9eab8f2168b12d7d3303
=> wsgi, missing street, txt: port osm streets to sql

src/wsgi_additional.rs, src/wsgi_additional/tests.rs
3 to go.
Change-Id: Id0d1b576f8b3d4a39b4f197a9d6bda7683fefd32
=> wsgi, additional housenumbers: port osm streets to sql

src/wsgi_additional.rs, src/wsgi_additional/tests.rs, tests/workdir/streets-gazdagret.csv
Which was the last place depending on
tests/workdir/streets-gazdagret.csv.
Change-Id: I76f3653ecd7333ad3d4f12628a4cfb2c1fec1f48
=> additional streets, txt output: port osm streets to sql

src/cron.rs
OSM streets are now in sql.
Change-Id: I3999e14c9de7989505465c373dde750a8169d046
=> cron: simplify can use stats::has_sql_mtime() here

data/relation-budapest_08.yaml
Baross tér, Lóvásár utca, Luther utca, Mosonyi utca
=> data: budapest_08: add filters

data/relation-vizivaros.yaml
Change-Id: I9564da36938189e45d8e1949d62388ade26402c4
=> data: vizivaros: add Kandó Kálmán utca filter

data/relation-budapest_01.yaml
Bérc utca, Kuny Domokos utca, Márvány utca, Orom utca, Pálya utca, Szirom utca
=> data: budapest_01: add filters

data/relation-budapest_01.yaml
Aladár utca, Gellérthegy utca, Naphegy tér, Zsolt utca
=> data: budapest_01: add and update filters

data/relation-budapest_01.yaml
=> data: budapest_01: convert ranges to invalid filters

data/relation-budapest_01.yaml
Batthyány utca, Bem rakpart, Berényi utca, Czakó utca, Döbrentei utca, Fazekas utca, Fő utca, Hadnagy utca, Hattyú utca, Hegyalja út, Hess András tér, Vám utca
=> data: budapest_01: update filters

src/sql.rs
Similar to commit 3ba387bdfc2694270fa548c17287258294db5a37 (sql: add
table to track OSM streets, 2023-11-13).
Change-Id: Ifc3afa2e68a8a8f75ae3bd238a2c62ee9ef62c28
=> sql: add table to track OSM housenumbers

data/relation-vizivaros.yaml
=> data: vizivaros: teszt housenumber-letters: true

data/relation-god.yaml
https://www.openstreetmap.org/note/3671524
=> data: god: filter streets

data/relation-szigetmonostor.yaml, src/area_files.rs, src/cron.rs, src/cron/tests.rs, src/fixtures/network/overpass-housenumbers-gazdagret.json, src/wsgi.rs, src/wsgi/tests.rs, src/wsgi_json.rs, src/wsgi_json/tests.rs
Similar to commit 3ef829018a136e9df9b44dbbef7596927c49bd08 (wsgi, html:
also store osm streets in sql, 2023-11-18).
Change-Id: Ia14388ef29f93fdba28e0de370452f96b3f6f9c4
=> wsgi, html: also store osm housenumbers in sql

src/wsgi.rs
Similar to commit 88a9a3f7aba5acf40b3da7048fd4646516408920 (wsgi: show
osm+areas time for /streets/.../view-result, 2023-11-24).
Related to <https://github.com/vmiklos/osm-gimmisn/issues/3105>.
Change-Id: I7de7531e715fee0d6e63b2fbee5509814eaa3be4
=> wsgi: show osm+areas time for /street-housenumbers/.../view-result

data/wsgi.ini.template
Change-Id: I8ee4b93d04fc5728880e9db827dc2811e182ac63
=> Update reference to 20231231

guide/src/news.md
Change-Id: I8620b6f677578283fe052a713e493ca3477306cc
=> guide: update news

data/relation-budapest_06.yaml
Csengery utca, Délibáb utca, Dessewffy utca, Szinyei Merse utca
=> data: budapest_06: add filters

src/wsgi_additional.rs, src/wsgi_additional/tests.rs
Similar to commit 08e981577245014d2d4c0ce0c14d98bb6809bcdb (wsgi,
additional housenumbers, html: take osm streets from sql, 2023-12-09).
Change-Id: Ib4d5110b406d1c8957d230ee389219aca3eabb2b
=> wsgi, additional housenumbers, html: take osm housenumberss from sql

src/cron/tests.rs, tests/workdir/street-housenumbers-gh195.csv, tests/workdir/street-housenumbers-gh267.csv
Similar to commit a3a439da2d484809b9bfe95a957e061b24ff7806 (cron: port
test_update_osm_streets_http_error() to sql, 2023-12-14).
Change-Id: Ib07e9b85e943c6b7c705abf349bf831b877813a1
=> cron: port test_update_osm_housenumbers_http_error() to sql

src/cron.rs
Change-Id: I15bc171965b177c819efd7b60dd187b80a22bdf8
=> cron, update_osm_housenumbers: port osm housenumbers to sql

src/wsgi.rs, src/wsgi/tests.rs
Change-Id: I333e6c6451a230516b816e1a39ed451a34007f54
=> wsgi, handle_street_housenumbers: port osm housenumbers to sql

data/wsgi.ini.template
Change-Id: Ieb640605c8464a3e992a9e8a13d9b080862647b9
=> Update reference to 20240116

src/stats.rs, src/stats/tests.rs
Which means no need to do manual error handling when a .citycount file
is missing for a given date.
Change-Id: I4de858401761752b6682ec58764f677d96b2527a
=> stats, handle_capital_progress: work from sql

data/wsgi.ini.template
Change-Id: I96abafa9b38c2fe85f2bf9d2d68d8b10d3cd9a88
=> Update reference to 20240128

Cargo.lock, Cargo.toml, guide/src/README.md, guide/src/news.md
Change-Id: I52eb0dbe8dbd72be42ee10bc582f045f5e67eb66
=> osm-gimmisn 24.2

data/wsgi.ini.template, guide/src/installation.md, src/sync_ref.rs, src/sync_ref/tests.rs
Also: www.example.com/osm -> osm.example.com, to match reality.
Change-Id: I309a751865a8a63bcc09c611741699876aa56baf
=> Update reference to 20240131

Cargo.lock, Cargo.toml, package.json
Change-Id: I657fac89698e10584b4a5c0dc1341e13e28c5b01
=> Update dependencies (2024-02)

data/relation-adyliget.yaml
=> data: adyliget: remove Határ utca filter

data/wsgi.ini.template
Change-Id: I3003732242c2a40ef86881589c0c424146f1ec84
=> Update reference to 20240204

src/wsgi_json/tests.rs
Change-Id: I003aa47b00e36d5c94d7c98a4269eb6081dfe860
=> wsgi_json: use more execute_batch()

src/wsgi_additional/tests.rs
Change-Id: I824fa6abe3a498fff299c272d2c018c094474b21
=> wsgi_additional tests: use more execute_batch()

src/cron.rs, src/stats.rs
The web UI is left unchanged for now.
Change-Id: I26d0fb580118d4dce688e4379211459470e3cb99
=> additional street counts: port cron to SQL

data/relation-budapest_02.yaml
Change-Id: I60301d81b29f6fe60049792ac768f0aace045b5f
=> data: budapest_02: add Retek utca filter

data/wsgi.ini.template
Change-Id: I388f894161e6b67d0e066f4a82b6106c8006326b
=> Update reference to 20240211

src/area_files.rs, src/wsgi.rs, src/wsgi/tests.rs
Change-Id: I3d3979cbc5c9ed8e6ddf084bd8224824447f714f
=> areas: remove last read of street ref lst files

src/area_files.rs, src/areas.rs, src/areas/tests.rs, src/browser/main.ts, src/webframe.rs, src/wsgi.rs, src/wsgi/tests.rs, src/wsgi_json.rs, src/wsgi_json/tests.rs, tests/workdir/streets-reference-gazdagret.lst
Change-Id: Icfa69d3a83ac9198ae903e74055a3459522f00f6
=> areas: remove last writes of street ref lst files

data/relation-budapest_02.yaml
Change-Id: I4b597d1b7b22030b672ce555581118a4b1d11f70
=> data: budapest_02: add Kis Rókus utca filter

src/areas/tests.rs
Change-Id: I17f0f9bd3bb0426d472b71ed176ac48780619c08
=> areas tests: use more execute_batch()

src/areas.rs, src/areas/tests.rs, src/cron.rs
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3744>.
Change-Id: Ie73e45d280cb379ecd9d6a70c878a5db61f56f91
=> cron: add a new --refarea switch

data/relation-budapest_02.yaml
Change-Id: Icc644631ed52fbc99395c5d8a83abfc20059fb6c
=> data: budapest_02: extend Káplár utca filter

src/webframe.rs
Refers to the already added update endpoint.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/3768>.
Change-Id: I6647b6ea5d3b5b9ed0fc6e0c5b336def5471eff5
=> lints, invalid-addr-cities: add update button

src/areas/tests.rs
Change-Id: I8f4b5e4e2942791b201d815be6cfd2510f5b4c26
=> area tests: use more execute_batch()

src/webframe.rs, src/webframe/tests.rs, src/wsgi_json.rs
Related to <https://github.com/vmiklos/osm-gimmisn/issues/3768>.
Change-Id: If56526eea1dbe30f5b75f3ba7ff50408c11b033a
=> lints, invalid-addr-cities: add update-result.json endpoint

src/browser/main.ts
Related to <https://github.com/vmiklos/osm-gimmisn/issues/3768>.
Change-Id: I416fa3baef6f0713d05f535ef4639ca34f79897f
=> lints, invalid-addr-cities: add JS loader

data/relation-budapest_02.yaml
Change-Id: I781b2d07b40e30b3bf310c625ca61fd989e5c2fc
=> data, budapest_02: extend Keleti Károly utca filter

data/relation-budapest_02.yaml, data/relation-orszagut.yaml
Change-Id: I8cb5797c03cf9273236c22eff8ae5a3617beeacd
=> data: budapest_02: add Tizedes utca filter

src/area_files.rs, src/area_files/tests.rs, src/cron.rs, src/cron/tests.rs, src/fixtures/network/overpass-stats.json, src/sql.rs
Related to <https://github.com/vmiklos/osm-gimmisn/issues/3792>.
Change-Id: Id129124bc03ea2574340372182bba42e278dcb0e
=> cron: get whole-country housenumbers in JSON as well

data/relation-budapest_02.yaml
Change-Id: I16bbceefe20fd5f0470f1be3ddc0a2f8f5e5f684
=> data: budapest_02: add Nyúl utca filter

src/stats.rs, src/webframe.rs, src/webframe/tests.rs
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3792>.
Change-Id: Iab34a0a690afb3b0f46bca49b94a96829f445a57
=> lints, whole-country, invalid-addr-cities: show osm+areas date in footer

src/cron.rs, src/cron/tests.rs
SQL is simpler, at least an empty table is always available.
Change-Id: Iebe9cc9672184c0289406446dce994079928361e
=> cron: port update_stats_topusers() to SQL

src/cron.rs, src/stats.rs, src/stats/tests.rs, src/util.rs, src/webframe.rs
Which was the last place where we read whole-country.csv, it seems.
Change-Id: If4cd762192e52050167ca5f10d9868f4d22e113d
=> stats: port update_invalid_addr_cities() to SQL

src/stats.rs
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3818>.
Change-Id: I26956a40cc92ba77af14de029292a43a95a9ea9a
=> stats: it's OK to not overwrite previous count from the same day

.github/workflows/tests.yml, Cargo.lock, Cargo.toml, package.json, src/i18n.rs
Change-Id: Iace0024cf30a407055e7e737b99646fdfb18e7d4
=> Update dependencies (2024-04)

src/cron.rs, src/cron/tests.rs, src/webframe/tests.rs
CSV is not needed anymore.
Change-Id: I9bc0fa8ac825208a0fdc5d10bc029693b261040a
=> cron: only get whole-country from overpass in JSON

data/relation-budapest_11.yaml
https://www.openstreetmap.org/note/4164031
=> data: budapest 11: remove Citadella út mapping

data/wsgi.ini.template
Change-Id: I6375145417ffee0268b61e8cd8c6f6cd67e910b0
=> Update reference to 20240331

data/wsgi.ini.template
Change-Id: If2dc85e311ded4560e37eeb09d3d78dbbf1559fc
=> Update reference to 20240401

data/wsgi.ini.template
Change-Id: I2398cc9b78212ded3e2fa19b7a15cd1b7dd01dd2
=> Update reference to 20240404

src/area_files.rs
Change-Id: Id3b9b0ed35d5fce3c2522e1466db41d3025cd4f9
=> area_files: log user input when json parse fails

data/relation-budapest_02.yaml
Based on notes from my previous survey.
Change-Id: I76b132f261ccc12fe3383ee09dc0efb3234a6d8c
=> data: budapest_02: extend Ezredes utca filter

data/wsgi.ini.template
Change-Id: I621a606f39ccc42aed398896210ca9ccf9e3b303
=> Update reference to 20240407

data/relation-budapest_02.yaml
Change-Id: I3fd4dde6e4474dab293ee640d4f160d6b4813ac7
=> data: budapest_02: remove no longer needed filters

data/relation-budapest_02.yaml
Change-Id: I7411dbd3e3cf5229619d83bd70ce8f864a17e8a4
=> data: budapest_02: add Garas utca filter

data/relation-budapest_02.yaml
Change-Id: Ibce90ea281cfe6d70b66fc5a113dba4f33c86949
=> data: budapest_02: extend Szilágyi Erzsébet fasor filter

guide/src/installation.md
Change-Id: I00dd6f62fd99fffabac94afb1f813d0dae7c93c9
=> guide: improve Windows build instructions

data/relation-budapest_02.yaml
Change-Id: I3a037afbd7e5bf6832cf68a3c25cd645335e9e74
=> data: budapest_02: add Lövőház utca filter

.github/workflows/tests.yml, Cargo.lock, Cargo.toml, package.json, src/areas.rs
Change-Id: I3a6b1c372f11908b6f6edf65f52203aae811eb80
=> Update dependencies (2024-05)

data/relation-budapest_02.yaml
Change-Id: Ia719f9e23269784a6b58b428c94acbadc76f5811
=> data: budapest_02: add Fillér utca filter

guide/src/hacking.md, tools/container/Containerfile
Fedora 39 -> 40
Change-Id: Ic0b67651c08dfecc7ad1cd6ed80981aa8873863b
=> tools: update the container base image

data/relation-budapest_02.yaml
Change-Id: I5a09ad9f432f867cbf46fdfdaecc34fc3d183ef2
=> data: budapest_02: add Trombitás út filter

data/wsgi.ini.template
Change-Id: Ie0bd668bda741311b04e93aba03ad9353336fecd
=> Update reference to 20240519

data/wsgi.ini.template
Change-Id: If63ed0dea92b6b98f5d1d138cfffdfe500732c55
=> Update reference to 20240527

data/relation-budapest_02.yaml
Change-Id: I6dd2d915ef7725e5c488d669e0d8da5a2c942e4b
=> data: budapest_02: add Lorántffy Zsuzsanna út filter

Cargo.lock, Cargo.toml, package.json
Change-Id: I4544b05f7bd9687c282aa6ce915c98ff4cc881b2
=> Update dependencies (2024-06)

data/relation-budapest_02.yaml
Change-Id: I375dd10e2686fa14ba51411d989c2d76130a0be5
=> data: budapest_02: add Marczibányi tér filter

data/wsgi.ini.template
Change-Id: Ifa1f7da87efb2fc7cece37fe4ab1a3d4a0443300
=> Update reference to 20240630

.github/workflows/tests.yml, Cargo.lock, Cargo.toml, package.json
Change-Id: Ib308842d0d73b33928affcfa57e460759e488f22
=> Update dependencies (2024-07)

src/areas/tests.rs
Change-Id: I8e0e7720659a9fc3b5da5577a9206c901f407e34
=> Fix areas::tests::test_relation_get_additional_housenumbers to work without street-housenumbers-reference-gazdagret.lst

src/areas/tests.rs
Change-Id: Id0bc7ef2e0f04f5ae22601a1ba42d19b0ead4f0d
=> Fix areas::tests::test_relation_get_lints to work without street-housenumbers-reference-gazdagret.lst

src/areas/tests.rs
Change-Id: I743fa7b17a69a127366bd21fad43e95ac6f1c042
=> Fix areas::tests::test_relation_write_lints to work without street-housenumbers-reference-gazdagret.lst

src/cron/tests.rs
Change-Id: I048ea3aaf005cbc5f310834e96b8a0df818c37d2
=> Use more execute_batch()

src/cron/tests.rs
Change-Id: I6a81c39bd538c7a9829f35404fe307d0c126b2be
=> cron, test_update_ref_housenumbers: drop duplicated json key

src/wsgi/tests.rs
Change-Id: Ia759104db74236178079c2d33f9697fab81bd0a7
=> Fix wsgi::tests::test_per_relation_lints to work without street-housenumbers-reference-gazdagret.lst

data/relations.yaml
Change-Id: I181c8567af51d73590d6474abc770d5be354f834
=> data: add oriszentpeter

data/relations.yaml
_I hope I've done it correctly!_
=> data: add cserkeszolo

src/wsgi_additional/tests.rs
Change-Id: I5f9fa4705a25010f124d794c39e739603b5d744c
=> Fix wsgi_additional::tests::test_additional_housenumbers_well_formed to work without street-housenumbers-reference-gazdagret.lst

data/relations.yaml
Please add Jánoshalma if possible. Thanks.
=> Add Jánoshalma to the data set

src/wsgi/tests.rs
Change-Id: Ic6f99661a3988b3c5b5a7616ce0f0bf6141d3aec
=> Fix wsgi::tests::test_missing_housenumbers_view_turbo_well_formed to work without street-housenumbers-reference-gazdagret.lst

data/wsgi.ini.template
Change-Id: I7624e02ad8e6f50232ad59a05ee49f74d2596c25
=> Update reference to 20240723

src/wsgi/tests.rs
Change-Id: I54883bb3cae83e74451045e8ae52add7628187a3
=> Fix wsgi::tests::test_missing_housenumbers_view_query_well_formed to work without street-housenumbers-reference-gazdagret.lst

src/wsgi/tests.rs
Change-Id: I91924a367cb4b04bd90a8308c33ce012ef45ba01
=> Fix wsgi::tests::test_missing_housenumbers_compat to work without street-housenumbers-reference-gazdagret.lst

src/areas/tests.rs
Change-Id: Ibe7245319a704d443025119974ca8855f5f82008
=> Fix areas::tests::test_relation_write_missing_housenumbers_interpolation_all to work without tests/workdir/street-housenumbers-reference-budafok.lst

data/wsgi.ini.template
Change-Id: Id603dd2b9c24bbd5fb6d49e2a35b219be2d1d8c3
=> Update reference to 20240730

Cargo.lock, Cargo.toml, guide/src/README.md, guide/src/news.md
Change-Id: I0e2bb5c8c7fb344770efa5ae76c6c19224bb1dce
=> osm-gimmisn 24.8

src/wsgi/tests.rs
Change-Id: Ia7fd2f1fda13647a6943e45dab2c40e2a33e9f76
=> Fix wsgi::tests::test_missing_housenumbers_view_result_chkl to work without tests/workdir/street-housenumbers-reference-budafok.lst

src/wsgi/tests.rs
Change-Id: Idebe666369ae0ddc8d7c8890ebbff387ba6ebdad
=> Fix wsgi::tests::test_missing_housenumbers_view_result_txt to work without tests/workdir/street-housenumbers-reference-budafok.lst

src/wsgi_json/tests.rs
Change-Id: Ibe1ab0263986eff602e45f6e73cfcf3803988176
=> Fix wsgi_json::tests::test_additional_housenumbers_view_result_json to work without tests/workdir/street-housenumbers-reference-budafok.lst

data/relation-budapest_02.yaml
Change-Id: Ia6425a517554dd7400e6389ee07a5fdae5d2c25f
=> data: bp02: add Balogvár utca filter

src/cron/tests.rs
Change-Id: Ibd10b9adb165d17976a5477503ceb8fdb79b1069
=> cron: fix test_update_missing_housenumbers to take ref housenumbers from sql

src/wsgi/tests.rs
Change-Id: Ieaca69042cf214dd09987d2b3621637bc1f6be58
=> wsgi: fix test_missing_housenumbers_view_result_chkl_even_odd_split to take ref housenumbers from sql

src/areas.rs, src/areas/tests.rs
The same info is in sql already, no need for this indirection anymore.
Change-Id: Ife39bb07d5506f4f8334d2a73dc64773b72410d1
=> areas: don't read street-housenumbers-reference-<relation>.lst

src/area_files.rs, src/areas.rs, src/wsgi.rs, src/wsgi/tests.rs
Which was the last user of get_ref_housenumbers_read_stream(), so drop
it.
Change-Id: Id13bb69929e24cf66001e15f8163747c981942d7
=> wsgi: don't read street-housenumbers-reference-<relation>.lst

src/area_files.rs, src/cache.rs, src/cache/tests.rs, src/sql.rs
- new additional-housenumbers-cache/<relation> key in the mtimes table
- new additional_housenumbers_cache table
Towards emptying these when the reference is updated.
Change-Id: Id7d0bc352de0da95c221ba62ef782c30a94e37b3
=> Store additional housenumbers json cache in sql

src/wsgi_additional.rs, src/wsgi_additional/tests.rs
Change-Id: I8a96e2f213f4f84a8388eef1ff0705876f456351
=> wsgi_additional: now it can't happen that ref housenumbers are not there

src/webframe.rs, src/wsgi.rs, src/wsgi/tests.rs
Change-Id: I6c600a73aed037349b7ddfd03906ebab489559a1
=> wsgi: now it can't happen that ref housenumbers are not there

src/areas.rs
Nobody reads this anymore.
Change-Id: I6bb9e886221f6dbadf40a5b3e40844da0c1e83ce
=> areas, Relation::is_new(): no need to check for ref housenumbers

src/browser/main.ts, src/wsgi_json.rs, src/wsgi_json/tests.rs
Change-Id: Iedd9e8ef70be52732a999cc5ab7b79919067d724
=> wsgi_json: remove endpoint that would write the ref housenumbers to a file, not read by anybody

src/webframe.rs, src/wsgi.rs, src/wsgi/tests.rs
Change-Id: I5b75203a44e8d3847fc17d21dfb8481f50a0a4b7
=> wsgi: remove endpoint to write ref housenumbers to file, not read by anybody

src/area_files.rs, src/area_files/tests.rs, src/areas.rs, src/areas/tests.rs, src/context/tests.rs, src/missing_housenumbers/tests.rs, src/wsgi/tests.rs, src/wsgi_additional/tests.rs, src/wsgi_json/tests.rs
Change-Id: Idd4db6430fbed50b42da5bd99ed8273ec62eba56
=> areas: remove ability to write ref housenumbers to a file

src/wsgi/tests.rs
Change-Id: I8de3d22e7ed6a85a1f639444c6b82c004a68361b
=> wsgi tests: no need to mock ref housenumbers files anymore

src/wsgi_additional/tests.rs
Change-Id: If7baf90d909e0d6fa815050b7e9cbcf60b00df01
=> wsgi_additional tests: no need to mock ref housenumbers files anymore

data/relation-szigetmonostor.yaml
Change-Id: I7786a06cebd782a1167ae3768623fa6aa179db13
=> data: szigetmonostor: extend Nagyduna sétány filter

src/wsgi_additional/tests.rs, src/wsgi_json/tests.rs
Change-Id: I69d211692eed280cd68ef5805d092738d26a123c
=> tests: remove last trace of workdir/additional-cache... json files, replaced by sql

src/cron/tests.rs
Change-Id: Icad6b0cdbed3dd7fb7ff1870f0f332a5224c4515
=> Use more execute_batch() in cron tests

src/parse_access_log/tests.rs
Change-Id: I177fe8a39585bd38fa108e3fc0ea5f07d7ca3311
=> Use more execute_batch() in parse_access_log tests

src/stats/tests.rs
Change-Id: I4010d96c866ebbf3f521542b66c3ed291029ebe3
=> Use more execute_batch() in stats tests

src/util/tests.rs
Change-Id: I05a28d50372b09dc6ad83d7b5e53352113c4f3b7
=> util: use ore execute_batch() in tests

data/wsgi.ini.template
Change-Id: Ice7905d918f79ea84f11d30f819b9a441aa07f05
=> Update reference to 20240901

src/webframe/tests.rs
Change-Id: I6ab8dba063c42e0e66a9c770a0aef92e8bf2d53f
=> webframe: use more execute_batch() in tests

src/wsgi/tests.rs
Change-Id: I89ab958ac5474db137ca8f9622bd576c25f12f83
=> wsgi: use more execute_batch() in tests

data/wsgi.ini.template
Change-Id: Ic69cd97d793dbc682feef61ba35c34d2d486b121
=> Update reference to 20240904

src/context.rs, src/wsgi_additional/tests.rs
Which removes the last use of Time::now_string().
Also, this is meant to be the last commit around the 'remove
workdir/street-housenumbers-reference-<relation>.lst files' story.
Change-Id: Idb6f2537c2278cacf31d78d251607c5a074400d8
=> wsgi_additional: use more execute_batch() in tests

data/wsgi.ini.template
Change-Id: I0ae67918a70ea04934c3a4a04237417e3492ff54
=> Update reference to 20240909

data/wsgi.ini.template
Change-Id: I1e754d5ab9bdd215a17d6ee664eec5d3da86d642
=> Update reference to 20240911

src/areas/tests.rs
Just 1 street with 3 housenumbers is enough, the rest was copy&paste.
Change-Id: I91aff8858654a8983116d9f07829669bf7d80475
=> areas tests: clean up `test_relation_get_missing_housenumbers`

data/relation-budapest_11.yaml
=> data: budapest 11: remove unused filters

guide/src/news.md, guide/src/usage.md
Change-Id: I4cc31a8d21adf0c4c354114d1ca7202db12f8fcf
=> guide: document new behavior of - in invalid lists

about.hbs
Change-Id: I49e40551f50e88b5194bc2ca493efe6be6c44a0c
=> guide: fix project name in the license bundle template

.github/workflows/tests.yml, Cargo.lock, Cargo.toml, package.json
Change-Id: Ia9579dfddb5c92610d1778da55ceec17fed48c71
=> Update dependencies (2024-10)

data/wsgi.ini.template
Change-Id: I01e1672b6cab7dff353fc362d38df188fad34da2
=> Update reference to 20241006

data/wsgi.ini.template
Change-Id: Ieabb7afb61a8b5b0dd6f2f0f1c3f7619cde47a5a
=> Update reference to 20241007

data/wsgi.ini.template
Change-Id: I605961a6e966444364ca1f18afab024ee5fe0d16
=> Update reference to 20241011

data/wsgi.ini.template
Change-Id: I2bacc1bf893f504f3e5d78daaf99e26016dbdb5d
=> Update reference to 20241013

data/wsgi.ini.template
Change-Id: I6b8645e74ba83126e65672afee0c09b4f648599e
=> Update reference to 20241017

src/main.rs
Working with the inner type directly works after all and is less code.
Change-Id: I2188a35adfdb914b6b2c1fccb2b0ed7e623d33fe
=> main: rework to avoid SenderHolder

data/wsgi.ini.template
Change-Id: I7d88ce2b669a8a26f379664faa8189026f6d7d94
=> Update reference to 20241019

data/relation-budapest_02.yaml
Change-Id: Ib928918f090b4f292c55d5b343b578c26c7cc701
=> data, bp02: extend Alvinci út filter

data/wsgi.ini.template
Change-Id: I36788303b60891ecd4b026430df413cfd7614999
=> Update reference to 20241027

data/wsgi.ini.template
Change-Id: I497e174b7dc2d0eb64c3c80aed2b846bd43478b9
=> Update reference to 20241028

data/wsgi.ini.template
Change-Id: I7022a5dd60160ec72071cf7ccb91420fce3d2872
=> Update reference to 20241029

.github/workflows/tests.yml, Cargo.lock, Cargo.toml, package.json
Change-Id: Id443c28215a89a8119065cfc0618fb77619c7d43
=> Update dependencies (2024-11)

data/relation-torokvesz.yaml
Change-Id: I30732b902deea5ffbf59a3d8bcd6e874d43b501b
=> data: torokvesz: sync with bp02

src/cron.rs, src/stats.rs, src/stats/tests.rs
Less code and works equally well.
Change-Id: I054b598866f09ec5dd6cd362d71614646f013742
=> stats: take ref.count from sql

src/cron.rs, src/cron/tests.rs
Nobody reads this anymore.
Change-Id: I882833ce4b3693aa98eee6c5e949a7d0c4966084
=> cron: stop writing workdir/stats/ref.count

data/wsgi.ini.template
Change-Id: I78628ee04db6c2c896247a2e09169c253ab6ef2d
=> CI: update linux baseline

data/wsgi.ini.template
Change-Id: I91fa51d461ddfece902cfcb8a872640525a11b75
=> Update reference to 20250101

src/overpass_query.rs, src/parse_access_log.rs, src/validator.rs
Change-Id: I2e68be94d0ee7ab7c6825fec71907ae37ed0b0c5
=> Move the regex construction outside the loops

data/wsgi.ini.template
Change-Id: I0780b656569aa834158584f5706f47375ef85c49
=> Update reference to 20250117

data/relation-szekesfehervar.yaml
added: Almássy telep, Berkes lakótelep, Horvát István lakótelep, Kisteleki utca, Ligetsor, Szedreskerti lakónegyed, Tóvárosi lakónegyed, Ybl Miklós lakótelep, Ybl Miklós utca
updated: Fáy András lakótelep, Köfém lakótelep
=> data: szekesfeher: add and update filters

src/browser/main.ts
Which was the only user of the old file.
Change-Id: I1b1be046be403a050723f4206268b61540d9fbf5
=> browser: switch from static to sql-based relations.json

data/relation-szekesfehervar.yaml
Attila, Bánáti, Belgrádi, Bereznai, Kórogyi, Zára
=> data: szekesfehervar: add filters

data/wsgi.ini.template
Change-Id: Ie7affc0bf172c1442cb84769847d18d0e1152e36
=> Update reference to 20250123

data/wsgi.ini.template
Change-Id: Ia8c4b321a1e7dac5c4c75b1958c4e7b0aa8ea983
=> Update reference to 20250125

data/relation-szekesfehervar.yaml
add Csitáry G. Emil utca, Keszegfalvi köz, Nagy Lajos király utca, Zámoly utca filter Vásártér, Sóstó ipari park, Csóri út
mapping Tigris dűlő
=> data: szekesfehervar: add filters, mappings

Cargo.lock, Cargo.toml, guide/src/README.md, guide/src/news.md
Change-Id: Iab1a4abd04ac660f5d0082f1d2ea5e3eca624fc1
=> osm-gimmisn 25.2

data/relation-budapest_02.yaml
Change-Id: I11c0a02f2b36dd39a6c006928c134be628a44210
=> data, budapest_02: add Hankóczy Jenő utca filter

data/housenumberless-settlements-hungary.overpassql
This is just the query request, it's not yet used.
Change-Id: I5025121f64e9e0f14004a15d674af03b7cd897bf
=> housenumberless-settlements: add overpass query to get all settlements in the country

src/cron.rs
I want to use this for the housenumberless-settlements check, without
introducing duplication.
Change-Id: I6cd97883179e25af69424ab5ab26f23e54cbd3ad
=> housenumberless-settlements, cron: extract the retry logic to a separate function for reuse

data/relation-szekesfehervar.yaml
Alvinci utca, Borszéki utca, Dési utca, Erzsébet út, Havranek József utca, Olaj utca, Őrhalom utca, Segesvári utca, Szüret utca, Zrínyi utca
=> data: szekesfehervar: add street filters

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/webframe.rs
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/4372>.
Change-Id: I0b8af08b4e962e26e55893b987a770ae66b55a37
=> housenumberless-settlements, webframe: link the new endpoint

data/relation-szekesfehervar.yaml
Filter for Bébic utca, Cento utca, Garam utca, Orsovai utca, Poprádi utca Mapping for Aranka utca, Homoród utca
=> data: szekesfehervar: add mappings, filters

data/wsgi.ini.template
Change-Id: Ia1b59153a483bc6aac75c3742a216685fc10f421
=> Update reference to 20250223

data/relation-szekesfehervar.yaml
Ág utca, Bőrgyár utca, Fenyőfa utca, Mezei utca, Úrhidai út
=> data: szekesfehervar: filter streets

.github/workflows/tests.yml, guide/src/hacking.md
From now on, this is meant to be checked monthly, too.
Change-Id: I55d1022700c0e66ffcf3c5fee36afcfc38482bd8
=> CI: update remaining outdated actions

data/relation-budapest_02.yaml
Change-Id: I21f52cddd9cfa92f8f3219b72066574213da693a
=> data: bp02: extend Ady Endre utca filter

src/webframe.rs, src/wsgi.rs
Related to <https://github.com/vmiklos/osm-gimmisn/issues/4470>.
Change-Id: Iff1c437b75309e07289b7fb1ce57ba3974a6fed7
=> sql: improve error handling

data/relation-budapest_02.yaml
Change-Id: I8b96cea5d9750c49811d8973449555420a738d41
=> data, bp02: add Eszter utca filter

data/relation-budapest_02.yaml
Change-Id: If78098630e0a0feab2d799505892584dfd8dc36a
=> data, bp02: add Mandula utca filter

tools/container/Containerfile
No build issues this time.
Change-Id: I192228cc89d1965f240253fd8a99139861376452
=> tools, container: update to Fedora 42

data/relation-budapest_02.yaml
Change-Id: Ia99205050c4dc304e1f5b2f25d4f433e055e12b9
=> data: bp02: add Erőd utca filter

data/wsgi.ini.template
Change-Id: I3f396b3b89e1873a0038b19a17d5a2382c012b36
=> Update reference to 20250421

data/wsgi.ini.template
Change-Id: Iec9bc55383f223239daa3f15ad0ba06ead4ff162
=> Update reference to 20250426

data/wsgi.ini.template
Change-Id: I648880b319ddc0da17f26c213ca037d2ab279bc3
=> Update reference to 20250427

data/relation-budapest_02.yaml
Change-Id: I3d6de09f43d9fb8e37056f0992141e610fbfbc29
=> data: bp02: extend Gábor Áron utca filter

data/relation-budapest_02.yaml
Change-Id: I2dd5c18fe72c5af89a3d43dcd288b0fab06815ea
=> data, bp02: extend Pasaréti út filter

data/relation-pasaret.yaml, data/relation-torokvesz.yaml
Change-Id: I1126098bf1cbf05f0ac9be4fbe4493bc6460f1d0
=> data: rebase pasaret/torokvesz on top of bp02

data/relation-budapest_14.yaml
=> data: budapest 14: filter invalid numbers

data/wsgi.ini.template
Change-Id: Ia0449f611c8ca44b1e2fd2786ca49ae7908f450f
=> Update reference to 20250525

data/relations.yaml
Change-Id: I2b4ed59273ecbaed586f6c0273208580bef8c117
=> data, relations: add bikal

data/wsgi.ini.template
Change-Id: I079798ec1b7567fd8e9aae82be3151a178f85c6b
=> Update reference to 20250529

src/wsgi.rs, src/wsgi/tests.rs
These are known to not respect robots.txt.
Change-Id: I495eb0a5502060d3ddeae7e93fb763f76428abeb
=> wsgi: reject update-result requests for some user agents

data/relation-budapest_02.yaml, data/relation-torokvesz.yaml
Change-Id: I294816c3452a6236ad20241825a345efdc59dda6
=> data, bp02: add Csalán út filter

data/relation-budapest_02.yaml
Change-Id: I883142d9d423b803403fa012a02fdaa538780778
=> data: bp02: add Orsó utca filter

data/relation-torokvesz.yaml
Change-Id: I8ce6d8ab0318145d01d63987b848c7a6910c0f23
=> data: rebase torokvesz on top of bp02

data/relation-gyula.yaml
Change-Id: Ia3893ed46dc7181a5bd3972c94cec2b4f3e00f69
=> data: gyula: add Part utca filter

src/cache.rs
Change-Id: If32849dc976167da54d01338c8a08358270af00d
=> cache: less multi-line statements

src/context.rs
Change-Id: Iea8bd5296fef0d9760804e20ff425c36d6fef7fe
=> context: less multi-line statements

src/missing_housenumbers.rs
Change-Id: Ic8cfb82391a7efcd3538068556211aae3341a4f3
=> missing_housenumbers: less multi-line statements

src/sync_ref.rs
Change-Id: I54a4166a0dcbc841354ea194282d8c2d09da8bec
=> sync_ref: less multi-line statements

src/validator.rs
Change-Id: I7b1afdc5496b8e3b15efe9b8370ae026e95ba914
=> validator: less multi-line statements

src/webframe.rs
Change-Id: Ia67fd4e5791aa8c149ba004493a9754254b02dbf
=> webframe: less multi-line statements

src/wsgi/tests.rs
This is mostly just a demo, no test uses such an xpath so far.
It also means that rustc 1.88 also thinks that we have complete line
coverage again.
Change-Id: I70d80f9e583aefd630c38c68d654616823430811
=> wsgi test: allow xpath to return a non-nodeset

data/relation-budapest_02.yaml, data/relation-torokvesz.yaml
Change-Id: Id5ce7f16a76a251c81235a0da2d78148e8b560f4
=> data: bp02: add Vöröstorony lejtő filter

data/wsgi.ini.template
Change-Id: Id08be82545b59178585913cda3f88d9d7dad3df5
=> Update reference to 20250713

data/wsgi.ini.template
Change-Id: I8bab8faad70347a8f6388d35b05964de7f54690c
=> Update reference to 20250727

.github/workflows/tests.yml, src/areas.rs, src/main.rs, src/ranges.rs, src/util.rs, src/validator.rs, src/webframe.rs
Reduces the indent of the `if` body.
Change-Id: I5c7f2edac53ebc8b48a658ed6fc3b4b981ee7b7b
=> Collapse some `if` statements

src/webframe.rs
Related to <https://github.com/vmiklos/osm-gimmisn/issues/4500>.
Change-Id: I59733b8d62f7d7184ec82a2706fefe457797b496
=> webframe, invalid-addr-cities-turbo: show ways as well

data/wsgi.ini.template
Change-Id: Ia0c62e6460c7509f48fa14d0b32939360a346273
=> Update reference to 20250906

data/relation-budapest_02.yaml, data/relation-torokvesz.yaml
Change-Id: Ia9dd9ffc35aeab322d5afa47b43557a8265cc73f
=> data, bp02: extend Nagybányai út filter

data/relation-torokvesz.yaml
Change-Id: Id54472c0fbceda12d967b9138631bbfdfcb5fb19
=> data: sync torokvesz from bp02

data/relation-budapest_02.yaml, data/relation-torokvesz.yaml
Change-Id: I046af91102c02232d898236562f58bfcc4f853e9
=> data, bp02: add Csévi utca filter
