vmiklos/osm-gimmisn

data/relation-budafok.yaml
Szürők: Balatoni út, Bimbó utca, Hajó utca, Kőérberki út, Ringló út, Vértanú utca, Vöröskúti határsor
Javítva: Kuruc köz
A Nagykőbánya utca így helyes, egybeírva. OSM-en már javítottam.
A szűrőkhöz írtam megjegyzéseket, ezek igazából nekem szólnak, így később is tudni fogom, hogy mit és miért szűrtem ki.
=> data: budafok: add filters

data/relation-alsorakos.yaml, data/relation-kiszuglo.yaml, data/relation-rakosfalva.yaml, data/relation-torokor.yaml
Olyan utcákat is hoznak a kapcsolatok, amik legfeljebb minimálisan lóghatnak át. De az utca és az összes épület a szomszédos városrészhez tartozik.
=> Zugló településrész határok pontosítása

data/relation-budapest_03.yaml
...az Arany u. 33- az biztos hibás, mert oldalanként kb. 10 ház van, ami kb. max 20 ig reális, de a 33 az már biztos rossz mert az utolsó előtti ház az 17-es.
=> data: update filters

data/relation-pilisvorosvar.yaml
Lahner György utca - Határ utca, filter instead of map
house numbers have only one street name, no mapping needed
=> data: pilisvorosvar: update reftreets

data/settlements-hungary.txt
It did not find anything missing on OSM, so let's stop here. Once it
would find something, we could have a page like
/osm/housenumber-stats/hungary/missing-settlements to list the missing
settlements.
Change-Id: Iade0b6d27ec81bab87f33e51d6e3209b6fd26fc5
=> data: add overpass query to get all settlements in Hungary

parse_access_log.py, requirements.txt, setup.cfg, stats.py, tests/test_parse_access_log.py
1) Top 5 (most edited) relations are frequent, even without visitors.
2) If a relation got less than 5 new house numbers in the last 30 days,
then the relation is not frequent, even with lots of visitors.
Change-Id: I8b46268f9cb9ca98855e6af8aa794051dbf40ae4
=> parse_access_log.py: take relation edit activity into account

cron.py, requirements.txt, tests/test_cron.py, tests/test_overpass_query.py, tests/test_util.py, tests/test_wsgi.py
Which points out a few type hinting problems, unnoticed previously.
Change-Id: I5167d036a09aaa189b4f7a6a60b294a846031236
=> Update mypy to 0.790

Makefile, additional_streets.py, areas.py, tests/test_areas.py
Just a cmdline tool so far, and not yet possible to silence false alarms.
Also move build_ref_streets() to RelationConfig before Relation grows
too large.
Change-Id: I7a424b90d44dd85ac0c688ff2017975e11b30ee3
=> Add initial reverse street compare

doc/README.adoc, tests/data/relation-gazdagret-refstreets-bad-map.yaml, tests/test_validator.py, validator.py
So it can be used for mapping ref names to osm names as well in the
future. The markup allowed mapping multiple osm names to the same ref
name in the past.
Change-Id: I354ca286a17b5ea833dd4f9984793940be317530
=> refstreets: enforce that this is a 1:1 mapping

tests/test_wsgi.py, webframe.py, wsgi.py
So that manually visiting e.g.
/osm/additional-streets/budapest_12/view-result gives the result.
Change-Id: Ib4cfe5f6bd98c7aee2ced6814a9237e759163e15
=> additional streets: add initial web endpoint

tests/data/relations.yaml, tests/test_areas.py, tests/test_wsgi.py
So that adding a new relation has no effect on existing tests.
Change-Id: I73de2c1fc0a1b57e0c01c1706ebf666a878994c5
=> Allow web-testing a relation without mentioning in tests/data/relations.yaml

Makefile, areas.py
Overpass already filters out empty street name from streets, this does
the same for house numbers.
Change-Id: If85925e9bc7b6167b134029e2be41089f1950b97
=> get_osm_streets: ignore empty street name from house number list

webframe.py
And make stats/docs header-only before the headers grows too large.
Fixes <https://github.com/vmiklos/osm-gimmisn/issues/688>.
Change-Id: I60b11d8638a953ff2853861a09aa39851df93b1b
=> additional-streets: link this from the header

areas.py, wsgi.py
So that the main page can show it fast, once it's calculated at least
once.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/689>.
Change-Id: I3a84b22170bff799a8d24e29cf6fb9e9b363bbe4
=> additional streets: remember the list length after calculating it

Makefile, cache_yamls.py, tests/test_cache_yamls.py
Change-Id: Id43f686a4320f7d977e987e132821e91dc6b4bba
=> cache_yamls: create a json that contains all the osm relation IDs we track

static/osm.js
When this is not the main page.
Change-Id: Ie0cdbbda115e4746bdac9465ce7a143b4c3ab905
=> filter-based-on-position: avoid 'TypeError: gps is null'

wsgi.py
So that the static filters (which do not depend on the position) are
next to each other.
Change-Id: Ie0aba075039ece8683216c0f78f6087f05459bc8
=> toolbar: order filter-by-pos before hide-incomplete

Makefile, static/osm.js, static/stats.js, tests/config.js, tests/test_webframe.py, webframe.py, wsgi.py
Provide a config.js instead, so the rest of the files can be served
as-is. Otherwise file offsets don't match in the filesystem and in the
browser which makes debugging harder than necessary.
Change-Id: Ie4778c8e8053b23412d6d5eaf8423c972cfc4239
=> webrame: refactor to stop preprocessing js files

.eslintrc, HACKING.adoc, INSTALL.adoc, Makefile, osm.js, package.json, stats.js, tests/config.js, tests/test_webframe.py, tests/workdir/bundle.js, webframe.py, wsgi.py
So that the stats page only loads 5 .js files, not 7.
The end goal is to load just a single one, and then the ability to move
to typescript.
Change-Id: Id058516673c0b889038dd3c5b863dcec5f229b54
=> js: merge config.js, osm.js and stats.js into a single bundle.js

tests/test_wsgi.py
Serving static js is a poor idea, since we no longer have js under
static/ on the filesystem.
Change-Id: I95f971a4dc3d66120b2c14cb4e472850fe777b07
=> wsgi: test serving static css

tests/static/sorttable.js, tests/test_webframe.py, webframe.py
All js is bundled and served from workdir, so the serve-from-git code is
no longer needed, reducing complexity.
Change-Id: I6c9d136306a0070e3a0556a6c2bb8ec78e7e1f38
=> webframe: drop support for serving js from git

areas.py, tests/workdir/street-housenumbers-test.csv, util.py
Normally we take osm streets, then also check osm housenumbers, in case
a house number would mention some street name which has no matching way.
Disable this mechanism for house numbers where there is only a street,
but no actual house number.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/754>.
Change-Id: I3c5237075389d698831c068bffff0a070dcaa084
=> get_osm_streets: ignore house-number-less house numbers

Makefile, tests/test_wsgi_json.py, wsgi.py, wsgi_json.py
So that js can call it in the future, without an actual redirect.
Introduce a wsgi_json module for this, before wsgi grows too large.
Change-Id: Icad722dffebc75bb8683b966963fe3ab1651d530
=> wsgi: add a /streets/.../update-result.json endpoint

osm.ts, webframe.py, wsgi.py
... in the missing-housenumber case. The benefit is that this way the
original page is not left, so the user can't end up on a different page
after the overpass query completes.
Change-Id: I96b784b45e073ed48c45ae22af6475043f17509d
=> wsgi: use the /streets/.../update-result.json endpoint

osm.ts, webframe.py, wsgi.py
... in the missing-housenumber case, in case of a new relation.
With this, all 3 redirects for a new relation is replaced by JSON API
calls.
Change-Id: I0703beb386f2be8db869e362323abb4b47defc21
=> wsgi: use the /missing-housenumbers/.../update-result.json endpoint

osm.ts, po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, webframe.py
The JS handler is intentionally registered using JS, so the noscript way
continues to work.
The benefit of the JS way is that it performs the actual update then
reloads, so it doesn't loose the context.
Change-Id: I6c06b770de4d661b8d1621fdb12c522f7fd697e8
=> missing housenumbers: add a JS way to update from OSM

wsgi.py
So there is only 1 reload, not 2 when osm streets are missing.
Change-Id: I53d1c26fdfe19937e551f3f7ac1e4bed98f92a5b
=> missing streets: use the /streets/.../update-result.json endpoint

osm.ts, webframe.py
Missing streets is now almost JS-ready, just the no-ref-streets case
remains.
Change-Id: Ib5ca08adeb163758276840db9ed04851813d3b2f
=> missing streets: add a JS way to update from OSM

osm.ts, webframe.py, wsgi.py
With this, missing-streets never leaves the page when doing the initial
osm/ref request or when updating from osm.
Change-Id: I106a91dddb239a1d16cb2f7e893feeee5ac14b24
=> wsgi: use the /missing-streets/.../update-result.json endpoint

tests/test_util.py, util.py
If a street update is done, we no longer know what was the original
context, better to not redirect automatically. These pages are no not
visited with JS enabled, we use the .json variant in the JS case which
never looses the context.
Change-Id: I6f21014eeeb77a072bf8d205857bd39f9197ea18
=> gen_link: no need to redirect anymore

webframe.py, wsgi.py
The python side can just generate HTML which works without JS, then JS
code can remove the elements which are not needed for JS. This means no
need to mark anything as noscript explicitly.
Change-Id: I9810d1f9ef0b6c1ef0b8833395c94a87898d4363
=> handle_no_osm_streets: eliminate not needed noscript

osm.ts, po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, webframe.py
Both for the housenumbers and the streets references. This was
previously working only for the update-from-overpass cases.
Change-Id: I7b75225e97ea77479c72b64f060c320b3984d3db
=> Add a way to use the json endpoints for the update-from-reference case as well

wsgi.py
The date is the max of the osm and ref last modified timestamp, same as
for missing streets.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/886>.
Change-Id: I998e655f3e840783f8b5eba4a068f5ca66e0969a
=> additional streets: print last modified date in the footer

Makefile
If ./deploy.sh is there, use it; otherwise do the usual pull + make.
Change-Id: Icd2d48d631e680a1aab55a7f3039b0d9af75d7e3
=> make deploy: support a custom deploy command

areas.py, tests/test_wsgi_additional.py, wsgi.py, wsgi_additional.py
Similar to missing housenumbers -> view-turbo, but this work can work
with OSM IDs, so it's more precise.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/861>.
Change-Id: I47346c1b9b2e4a8a30371ba58deb2b7bc8a43a0b
=> additional streets: add view-turbo action

areas.py, wsgi_additional.py
One street can have multiple ids, let's uniq sort the type+id pairs
only.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/861>.
Change-Id: I25fb0510ffad49c318d00136a76ce27911ec9f51
=> additional streets, view turbo: don't uniq sort on street name

tests/test_util.py, util.py
This was only useful when the CSV only had 3 cols.
Change-Id: Ib3c1b64d8cb2181449e1a0c203bb05740df8f4ae
=> Drop unused sort_housenumbers_csv

HACKING.adoc, areas.py, tests/test_areas.py
This is for housenumbers, street were working already.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/964>.
Change-Id: I0cbb6ad1c1467fc5ad9200bc51352b68408cbb73
=> get_osm_housenumbers: consider addr:place when addr:street is empty

Makefile, invalid_refstreets.py
Mostly because this way I can quickly find a relation with errors for
integration testing.
Change-Id: Ia4088e57f948190c1ddf8a32f5e703c81e8d23a4
=> invalid_refstreets: add a script to find errors in all relations

tests/test_wsgi.py, wsgi.py, wsgi_additional.py
We have a list of invalid osm and ref names for the osm <-> ref street
name mapping. This was already visible at the bottom of the missing
housenumbers page. Do the same for the missing/additional streets pages,
as this is useful for relations where only streets are analyzed.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1008>.
Change-Id: I657f7307fff21540f50e6e8be39cd4dd9bbe6435
=> invalid refstreets: add to missing/additional streets as well

main.ts
Because the "osm house numbers" list is merged from true streets and
streets of house numbers, so in case a name is deleted from OSM, it'll
only show up as missing if both are updated.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1033>.
Change-Id: I29a05a55e04c776a51968805714a0e20b4486fc5
=> missing streets: let "update from osm" also update house numbers

util.py
A ref name is invalid based on only the OSM database, for now.
Related to
<https://github.com/vmiklos/osm-gimmisn/issues/1025#issuecomment-784018959>.
Change-Id: I0e747ad38a93b72d5da9011bff5921aae195f9e9
=> invalid refstreets: document what is an invalid osm/ref name

util.py
The bare note makes little sense when the check found no problems.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1067>.
Change-Id: Id413543a6af7d2586f1de791acc27e76b55f3f12
=> invalid refstreets: don't show note when there are no results

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, tests/test_wsgi.py, webframe.py
So that we can search for more errors, like invalid street names in
filters.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/1048>.
Change-Id: I51d4abde33c442db80da4a1ca906849fe4c9391c
=> stats: invalid-refstreets -> invalid-relations

tests/test_wsgi.py, webframe.py, wsgi.py, wsgi_json.py
Works with cherry.py only, not with wsgiref, which doesn't bother
setting the HTTP_ACCEPT_ENCODING key. bundlej.js transfer size goes down
from 263.55 KB to 93.95 KB with this.
Fixes <https://github.com/vmiklos/osm-gimmisn/issues/1116>.
Change-Id: I4baa8735156f95843eed88a1bb0b9ed73921a50f
=> wsgi: optionally gzip-compress the output

webframe.py, wsgi.py, wsgi_json.py
WSGI always gives us an environment and a callback object. Put
everything extra into Response, instead of a mix of Response + remaining
properties.
Change-Id: I7d9aa39f0746d3d4cdfc208e5f745fcf3ed81fbd
=> webframe: fold remaining args of send_response() into Response

Makefile, areas.py, cache.py, tests/test_cache.py, wsgi.py
Old cost for budapest_11: 26.888 seconds
New cost: 0.054 seconds
I.e. once you hit the cached cache, the new cost is 0.2% of the baseline.
Note that the caches is not versioned, the path can be always extended
to contain a version number later if it's needed.
Also note that the cached content is localized, so the language is part
of the cache key.
Fixes <https://github.com/vmiklos/osm-gimmisn/issues/1119>.
Change-Id: Ia3d11833b247879b6452d47b93c43d7576902269
=> Cache missing-housenumbers HTML output

cron.py
So the typical user gets the cached version even the first time the page
is visited.
Change-Id: I6012d9b6e2324da10ae598bc6898f52be9140d64
=> cron: build missing housenumbers html cache

cache.py
It's valid to not have filters, which is common for new relations.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1225>.
Change-Id: Icd03bee75e6362f2054dc060c442cd397dc70f6e
=> missing-housenumbers html cache: handle missing relation yaml

areas.py, cache.py, cron.py, tests/test_cache.py, wsgi.py
Old cost for budapest_11: 28.123 seconds
New cost: 0.053 seconds
I.e. once you hit the cached cache, the new cost is 0.19% of the baseline.
Note that the caches is not versioned, the path can be always extended
to contain a version number later if it's needed.
Also note that the cached content is not localized, so the language is
not part of the cache key.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1206>.
Change-Id: Iad51dafcddedcd5dca13d5b59c3f645e59e3b145
=> Cache missing-housenumbers plain text output

parse_access_log.py, tests/test_parse_access_log.py
Previously a complete relation was just ignored from the frequent
relations set, which typically resulted in active=false.
Now we explicitly expect that in case it's complete then it should be
active=false.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1201>.
Change-Id: I173a38320d1625db8a28404a347c286cecf2c2d0
=> parse_access_log: ignore complete areas harder

tests/test_areas.py, tests/test_cache.py, tests/test_cron.py, tests/test_parse_access_log.py, tests/test_wsgi.py, tests/test_wsgi_additional.py, tests/test_wsgi_json.py
tests/test_config.py already provides a way to see test/workdir as the
workdir.
Change-Id: I79cfd21f5789a1ed5e1282e36ffba5ccf25f42a2
=> test: clean up not needed get_relation() functions

tests/test_wsgi.py, webframe.py
This is typically a new relation, the cron job didn't generate the
street list yet.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1126>.
Change-Id: I4e66f4e181560819d4ae5b5db6ea15fb9f673f25
=> stats, invalid-relations: ignore relation without an osm street list

data/relation-nagykovacsi.yaml
Azok az utcák, amik a referenciából hiányoznak, de a terepen ellenőrizve megvannak.
=> data: nagykovacsi: existing streets

util.py
Record all column headers, not just the type. It'll be useful later and
it's less code.
Change-Id: I44184ed4a3d4bbf5abb555c579eb4184780c6988
=> util: simplify tsv_to_list()

Makefile, area_files.py, areas.py, cache.py, tests/test_cache.py, tests/test_wsgi.py, wsgi.py, wsgi_additional.py
Something like /additional-housenumbers/szigetmonostor/view-result
should now work, though it's not yet linked anywhere.
Still no filters yet.
Change-Id: Idabf20d60e7f3adcf429f3631ab40bbf14918d65
=> additional housenumbers: add initial html output

.coveragerc, util.py
Given that regex, even an empty string matches.
Change-Id: I2c72ea47d4969009fad31c7ea9dae38f07e4b9ce
=> split_house_number: no match can't happen

Makefile, areas.py, cache.py, po/hu/osm-gimmisn.po, po/osm-gimmisn.pot
Track the number of additional house numbers as well, not just the
number of streets that have additional house numbers. This way the
output is closer to the missing housenumbers page.
Change-Id: I33b5107ae2618179a3c2036bdac6b85c01acc9ac
=> additional housenumbers: improve html output

areas.py, doc/README.adoc, tests/data/relation-gazdagret-filter-valid-bad-type.yaml, tests/data/relation-gazdagret-filter-valid-bad.yaml, tests/data/relation-gazdagret-filter-valid-bad2.yaml, tests/data/relation-gazdagret-filter-valid-good.yaml, tests/data/relation-gazdagret-filter-valid-good2.yaml, tests/data/relation-gazdagret.yaml, tests/test_areas.py, tests/test_validator.py, validator.py
The new "valid" list is similar to the "invalid" one, can filter out
delete suggestions which are fine in OSM, after all.
Change-Id: I882f30e6df3e706a00c79ca469d84f98b36c3f3c
=> additional housenumbers: add filter support

data/relation-szigetmonostor.yaml
Which is used to filter the output of /osm/additional-housenumbers/szigetmonostor/view-result
Change-Id: Idf31f6cc7034191af58eb6e19826a8e3ce2416a8
=> data: szigetmonostor: add first 'valid' filter

tests/test_wsgi.py, wsgi.py
These are usually needed only for debugging and they take space.
Also write a test for a case that so far only tested implicitly.
Change-Id: Ia69cf688632a2005f4bdd7d187a0b8b92c89285d
=> wsgi: don't link existing streets / housenumbers on the main page

config.py, tests/test_wsgi.py, tests/test_wsgi_additional.py, tests/test_wsgi_json.py, wsgi.py
The problem with static getters is that the whole process needs
restarting when updating e.g. the reference to a new version. The fix
for this is to migrate to non-static getters, workdir is a start. (And
even not all workdir get calls are converted yet.)
Change-Id: Id43634d7b2ca05530889dd66b6d6583ef9e76f51
=> config: add a non-static way to get the workdir

config.py, tests/test_util.py, tests/test_webframe.py, tests/test_wsgi.py
Its purpose is to mutate shared state, avoid that.
Change-Id: Iabfaf2359b64def7e813fa482c4038e5ff8ec3a9
=> Rework to avoid ConfigContext

tools/dump-deps.sh
Helps seeing what are the leaf modules which are possible to port to C
(or equivalent), if wanted.
Change-Id: I463d1eb741ece7869993f324e1a8f02cd366c847
=> Add a dependency dumper for thw own python modules

areas.py
Fetch the ranges for streets only once, not for every house number.
'./missing_housenumbers.py budapest_11' goes from 28,035s to 3,600s
(12.84%) of the baseline.
In practice this only matters when the result is not yet cached.
Change-Id: Ie86bccbc4a57bd0041dfb441732ac8d729278581
=> missing housenumbers: speed this up

areas.py
Avoid lots of string compare with replacing a "street name<tab>house
number" list with a dict where the street name is the key.
0m3,600s -> 0m0,943s (26.19% of baseline) for './missing_housenumbers.py
budapest_11'.
(Now the perf profile doesn't point out anything silly anymore, so
that's probably as far as we can get with cheap tweaks.)
Change-Id: I3be219ac2263502ab12bad394f057856fc601219
=> missing housenumbers: speed this up even more

config.py, cron.py, tests/test_util.py
Which means config.Config is now unused code.
Change-Id: Ib179a1529afdb06233aedc5d7158df6c529f275f
=> Port to config.Config2.get_cron_update_inactive()

additional_housenumbers.py, additional_streets.py, config.py, cron.py, get_reference_housenumbers.py, get_reference_streets.py, invalid_refstreets.py, missing_housenumbers.py, missing_streets.py, overpass_query.py, parse_access_log.py, tests/test_areas.py, tests/test_cache.py, tests/test_cache_yamls.py, tests/test_config.py, tests/test_cron.py, tests/test_get_reference_housenumbers.py, tests/test_get_reference_streets.py, tests/test_missing_housenumbers.py, tests/test_missing_streets.py, tests/test_overpass_query.py, tests/test_parse_access_log.py, tests/test_wsgi.py, tests/test_wsgi_additional.py, tests/test_wsgi_json.py, wsgi.py
We pass config around anyway, and this saves a lot of code.
Change-Id: I699cdd49c053f0a023693bb6dffcdaa197cf3f19
=> config: rework to avoid make_config()

.coveragerc, cherry.py, tests/test_cherry.py
wsgi wants a function that is stateless, but we only parse the config
once, test this lambda that just calls the real function with the
remembered config.
Change-Id: Icd1b4571ff01717eec00ebeb05b9ae881f92a107
=> cherry: test lamba that injects the config

tests/test_areas.py, tests/test_cache.py, tests/test_cache_yamls.py, tests/test_cherry.py, tests/test_config.py, tests/test_cron.py, tests/test_get_reference_housenumbers.py, tests/test_get_reference_streets.py, tests/test_missing_housenumbers.py, tests/test_missing_streets.py, tests/test_parse_access_log.py, tests/test_stats.py, tests/test_webframe.py, tests/test_wsgi.py, tests/test_wsgi_json.py
We pass around config.Config already, no need to mock it.
Change-Id: I727a5ae32423de009d66ab6e771e38a56575a556
=> Rework to avoid no longer needed test_config.TestCase

config.py, requirements.txt, tests/test_webframe.py, webframe.py, wsgi.py
This was only needed when the server and the client timezone was
different, which is not the case currently, so avoid this complexity.
Change-Id: I56476194562d74b6a023dc8afa09285a0deea529
=> Rework to avoid pytz dependency

.gitignore, Makefile, areas.py, cache_yamls.py, tests/test_cache_yamls.py
Pickle is a python-specific serialization that allows quickly loading
nested dictionaries from disk.
We use yaml for the in-git filter data as it's a better markup for
manual editing: comments, etc.
Given that yaml provides nice manual editing, it's naturally slower to
load than pickle. Switch to json as the cache format: json is still
hard to edit manually (e.g. no comments possible) but it's not
python-specific and almost as fast as pickle.
(Sure, we could use some non-standard json parser that supports
comments, but that'll be probably slower than the stupid+fast built-in
one.)
Change-Id: I8c1dfc33e6cd6fc0991aaf8795b7202b72cb0fbc
=> cache_yamls: switch from pickle to json

areas.py, tests/test_util.py, util.py
With this, all on-disk cached is in json, not a mix of json and pickle.
Change-Id: Ic25dfbc2bda856a44c0827c19b9c7d178d6be8f2
=> reference cache: switch from pickle to json

requirements.txt, stats.py, tests/test_stats.py
A whole module for a function of 5 lines is a bit of an overkill.
Change-Id: I4d994b72d061503bc41707d02fda90284cf8a882
=> stats: eliminate python-dateutil dependency

cache.py, config.py, cron.py, requirements.txt, tests/test_wsgi.py, util.py, webframe.py, wsgi.py, wsgi_additional.py
The problem with locale.setlocale() is that it's not thread-safe. And it
turns out the generic Unicode-aware rules are enough from ICU, no need
to track the specific locale precisely.
Change-Id: I1f00b17b81aaa31a741c6c3be612a9ecae6a745c
=> Use icu instead of locale.setlocale()

accept_language.py, tests/test_accept_language.py
To be in sync with e.g. https://crates.io/crates/accept_language/
Change-Id: I9b95feef81f0481f21534eaa3f67bde894afec29
=> accept_language: remove length check

.coveragerc, cache.py, config.py, tests/test_cache.py, tests/test_config.py
Mostly because this breaks when the caller of the patched function is
implememented in C.
Change-Id: Ia120c6ec592608766aa4a93473831819bd5f2fa6
=> test_cache.TestIsMissingHousenumbersHtmlCached.test_no_cache: avoid mocking

Makefile
The old approach tried to check the changed modules, but this resulted
in hiding some errors in incremental builds. check-mypy takes a few
seconds only, it's better to just check all modules all the time.
Change-Id: Ibccad22d5ff173e51dab75cb72b5ddd2e5c000db
=> mypy: check all modules together

data/relation-budapest_09.yaml
Dalai Láma és társai
https://telex.hu/belfold/2021/06/01/fudan-egyetem-utcanevek-atnevezes-ferencvaros
ugyan nem hivatalos, de a táblák kint vannak
=> data: budapest 09: filter steets

stats.py, tests/test_config.py, tests/test_stats.py
And move make_test_time_old() to test_stats which is the only place that
uses it.
Change-Id: I6baac10b45cc6f692a3b560d6667a0fa4c5ad780
=> test_stats.TestHandleDailyTotal: avoid mocking

tests/test_util.py, util.py
My hope was that en_US.UTF-8 is some generic unicode sorting that is
good enough for both English and Hungarian, but it is not, fix this.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1408>.
Change-Id: Iab95a0ad4a66fda8e3543e774561556f7b41c00d
=> Fix Hungarian sort order

tests/test_wsgi.py, wsgi.py
i.e. "42,43" is turned into 42 and 43, but "" can't be turned into a
number, it should be turned into an empty list.
This happens when filtering for relations based on positions, but we
found none.
Change-Id: Ic65f053c843e173d12dca53ebfbd1154fbe54dc5
=> wsgi: fix missing error handling when the list of relation numbers is empty

tests/network/overpass-stats.csv, tests/test_cron.py
Still 74 calls to unittest.mock.patch() remains.
Change-Id: Ia3826ccb0c560083747eebad7f6ddc5419b3653e
=> test_cron.TestUpdateStats.test_happy: avoid mocking

tests/network/overpass-streets-ujbuda.csv, tests/test_wsgi.py
Still 66 calls to unittest.mock.patch() remains.
Change-Id: I325cb106f7ffe03a52289c669b8826dc33a0272c
=> test_wsgi.TestStreets: avoid mocking

tests/test_wsgi_json.py
Still 63 calls to unittest.mock.patch() remains.
Change-Id: I73a5c7184569b290d768a27ca96a5dab0c913301
=> test_wsgi_json: avoid mocking

Makefile, areas.py, cache.py, po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, util.py, webframe.py, wsgi.py, wsgi_additional.py
Mostly because _ is a reserved identifier in Rust, which blocks
incremental porting.
Change-Id: I7dc5d5415c0b758c5c9becb6c0b69105c3fe21d6
=> i18n: change translate function from _ to tr

tests/test_wsgi.py, webframe.py, wsgi.py
Still 38 calls to unittest.mock.patch() remains.
Change-Id: I81fa1488890deda2ec3a8e4b8e80f9273e1d2a30
=> Avoid remaining mocking of os.path.exists

tests/test_wsgi.py, webframe.py
Still 34 calls to unittest.mock.patch() remains.
Change-Id: I48f13c2b0e79ebfb5f46fefcc716335aed854bad
=> test_wsgi.TestStatsCityProgress.test_well_formed: avoid mocking

tests/test_cron.py
The config already had the test timer configured.
Change-Id: Iff4ef72bce2ca88692007fd4a546dc2ac1088399
=> test_cron: avoid MockDate

areas.py, config.py, tests/test_config.py, tests/test_wsgi_additional.py, webframe.py
The first is a very specific hook, while the later is a generic one that
we can reuse in other cases.
This moves towards in-memory files during tests. At least not writing
the real filesystem during tests will be needed if we'll want to run the
tests in parallel in the future.
Change-Id: If70d4c23ca624cdf37cab1a78c156ecb937fead5
=> config.FileSystem: get_relation_allowlist -> open

area_files.py, tests/test_util.py, util.py
For consistency. If we have to use BinaryIO somewhere, then better to
not use TextIO at all.
Change-Id: I346b61c3aaab5ce16e914915ff02e385bd542ecd
=> csv reader: switch to binary IO

Makefile, cherry.py, tests/test_wsgi.py, wsgi.py
This simplifies the code, so that production and local 'make run' uses
the same codepath.
Change-Id: Id9a1258f2effeb18087f5cec4bb4e029db6adde9
=> make run: change to cherry.py

parse_access_log.py, tests/test_parse_access_log.py
Change-Id: I310ea8fe7b0264fbba47d896f4fd2f53daebb2c7
=> parse_access_log: clean up last redundant arg of check_top_edited_relations()

cron.py, stats.py, tests/test_context.py, tests/test_cron.py, tests/test_stats.py
There was no coverage for these on incremental builds, i.e. we didn't
test both cases: when the <date>.csv exists and when it does not.
Change-Id: I222d4f3231daa51a4fcb519d9a0f1e91b690a1a0
=> Test cron.update_stats_count() and update_stats_topusers()

tests/test_cron.py, tests/test_parse_access_log.py, tests/test_webframe.py, tests/test_wsgi.py
Which was the last test that used mocking. This was probelatic because
mocking breaks when the port is ported to C.
Change-Id: Ide06da8ce7b0ce5089f00fac8f7b3a2a7aa7f0f6
=> test_parse_access_log: avoid mocking

tests/test_wsgi_json.py
If no tests write to (shared) files under tests/, then we'll be able to
run the tests in parallel.
Change-Id: Icfa12fadd6eb00847034fb8615e772e43edaa317
=> test_wsgi_json.TestJsonStreets.test_update_result_json: write to memory

areas.py, util.py
It's not really the way C++ or Rust generics works, but good enough for
our needs to avoid Any.
Change-Id: I1a9a19fd52f17c9e475f7f193c5721ebe1d5d51b
=> Finally figured out mypy generics

webframe.py
So use time.gmtime() instead which takes utc time.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1508>.
Change-Id: I1d66a246ee22618754bb825e5098f353df7615a3
=> webframe: context time is in utc, datetime.date.fromtimestamp takes a local time

.github/workflows/tests.yml
3.6 is enough, 3.8 is not something the primary instance runs nor what I
run locally.
Change-Id: Ibe2145520ca37a29ad30289dbfaa409d426bb131
=> CI: test just one python version

cron.py
So testcases can write them in parallel if they want.
Change-Id: I2ee5e2dca5541f73f6ac84d19496abb9bf81a570
=> cron: port 3 more file opens to go via the context

.pylintrc, tests/test_areas.py
Also consistently override pylint settings: set to double-of-default or
to 0 depending on if it's a min or a max.
Change-Id: I8bc413c0226daa3c8ca9e2a8a487d8bc721d6bc2
=> test_areas.TestRelationWriteMissingStreets.test_empty: write to memory

context.py, overpass_query.py, tests/test_context.py
Only a single place used the default.
Also catch both http and url errors when turning them into strings.
Change-Id: I2a926c4b7204f54d816f3328698003d0537f5b47
=> context.Network: avoid pointless optional parameter

.github/workflows/tests.yml
Change-Id: Ieb39403625a13e910fb61cbf55bf5b6f7d812b84
=> CI: allow porting Python modules to Rust

HACKING.adoc, Makefile, areas.py, cache.py, requirements.txt, tests/test_areas.py, tests/test_cache.py, tests/test_util.py, tests/test_webframe.py, tests/test_wsgi_additional.py, tools/dump-deps.sh, util.py, webframe.py, wsgi.py, wsgi_additional.py, yattag.py
- 68 lines is less than the 2.2k lines of that dependency
- attribute names containing hyphens (e.g. data-value) are no longer a
special case this way
- this is now short enough to be ported to Rust
Change-Id: Ie055b7884d51b99cac2be67b5a720fb14a0c9634
=> Replace the yattag dependency with a subset module

Cargo.toml, Makefile, src/lib.rs, src/yattag.rs
It works, but type hints are missing on the Python side.
Change-Id: I21e5c9af59fe26acb12c5d4ddd7dcf89ba9fd4d3
=> Start porting yattag.py to Rust

Cargo.toml, Makefile, accept_language.py, rust.pyi, src/accept_language.rs, src/lib.rs, src/yattag.rs, tests/test_accept_language.py, tools/dump-deps.sh
There is <https://crates.io/crates/accept-language>, so only the Python
wrapper is needed in own code.
Change-Id: I1a965a243f62a458a359f822575f6d55e1bfee3b
=> Port accept_language.py to Rust

Cargo.toml, Makefile, api.py, context.py, rust.pyi, src/context.rs, src/lib.rs, tests/test_context.py
Which means test_context and rust.pyi needs some shared place to declare
a common interface on the Python side, so introduce an api.py for that.
Change-Id: I96818bb2d1c016bb6325b0994807c281994c725e
=> Port context.Network to Rust

src/context.rs, src/lib.rs
It's done, but the Python bindings are missing.
Change-Id: Ie89174fac3949c89844812026d7a0a0689a4e4d5
=> Start porting context.FileSystem to Rust

context.py, rust.pyi, src/context.rs, src/lib.rs
But don't bother wrapping the open_read() / open_write() part as there
is no easy way to expose an opened Rust file to Python and we don't
really need it, either.
Change-Id: I9696b672a697f82efa97a8de1cbc39f356f29aee
=> Finish porting context.FileSystem to Rust

api.py, overpass_query.py, rust.pyi, tests/test_context.py
As that's what the implementation does. Otherwise we get:
File "/home/osm-gimmisn/git/osm-gimmisn/cron.py", line 341, in our_main
update_stats(ctx, overpass)
File "/home/osm-gimmisn/git/osm-gimmisn/cron.py", line 308, in update_stats
overpass_sleep(ctx)
File "/home/osm-gimmisn/git/osm-gimmisn/cron.py", line 53, in overpass_sleep
sleep = overpass_query.overpass_query_need_sleep(ctx)
File "/home/osm-gimmisn/git/osm-gimmisn/overpass_query.py", line 29, in overpass_query_need_sleep
buf, err = urlopen(ctx.get_ini().get_overpass_uri() + "/api/status", bytes())
TypeError: argument 'data': 'bytes' object cannot be converted to 'PyString'
Change-Id: I0f1098e7ef938f5d774e91ee70ab8fc0fca7aaba
=> Change urlopen() type hints to take string data and return string data

src/context.rs
To match what is in the overpass query templates. Default was 30
seconds, which is less than the old Python timeout.
Change-Id: I43d331c979a8e717414e16f8a404556f02cfa0c5
=> reqwest: increase default timeout

context.py, rust.pyi, src/context.rs, src/lib.rs, tools/dump-deps.sh
Which requries wrappers in both directions around Network, but the
wrapper around StdNetwork is no longer needed.
Change-Id: Idf2a7f56bd3fa0b8b8ffaea1fdc6bc855e2f3b7d
=> Port context.Context.get/set_network() to Rust

context.py, rust.pyi, src/context.rs, src/lib.rs, tests/test_context.py, tests/test_cron.py
And also get rid of casts in tests/test_cron.py, they are hackish and
now that TestTime is accessed through a Rust wrapper they would even
break.
Change-Id: I585c1873a0b183bd097d7ab06f224c5ca438966b
=> Port context.Context.get/set_time() to Rust

areas.py, context.py, cron.py, parse_access_log.py, rust.pyi, src/context.rs, src/yattag.rs, stats.py, util.py, webframe.py
Which requires writing some iterator code, as pyo3 doesn't map from the
Read trait to a BinaryIO, but the Python csv module wants to read the
file line-by-line that way. Change own Python code to do the same, so at
least readlines() doesn't have to be implemented.
Change-Id: I5f63f46a21e8de6debca7fd9ff4a94708ae7e9b4
=> Port context.StdFileSystem.open_read() to Rust

api.py, context.py, rust.pyi, src/context.rs, tests/test_context.py
Which means no wrapper is needed around rust.PyStdFileSystem anymore.
Change-Id: If337e723578ed4dbd96018af6da547d746cc0743
=> Port context.StdFileSystem.open_write() to Rust

Makefile, api.py, cron.py, overpass_query.py, rust.pyi, src/context.rs, src/lib.rs, src/overpass_query.rs, tests/test_context.py, tests/test_overpass_query.py, wsgi.py, wsgi_json.py
Can turn the error case into a Python exception after all, so no need to
return a tuple.
Change-Id: I1ad926b00da1eefec0f71da09eaf56aca4bd8cda
=> overpass_query: port overpass_query() to Rust

Makefile, areas.py, rust.pyi, src/context.rs, src/lib.rs, src/ranges.rs, src/util.rs, src/yattag.rs, tests/test_areas.py, tests/test_util.py, util.py, wsgi.py
Also eliminate the registration of the individual classes from
src/lib.rs, like it was already the case for functions.
Change-Id: I435666a13390c22e13201369d19e14b8948906e5
=> Port util.LetterSuffixStyle to Rust

rust.pyi, src/util.rs, util.py
TIL: if you screw up eq(), then sorted(set(...)) on the Python side
won't work, even if hash() is implemented correctly.
Change-Id: I52152d5a19f6c9dae927c881247f0547be29ba08
=> Port util.HouseNumberRange to Rust

Cargo.toml, api.py, areas.py, rust.pyi, src/util.rs, util.py
Also port get_reference_cache_path(), build_reference_cache() and
build_reference_caches().
Finally fix util::format_even_odd_html: one break is enough, between the
odd and the even line.
Change-Id: Ie1ddf6d6635ad3b0ada7372633e344024d7d08ad
=> util: port build_street_reference_cache() to Rust

cache.py, rust.pyi, src/util.rs, src/yattag.rs, tests/test_util.py, util.py, webframe.py, wsgi.py, wsgi_additional.py
Also invalid_filter_keys_to_html(), get_column() and tsv_to_list().
Change-Id: I954b8a158b6622141a7ad771804e3f82b550f7ee
=> util: port invalid_refstreets_to_html() to Rust

areas.py
main: unhandled exception: Traceback (most recent call last):
File "/home/osm-gimmisn/git/osm-gimmisn/cron.py", line 351, in our_main
update_ref_housenumbers(ctx, relations, update)
File "/home/osm-gimmisn/git/osm-gimmisn/cron.py", line 125, in update_ref_housenumbers
relation.write_ref_housenumbers(references)
File "/home/osm-gimmisn/git/osm-gimmisn/areas.py", line 404, in write_ref_housenumbers
streets = [i.get_osm_name() for i in self.get_osm_streets()]
File "/home/osm-gimmisn/git/osm-gimmisn/areas.py", line 294, in get_osm_streets
street = util.Street(osm_name=row[1], ref_name="", show_ref_street=True, osm_id=int(row[0]))
IndexError: list index out of range
workdir/streets-balatonalmadi-vorosbereny.csv is some XHTML error
message, not a CSV.
Change-Id: …
=> areas: guard against XML data when requesting CSV

NEWS.adoc, cron.py, src/area_files.rs, tests/network/overpass.xml, tests/test_cron.py
Skip it if it looks like XML.
Resolves <https://github.com/vmiklos/osm-gimmisn/issues/1664>.
Change-Id: Iaf5c53081e0a99b5a67ba23917d8eb7722f4971b
=> cron: handle non-CSV response from overpass

Cargo.toml, HACKING.adoc, src/areas.rs
Now that the relevant piece of this is free from Python, callgrind shows
where is the not needed copying.
Old cost for 'time ./missing_housenumbers.py budapest_11':
real    0m12,599s
New cost:
real    0m0,703s
The best Python time was 0m0,943s before we started to pay for the
Python<->Rust copying, so finally this is some real benefit.
Change-Id: I6095714e64860ec2daf58ce73ccc92a5bdb8d365
=> areas: speed up get_missing_housenumbers()

Makefile, tools/ci-build.sh
1m50,236s -> 1m2,729s for the build time and the output is almost
unused, so doesn't matter much.
Change-Id: I78e268044d8fc4b84e20ee4b3f7dc4b460b340df
=> CI: default to unopitimized Rust build

src/util.rs
missing_housenumbers budapest_11: 703ms -> 372ms (53% of baseline)
Change-Id: I137903bad3067cf0fd6756625e2c163cbc9c37d2
=> util: optimize HouseNumber::get_diff_key()

src/util.rs
'time target/release/missing_housenumbers budapest_11' gives:
- old: 654.67 ms
- new: 420.67 ms
i.e. the new cost is 64.26% of the old one.
Change-Id: Ia41fdbaebf0e5eb1decc400891e432fb3469585a
=> util: optimize normalize_letter_suffix()

src/areas.rs
It seems Python accepted a whitespace suffix, but Rust does not.
data/relation-balatonalmadi-budatava.yaml:36:      - {start: '18', end: '198    '}
Just adjust the Rust side for now.
Change-Id: I1f7d666918cd0850648629bdd97f6965c05195b8
=> areas: trim start/end of range before convert to number

tests/data/relation-gazdagret-filter-range-bad-end2.yaml, tests/data/relation-gazdagret-filter-range-bad-start2.yaml, tests/test_validator.py, validator.py
It works with Python's int("42 "), but doing the same is an error with
Rust.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1815>.
Change-Id: Ib76b3356e14cf4431c6c20254770cdd23764e370
=> validator: reject number in string with whitespace

src/validator.rs, tests/test_validator.py
Change-Id: I81d0316053d583b3029cc33e7bdd058c1a721569
=> Port up to tests.test_validator.TestValidatorMainFailureMsg.test_start_whitespace()

Cargo.toml, Makefile, src/bin/cache_yamls.rs, src/bin/cron.rs, src/bin/missing_housenumbers.rs, src/bin/parse_access_log.rs, src/bin/rouille.rs, src/bin/validator.rs
This initially made sense when the majority of it was Python, but not
anymore.
Also drop some --no-default-features from the Makefile, that was only
necessary for pyo3.
Change-Id: I1d7c352a6643c49f8c08a8c4e66a2dfa2cf583fd
=> Rename the 'rust' lib crate to 'osm-gimmisn'

Cargo.toml, INSTALL.adoc, src/util.rs
The primary motivation is to invoke the validator before pushing. Avoid
ICU for now, since the validator doesn't need it, and it's complicated
to build it on Windows.
Sample output:
https://share.vmiklos.hu/osm-gimmisn/validator-v7.2-293-g109ab66c.exe
Change-Id: I1f66bc6d0eb4fa2e99fa04829a80e606b23475c0
=> Add a way to build on Windows

src/area_files.rs, src/areas.rs, src/cache.rs, src/cron.rs, src/parse_access_log.rs, src/webframe.rs, src/wsgi.rs, src/wsgi_additional.rs
Avoid the string -> path -> string roundtrip, which means this can never
fail.
Also do the same for a number of other RelationFiles functions:
- get_osm_streets_path()
- get_osm_housenumbers_path()
- get_ref_housenumbers_path()
- get_housenumbers_percent_path()
- get_housenumbers_htmlcache_path()
- get_housenumbers_txtcache_path()
- get_streets_percent_path()
- get_streets_additional_count_path()
- get_housenumbers_additional_count_path()
- get_additional_housenumbers_htmlcache_path()
Change-Id: I685a2a0600f90de9136693d247d1c0e715d6dd10
=> Simplify RelationFiles::get_ref_streets_path()

Makefile, doc/README.adoc, src/cache.rs, src/context.rs, tests/data/relation-nosuchrelation.yaml
With this, 100% line coverage is reached in context.rs.
Change-Id: Id8c03ddd431e7c92a409cc61b3e153f683cfa7d0
=> context: test what happens when the fallback value of a config key is used

src/areas.rs, src/bin/cron.rs, src/cron.rs, src/overpass_query.rs
Make sure that the function doesn't fail for all relations just because
one relation is broken.
With this, 100% line coverage is reached in cron.rs.
Change-Id: Idff9edf57b693a56e443e63744e8a4b0074f0aad
=> cron: test update of ref housenumbers when osm street list is broken

src/areas.rs, src/cron.rs, src/i18n.rs, src/util.rs, src/wsgi.rs
To actually test the non-cached path. The old cache path was wrong, so
it tested the cached path.
Also add one more test for get_street_from_housenumber().
With this, 100% line coverage is reached in util.rs.
Change-Id: I5a853b650a49d174d58262fefc2747520037a10d
=> util: fix test_build_reference_cache()

src/webframe.rs, src/wsgi.rs, tests/workdir/stats/2020-05-10.citycount
Test the case when a relation is both in osm and ref, which is the
interesting one.
Improve the zipprogress test similarly.
With this, 100% line coverage is reached in webframe.rs.
Change-Id: I4933b0c0ae25c0433ce7d21151b1506197724319
=> webframe: improve test_handle_stats_cityprogress_well_formed()

src/areas.rs, src/bin/cron.rs, src/cache.rs, src/cache_yamls.rs, src/context.rs, src/cron.rs, src/parse_access_log.rs, src/stats.rs, src/util.rs, src/webframe.rs, src/wsgi.rs
I.e. make it never fail, it was just a leftover.
Change-Id: I1ed60a43c7b184a181c14afa255db98f2df8ed2d
=> context: make get_abspath() just return a String

src/yattag.rs
With this, 100% line coverage is reached in yattag.rs.
Change-Id: Ib8d87860dc4d74e8064e2296e0c87eb376460e6e
=> yattag: test escaping

src/wsgi_json.rs
No need to handle errors when we update streets / housenumbers from the
reference as that's done offline and if it still goes wrong, the caller
should handle that error in general.
With this, 100% line coverage is reached in wsgi_json.rs.
Change-Id: I8c8a3ab6116df350139983480adac3ba2b96045e
=> wsgi_json: simplify

Makefile, src/cron.rs, tools/ci-build.sh
This used to be the case for Python code, just got lost during porting.
Change-Id: Ie9923fae22d96c6254f4ca5359a589ccd716b84e
=> CI: require 100% statement coverage for Rust code

.github/workflows/tests.yml, src/webframe.rs, src/wsgi.rs, src/wsgi_json.rs
Fixes the problem that we expected the old Python HTTP_ACCEPT_ENCODING
header, while rouille provides the header as-is.
Also allows simplifying webframe::handle_error() and
wsgi::our_application().
Finally give Swatinem/rust-cache a try, perhaps it can speed up the
build somewhat.
Change-Id: I7fc115a9852facdad8f2159aedd180f79e15f28f
=> webframe: take a rouille::Request in compress_response()

.github/workflows/tests.yml, src/bin/rouille.rs, src/util.rs, src/webframe.rs, src/wsgi.rs
This allows eliminating the untested conversion code in
src/bin/rouille.rs.
Change-Id: I873e291f84c3b802fb613f614acdd90b7ecccee2
=> webframe: change Response to match the header format of rouille

src/webframe.rs, src/wsgi.rs, src/wsgi_json.rs
It's just a header, no need to handle it in some special way.
Also reorder the remaining fields to match rouille::Response.
Change-Id: I47228c145749c6f0272a8b9e619d11f8f13a56df
=> webframe: clean up not needed Response::content_type

src/webframe.rs, src/wsgi.rs, src/wsgi_json.rs
Avoids pointless conversion between rouille::Response and status code /
headers / data.
Change-Id: I4f6052422b0459f3d4a244ebdd416d45b0bda614
=> webframe: turn compress_response() into a trivial wrapper

src/webframe.rs, src/wsgi.rs, src/wsgi_json.rs
Use rouille directly, and only at a single place.
Change-Id: Iae6ec9950331399c8aa8e530c0dafe9b712f761e
=> webframe: clean up not needed compress_response()

src/webframe.rs, src/wsgi.rs
And remove error handling on the caller side.
Change-Id: Ifc66c55e82ebcb26f95850fde66bcf1dbc2eee48
=> webframe: make it explicit that handle_error() never fails

src/bin/rouille.rs, src/wsgi.rs
Which is how it always should have been: application() is just a wrapper
around our_application(), and *that* can fail.
Also, this means that finally we use rouille::Request/Response
everywhere intead of pointless conversions, which were only required
when part of the codebase was still in Python.
Change-Id: I66379eadb896fab00b227c733ca9cc6ad4ffa4e3
=> wsgi: application() now never fails

src/wsgi.rs
Those can never fail, so don't do the unnecessary Ok() wrapping.
Change-Id: I47a0aa1d31bd99a988eac32e8edec5d0d889e0a8
=> wsgi: avoid two not needed Result types

.gitignore, Makefile
Let cargo do that. That is enough, and avoids the problem that 'make
-j8' invokes 'cargo build' multiple times for no reason.
Change-Id: I2b52375ea6da1b0abde49cda98b68d775999565f
=> make: stop maintaining a list of binary crates

.github/workflows/tests.yml, Cargo.toml, HACKING.adoc, src/areas.rs, src/util.rs
Which finally allows performance profiling without touching Cargo.toml.
Also remove a redundant closure and an unused field, both are caught by
the new version.
Change-Id: I0955e0f1e705f4de974bf82726d5ed45a0d198ec
=> Update to Rust 1.57.0

src/cache.rs, src/util.rs, src/webframe.rs, src/wsgi.rs, src/wsgi_additional.rs, src/yattag.rs
This allows eliminating variables which are used, but look unused; and
make the relationship between the tag and its text more explicit.
Change-Id: I5182d8a14ae0486de951b4d124f1db1d5e510fb9
=> yattag: associate text with its tag explicitly

src/cron.rs, src/util.rs
Root cause was fixed with
<https://www.openstreetmap.org/changeset/114536734>, but also improve
error handling on this side.
Change-Id: I5244e74436a5b332b8b4867db0ad8721f7ae7b33
=> cron: don't fail on invalid postcode

src/areas.rs
serde_json::from_value() knows how to check for type errors, no need to
do that manually.
Change-Id: I0a8be364d75e9252eff0b64ddeb413d28e83d04b
=> areas: use typed parsing for refcounty-names.yaml

src/areas.rs
serde_json::from_value() knows how to check for type errors, no need to
do that manually.
Change-Id: I13d96ee40839143d93b83f4f21902d0e81b28290
=> areas: used typed parsing for refsettlement-names.yaml

src/areas.rs
serde knows how to check for type errors, no need to do that manually.
This was simply a 1:1 porting from Python which doesn't have types at
json parsing time.
Change-Id: Iade03836b6e1eb393be6c54aae4391e1ce39d292
=> areas: used typed parsing for yamls.cache

src/webframe.rs, src/wsgi.rs
No need to take it by value.
Change-Id: I01a1b02a3727fe8dafbe90e4ea59903be9157563
=> webframe: take a Relations reference in get_toolbar()

src/browser/stats.ts
This was not an issue so far, because by accident we never had the bars
with the largest value in the center of the chart, but now this is
visible at
<https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/hungary/#_usertotal>
for the 3 bars which are the closest to the horizontal center.
Change-Id: Ia316f91315f8787bc531f29d86935aebd75780e5
=> stats: avoid overlap between the title and the topmost data labels

Cargo.toml, src/areas.rs
The values are still all untyped.
Change-Id: I4987a7029a4f62cf3a8b609e6183dca2bd30a04b
=> areas: use typed json for the toplevel relation-<name>.yaml files

src/areas.rs
It's just a pair of hashtable lookups, it's not building anything.
And no need to copy, the callers can decide what to do with the
reference.
Change-Id: I423d533b08eed7ea3d15f6864ad1349e0fcd7b44
=> areas: build -> get for ref_streets

src/areas.rs, src/validator.rs, tests/data/relation-gazdagret-filter-interpolation-bad.yaml, tests/data/relation-gazdagret-filter-invalid-bad.yaml, tests/data/relation-gazdagret-filter-range-bad-type.yaml, tests/data/relation-gazdagret-filter-refsettlement-bad.yaml, tests/data/relation-gazdagret-filter-valid-bad.yaml, tests/data/relations-missing-refcounty/relations.yaml, tests/data/relations-missing-refsettlement/relations.yaml
Parsing via typed json gives this out of the box, and it's also less
code. Some errors are still unchanged, where the type system can't
express some condition and a manual check is kept.
Dropped tests:
- test_relation_filters_valid_bad: this just enforced that all numbers
in the "valid" array are strings -- but there is no problem to have
them as numbers, really.
- test_relation_filters_refsettlement_bad: same, enforced that numbers
have to be strings
- test_relation_filters_ranges_bad_type: same
- test_relation_filters_invalid_bad: same
- test_relation_filters_interpolation_bad: same
Added tests:
- test_relations_missing_refcounty: previously only the osmrelation key
was checked
- test_relations_missing_refsettlement: same
Change-Id: Ibba415c99dd21e08809727319235657063d3425b
=> validator: report location of the errors where possible

NEWS.adoc, src/bin/validator.rs
The bug was in the last step, which is mocked in tests, annoying.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/1950>.
Change-Id: I8b25da9fbdcae274fc40d0a726ab66294ba2dc51
=> validator: fix exit code

Cargo.toml
See <https://doc.rust-lang.org/edition-guide/rust-2021/index.html> for
details.
Change-Id: I0e3e3da58a6205d6e2f6c49748409e02484d6087
=> Rust: update edition to 2021

src/cache_yamls.rs
This is helpful if cache_yamls aborts the build before the validator
could report the name of the problematic file.
Change-Id: I28c7801b9f6514114002a436e89589ee9c6f8e89
=> cache_yamls: report which file contains the problem

src/areas.rs
No need to fetch the osm street list twice during
'target/symbols/missing_housenumbers budapest_11'.
Old cost: 192ms
New cost: 173ms (90% of baseline)
Change-Id: I500c037c03327dd04a8a1c0738e52833a9e1a800
=> areas: optimize get_missing_housenumbers() a bit

.github/workflows/tests.yml
The default one may be newer than what we can handle.
Change-Id: Ied7a0cf7bc62f9ee6a1b4aefc21fe057633eaa90
=> CI: try to lock down the clippy version

src/areas.rs
The benefit is that there is no common "gazdagret" relation this way,
where changing it influences a lot of tests: rather it's possible to set
the relation config exactly the way that's useful for the test.
=> Make a few tests work without a tests/data/yamls.cache file

src/areas.rs, src/cron.rs, src/wsgi_additional.rs
This helps when declaring the full contents of yaml files in test code.
And the same for refsettlement-names.yaml.
Change-Id: Ia4f71b9172519300b920193008286cf28f860df6
=> Make refcounty-names.yaml optional

src/areas.rs
This way each test can have a custom, minimal relation config.
Change-Id: I5d4ed09cc382c0e739bab4a893bffd8baca33c64
=> Make more tests work without a tests/data/yamls.cache file

src/areas.rs, src/util.rs
This way areas::tests::test_relation_build_ref_housenumbers_missing()
can keep its output in-memory.
Towards eliminating the --test-threads=1 flag when running tests.
Change-Id: I9e2610ad3fd9ca536a6d9c6716915294404d6634
=> util: make build_reference_cache() use context::FileSystem

src/cache_yamls.rs
Replaces as_mapping() and as_u64() with a simple load into the existing
areas::RelationsDict.
Change-Id: I0638c46bda787c147d3b01998bab691d9c68b68b
=> cache_yamls: switch to typed json to avoid manual cast to numbers

src/cache.rs, src/context.rs, src/wsgi.rs
cron::tests::test_update_additional_streets() needs this before it can
be converted to use TestFileSystem.
Change-Id: Ibfda2131c4bd2674f1bc65fc4ac3f67430c720d3
=> TestFileSystem: update mtime on open_write()

src/areas.rs, src/cron.rs, src/parse_access_log.rs, src/util.rs, src/webframe.rs, src/wsgi.rs
It was a no longer necessary wrapper and this makes more tests work
without a tests/data/yamls.cache file.
Still 70 tests to fix.
Change-Id: I92e11aaaec09f5f3e9ed0962d670c997088a12ee
=> Clean up util::get_content()

Cargo.toml
Same for sxd-* and utime.
246 -> 236 dependencies when building the non-test code.
Change-Id: I9bffb859089a0c6653c472a23a865ee8b9e2cf29
=> flate2: dep -> dev-dep

Cargo.toml, src/cron.rs
- anyhow to 1.0.53
- clap to 3.0.13
- itertools to 0.10.3
- rouille to 3.5.0
- rust_icu_ucol to 2.0.0
- rust_icu_ustring to 2.0.0
- serde to 1.0.136
- serde_json to 1.0.78
- serde_yaml to 0.8.23
- simplelog to 0.11.2
Change-Id: I4f54b88140ac3a18849c60b494c84b35ae868120
=> cargo: update dependencies (2022-01)

src/util.rs
I'm not exactly sure why rustc didn't flag this on Linux, only on
Windows.
Change-Id: I39a5a08334146565cf6501af955722288072cb0d
=> Remove unused use declaration

src/wsgi_additional.rs
- fix wsgi_additional::tests::test_streets_no_osm_streets_well_formed
- fix wsgi_additional::tests::test_streets_no_ref_streets_well_formed
- fix wsgi_additional::tests::test_streets_view_result_chkl
- fix wsgi_additional::tests::test_streets_view_result_txt
- fix wsgi_additional::tests::test_streets_view_turbo_well_formed
- fix wsgi_additional::tests::test_streets_well_formed
Change-Id: I51cabb6e7ec39de79132f7daf5803c45df96a92d
=> Make the remaining tests work without a tests/data/yamls.cache file

Makefile, package.json, src/browser/stats.ts, tsconfig.json, webpack.config.js
1) See <https://www.chartjs.org/docs/latest/getting-started/v3-migration.html>
2) This built, but failed to run with:
Uncaught TypeError: auto_1.default is undefined
It seems migrating to webpack fixes this.
3) Webpack conflicted with chartjs-plugin-datalabels, but
<https://github.com/chartjs/chartjs-plugin-datalabels/discussions/304>
solves that.
4) Barcharts now require labels for the values of datasets, which is not
relevant for us, so just set an empty label, otherwise the 'progress'
and 'capital-progress' charts would be broken.
5) Tree-shaking now decreases the bundle size from 265K to 213K (80% of
baseline).
Change-Id: I5c6d03bc13271d7576a4b95916257cdec5a6c1f1
=> stats: update to chartjs v3

src/cache.rs, src/wsgi.rs
- fix cache::tests::test_is_missing_housenumbers_html_cached: don't write relation percent file
- fix wsgi::tests::test_missing_housenumbers_well_formed: don't write relation percent file
With this, 'git diff' is now again empty after 'make check'.
Change-Id: I12c758ef7c7214a273386c6ca12e92d903a8b20e
=> Fix tests that make changes to the test data during 'make check'

src/areas.rs, src/bin/validator.rs, src/cache_yamls.rs, src/context.rs, src/overpass_query.rs, src/validator.rs
Which reads the filesystem directly, so not possible to mock the data in
tests.
And the same in:
- cache_yamls
- overpass_query
- validator
Change-Id: I6d7611bc34e2b371711fee4b0a0282e206951a98
=> areas: avoid std::fs::read_to_string()

src/stats.rs
Which reads the filesystem directly, so not possible to mock the data in
tests.
Change-Id: Ia793486956cd279aae72c411a3962ffcd4890eec
=> stats: avoid std::fs::read_to_string()

Makefile, src/cron.rs, src/parse_access_log.rs, src/parse_access_log/tests.rs
This is possible in case the return value is used with
String::from_utf8() anyway.
std::fs::read() is problematic as it reads the filesystem directly, so
not possible to mock the data in tests.
Change-Id: Ibbcce0889fc5773c4e3e4dd8bf937bd56e52fc54
=> Replace std::fs::read() with read_to_string() where possible

Makefile, src/areas/tests.rs
The not-even-odd case is only implicitly tested by
tests/data/relation-budafok.yaml, i.e. nobody asserted that the
behavior is correct.
Also drop 'cargo test ... --no-run', I forgot that it builds without
coverage, so this meant we build the code 3 times, while the intention
was to let 'make' build the tests without building the code more than 2
times.
Change-Id: I6bb9ef022975244cb83aa4cb9d6e5d9ff5c8c95e
=> areas: add test for Relation::numbered_streets_to_table()

src/wsgi/tests.rs, tests/data/relation-budafok.yaml, tests/data/relations.yaml
It was the last function that was only implicitly tested by the now gone
tests/data/relation-budafok.yaml.
Change-Id: Id8d87a620cbf37faeacfa4f145abb1596bc2e641
=> wsgi: test handle_main_housenr_additional_count()

src/wsgi/tests.rs, tests/data/relation-gellerthegy.yaml, tests/data/relations.yaml
Which was only implicitly tested by the "gellerthegy" relation. So add
explicit tests and remove the relation was that global in the test data.
Change-Id: I08f5f0e17a8267d3e6b4bd76f4e707c11d28c424
=> wsgi: test handle_main_relation()

src/areas.rs, src/areas/tests.rs, src/cron/tests.rs, src/wsgi/tests.rs, tests/data/relation-ujbuda.yaml, tests/data/relations.yaml
It's less code to have explicit tests for these two functions, and then
the whole "ujbuda" relation can go from the test data.
Which means that the remaining tests always get a single relation, so no
need to disable anything.
Change-Id: Ib601f0486617edb6a15dca54f9ce3af54b1cc3f4
=> Add tests for areas::RelationConfig::set_active() and wsgi::handle_main_relation()

src/area_files.rs, src/wsgi.rs
It's less code and is faster as well.
Change-Id: I5925c4eeb2136042e02aaac9b1470dc6d4b44639
=> wsgi: avoid f64 -> string -> f64 in handle_main_street_percent()

src/area_files.rs, src/areas.rs, src/cache.rs, src/context.rs, src/cron.rs
Merges the various copy&pasted get_foo_write_stream() functions into a
single one.
Change-Id: Ie871bd06cac08c182eaec92aa588fa6a7339f298
=> context: introduce write_from_string()

src/areas.rs, src/areas/tests.rs, src/cache.rs, src/webframe.rs
Towards taking a float in util::format_percent().
Change-Id: Ibcf0df672346ccf71da5ae03da6ef44ad4508dce
=> Return a float percent in write_missing_housenumbers()

src/areas.rs, src/areas/tests.rs, src/wsgi.rs
Towards taking a float in util::format_percent().
Change-Id: I28adfe68add44e97eba1ff68cc0b00a641653736
=> Return a float percent in write_missing_streets()

NEWS.adoc, src/cache.rs, src/util.rs, src/webframe.rs, src/wsgi.rs
All callers have a f64, so this avoids a f64 -> string -> f64 -> string
conversion, just keeping the final f64 -> string one.
Change-Id: Idb910d482233178f6aa6b3925884e97cec935053
=> util::format_percent: take a f64

src/area_files.rs, src/wsgi.rs
It's less code this way and the later was the only caller.
Change-Id: I0a310f39f20bfe6cac71315ccb915279018b734f
=> Fold get_streets_additional_count_read_stream() into handle_main_street_additional_count()

src/cron/tests.rs
So gazdagret is there even in case relations.yaml doesn't contain it.
Change-Id: I8d81c200ce2bfd764717f8b7af734297b3645a6d
=> cron: add explicit relations to xml_as_csv tests

src/areas/tests.rs
This was only tested implicitly via tests/data/yamls.cache previously.
Change-Id: I5f450b229b86a2d4ab70732b0c0c45ca8bd00564
=> areas: test get_invalid_filter_keys()

src/area_files.rs, src/cache.rs, src/cache/tests.rs
The interpolation=all case was not tested explicitly.
Change-Id: I34a35d18001952622f7a9c3a1184697360faa64e
=> cache: add more tests for get_missing_housenumbers_txt()

src/util.rs, src/wsgi.rs, src/wsgi/tests.rs
Which was only tested implicitly via tests/data/yamls.cache previously.
Change-Id: I821f9d146d963132334664757cab5a1e38e55df2
=> wsgi: test handle_main_housenr_percent()

src/wsgi/tests.rs
Which was only tested implicitly via tests/data/yamls.cache previously.
Change-Id: If359b707aea929905a7b5c8990adb037db430a59
=> wsgi: test handle_main_street_additional_count()

src/wsgi/tests.rs
Test the result, not just if the output is well-formed.
Change-Id: I3fb8a51f574e14767fa003843d6f5f01b9447b3b
=> wsgi: improve test for filter_for_incomplete()

src/wsgi/tests.rs
Test the result, not just if the output is well-formed.
Change-Id: I941752317fa60f3ce456ecf60aefff5a1b774eba
=> wsgi: improve test_main_filter_for_refcounty()

Makefile
We no longer need this to have full line coverage in tests.
Change-Id: Ia9ad4472357fc7d5de28fb117ec5dfa0ffea5c40
=> Stop creating a test yamls.cache

Makefile
make check was passing locally, but not at CI time.
Change-Id: I106e91a47fb9a1d3db804b3bf3cd25023fa83b3c
=> Re-run clippy when rust version changes

Makefile
We no longer need this to have full line coverage in tests.
Change-Id: I7088b260606322bb7dfe5953373ee23939e79613
=> Stop creating a test osm.min.css

src/stats.rs
This allows mocking, the old way read the filesystem directly.
Change-Id: I0ed00720f54b9dbf4deb4d796ae4ce720239f160
=> stats: std::path::Path::exists() -> path_exists()

src/cron/tests.rs
Change-Id: I18dd625a55327e447a2faf210fdd3ee86f2ac990
=> cron: improve test_update_stats_no_overpass()

src/cron/tests.rs
Change-Id: I4f6eb356f56386aa12e31656051ed489d1f8a7b9
=> cron: improve test_update_ref_housenumbers_xml_as_csv()

src/cron/tests.rs
Change-Id: I4744faf9a4d7be66d15e3490ea3ceae23e76d7df
=> cron: improve test_update_osm_housenumbers()

src/cron.rs, src/cron/tests.rs
That std::path::Path::new() doesn't look right, this way the test passes
or not based on if the integer-rounded modification time manages to be
inside the same second vs not.
One such failing case was https://github.com/vmiklos/osm-gimmisn/actions/runs/1986438662/attempts/1
Change-Id: I8b215a2d603c2947863f95a358ad17b285e134e7
=> cron: use context::FileSystem in update_missing_streets()

src/parse_access_log.rs
motivation.
Change-Id: Ie600b6c31eecc13b07b7e3ae3f7efce57cc9e17b
=> parse_access_log: avoid std::path::Path

src/wsgi.rs
motivation.
This particular usage is not that problematic, but it's very easy to
call problematic functions on the created Path object, so don't risk it.
Change-Id: I59c88118cb4cee830cc238cec6b407c640a6d473
=> wsgi: avoid std::path::Path

src/bin/validator.rs, src/validator.rs, src/validator/tests.rs
Move most of the error handling into validator::main() and turn the
schema errors into a backtrace-like error message.
Change-Id: If2a55a6babf4f32ecffed0a173ade66bd45d5272
=> validator: reduce the amount of untested code in main()

src/util/tests.rs
motivation.
Change-Id: Ic2a8840b114ff20a49901b378cd6c5c14c6a6b9d
=> util: avoid std::path::Path

src/util/tests.rs
Change-Id: Ide43ef836f35bc600591e032c0485676341dbd34
=> util: improve test_build_reference_cache()

src/context/tests.rs, src/cron/tests.rs
Finally allows to fail in open_write() if the path is not mocked.
Change-Id: I02366d54c14f133077f6a339c3e9e00c42c59d64
=> cron: improve our_main()

src/cache/tests.rs
Change-Id: I8d1fd805cda999ea585000381b46759d9a3e1fa0
=> cache: improve test_get_additional_housenumbers_html()

src/cache/tests.rs
Also test get_missing_housenumbers_html() explicitly.
Change-Id: I5f8bad12ba29ab16ae3a93421c9eb5520f5e5bcd
=> cache: improve test_is_missing_housenumbers_html_cached_ref_housenumbers_new()

src/cache.rs, src/cache/tests.rs, src/wsgi/tests.rs
Also add a test for is_cache_current(), which did the opposite of
outdated, so rename it.
Change-Id: I303640381671e8b33c028acbbf5db19cd235c54c
=> wsgi: improve test_missing_housenumbers_view_result_txt()

src/context.rs
This is a leftover from Python where this had to be thread-safe.
Change-Id: Ic1fd88edf30f635ce2386895227b5e13a5b51d0f
=> context: no need to inherit any trait in Unit

src/cache_yamls.rs, src/context/tests.rs, src/cron.rs, src/cron/tests.rs, src/missing_housenumbers.rs, src/parse_access_log.rs
Now all tests go via TestFileSystem::open_write(), so at least such
writes now fail the test.
Change-Id: I62693a68e674ab8bf01608899656dc05b6a6aa20
=> cron: improve test_main_error()

Cargo.toml
It was only needed till tests were wrting the filesystem.
Change-Id: I7beaf553d9b4d50ca39014e1b38a589c3053c6d3
=> Remove no longer needed utime dependency

Makefile
1 thread: 0.70s
8 threads: 0.16s -> 23% of the baseline.
Change-Id: Id8121226967f35d53ffa82d6cc84f3bebbd2d6cd
=> Run tests in parallel

src/bin/cache_yamls.rs, src/cache_yamls.rs, src/cache_yamls/tests.rs, src/context.rs, src/context/tests.rs, src/cron.rs, src/webframe/tests.rs, src/wsgi.rs
This is similar to commit 9887114c9bc5e21eec69754e9adfdf754c3ccf38
(validator: reduce the amount of untested code in main(), 2022-03-19).
Also impove make_error() to return a Result, which needs less code.
Change-Id: I360d4dccf8f11495a13a7c26c525e27b676ddb04
=> cache_yamls: reduce the amount of untested code in main()

data/relation-budapest_12.yaml
This is no longer needed since
<https://www.openstreetmap.org/changeset/119346980> (3 days ago).
Change-Id: I2ade6d76c605f99272543477689a6d62f1568f38
=> data: budapest_12: remove no longer needed Tearózsa utca street mapping

src/bin/rouille.rs, src/webframe.rs
To make it easier to see when we exit to restart vs real failure.
Change-Id: I182e3b46431568af746bdad02e76b66879e2add0
=> webframe: add a stop message matching a start one

src/bin/missing_housenumbers.rs, src/missing_housenumbers.rs, src/missing_housenumbers/tests.rs
This is similar to commit 9887114c9bc5e21eec69754e9adfdf754c3ccf38
(validator: reduce the amount of untested code in main(), 2022-03-19).
Change-Id: Iead65fadb631e5494375d9b756bbbf0d1afa51ab
=> missing_housenumbers: reduce the amount of untested code in main()

src/bin/parse_access_log.rs, src/parse_access_log.rs, src/parse_access_log/tests.rs
This is similar to commit 9887114c9bc5e21eec69754e9adfdf754c3ccf38
(validator: reduce the amount of untested code in main(), 2022-03-19).
Change-Id: I27dbe0de34b8535bb54d2f1125fb889438440c4c
=> parse_access_log: reduce the amount of untested code in main()

src/areas/tests.rs
Previously there was just a single filter, so just picking the last
filter was also accepted.
Change-Id: I4e38b7cfba02d99c0439d33779f098a79644143c
=> areas: test that get_street_refsettlement() picks the correct filter

src/areas/tests.rs
It should ignore such ranges.
Change-Id: Id378e8f69e5eed37336a75cefba04a64bc176050
=> areas: test what happens when get_street_refsettlement() has a range with no refsettlement

src/util.rs, src/util/tests.rs, src/wsgi.rs
This way get_timestamp() gives the correct result in case an in-memory
filesystem has a custom timestamp.
Change-Id: Id111a5e76360c49804fa16642ff6825c2ea7d3f0
=> util: use FileSystem::getmtime() in get_timestamp()

src/validator.rs, src/validator/tests.rs
The name of the key is e.g. "refstreets", not "refstreets.".
Change-Id: Ief7fe96141cc0ec8ae7f560c436d6b75507eff2a
=> validator: improve error message in validate_refstreets()

src/validator.rs, src/validator/tests.rs
<class 'str'> is a leftover from Python.
Change-Id: If4392d661c96a6fe7510e696f6035e0bcd19346e
=> validator: fix this odd value type

data/wsgi.ini.template, src/areas.rs, src/context.rs, src/context/tests.rs, src/parse_access_log.rs, src/webframe.rs, src/wsgi.rs, tests/wsgi.ini
workdir is already hardcoded at many places to be workdir/, don't
require a wsgi.ini entry for this when we don't fully handle it anyway.
Change-Id: Ieaefbeb77e51d7d2669292a7842bbe260d3134ad
=> context: give up on configurable path for workdir

src/areas/tests.rs
Change-Id: I5ecc54abd2b4d886e4796aa83bd3d514d90d248c
=> areas: test what happens when Relation::new() gets invalid json

Makefile, osm-gimmisn.service
This is meant to allow not hardcoding the path to refdir/workdir at
build-time in the future.
Change-Id: Ie3f6103cefe2372b38423b33f77920002215fb4e
=> systemd: set a working directory explicitly

src/areas/tests.rs
Change-Id: Id7b45cda2295e06c86fb7f39d6b946c444c8267d
=> areas: test Relation::get_street_ranges() error handling

src/areas/tests.rs
Change-Id: If105df0871fb6fd85183aaa424cfc2b746b5c305
=> areas: test Relation::get_osm_streets() failure when there is no overpass result for streets

src/bin/cron.rs, src/bin/rouille.rs
Also bump the timeout in the proxy to the double of the current value,
so /missing-housenumbers/.../update-result.json doesn't fail with a HTTP
502 error when the overpass query takes more than 60 seconds when
rouille is behind an SSL proxy.
Change-Id: I20f244702700b3aba825d6c47dd2ca1e835703e5
=> cron: restore lost file-based logging

src/areas/tests.rs
Change-Id: Ie5bd17686c9332761a2fe1946d118355518fe97b
=> areas: test get_alias(), the fallback case

src/areas.rs
Which also avoids an untested line of code in the
RelationConfig::get_property::<std::collections::HashMap>()
instantiation.
Change-Id: Ifc947f2351156e45641f85e031d398e2bcc0ab3c
=> areas: no need to look for refstreets: in relations.yaml

src/areas/tests.rs
Change-Id: I5de9d601b186273b79f834fada7eb1846e911b67
=> areas: test get_osm_housenumbers() with not-well-formed CSV

src/areas/tests.rs
It should return an empty list without an error.
Change-Id: I77e558f2398c43d97b13f15a87bf4a05d48d785c
=> areas: test when happens when normalize_invalids() gets out-of-range input

src/areas.rs
We already do this and it simplifies the code to not look at
relation-<name>.yaml as well.
Change-Id: Id0fe1cffffe777400005d8e634ec8731fe7c67e0
=> areas: require that osmrelation is defined in relations.yaml

src/areas/tests.rs
Change-Id: Ic810a6cd43a0f97a4a80e97a8acdbc74727bc363
=> areas: test Relations::new() with an invalid refsettlement-names.yaml

src/areas/tests.rs
It would not be executed anyway.
Change-Id: Iab5e34b7c6bf07b6b80508df2acb190dbf725fbf
=> areas: don't sort a single element in tests

Makefile, src/context.rs, src/context/system.rs
Mostly because this way I can ignore these in test coverage.
Change-Id: I5d49df30e42e7c25d7bdc8c34418c8c1d57be06c
=> context: extract the std trait implementations into a separate module

src/context/tests.rs
Change-Id: I2fef03304a8e292554e018540921398eb8cc5098
=> context: test FileSystem::list_dir()

src/cron.rs, tests/network/overpass-stats.csv
To be able to refer to columns by name, so this doesn't break if
data/street-housenumbers-hungary.txt reorders columns.
Change-Id: I02727203a83db37b4ec14e91f425cad4ff12c276
=> cron: use a proper CSV parser in update_stats_count()

src/cron.rs
To be able to refer to columns by name, so this doesn't break if
data/street-housenumbers-hungary.txt reorders columns.
Additionally we used to count "@user" as a user in the first line, don't
do that.
Change-Id: I9c1108b0b8f978c23f9abe18786bdf24569ec3aa
=> cron: use a proper CSV parser in update_stats_topusers()

src/stats.rs
This will be useful if one day .citycount files would have tab
characters in key or values.
Change-Id: I4798f2823996d3f5715546c66794751a994097a4
=> stats: use a proper CSV parser in get_topcities()

Cargo.toml, HACKING.adoc, src/bin/cron.rs
Which switched from chrono.rs to time.rs, so the way to specify a custom
time format has changed, adapt the cron command to that.
Change-Id: If41e2aa1787c4ecc95f8cc095e9e087e9be27ef6
=> Update simplelog.rs to 0.12

src/cron/tests.rs
Sorting callback was not tested previously.
Change-Id: I7e4cf5f85742d4018ef6514930d198603f001237
=> cron: test write_city_count_path()

src/cron/tests.rs
Sorting callback was not tested previously.
Change-Id: I354a568eb12f3c585114ab52519e34d627361f32
=> cron: test write_zip_count_path()

src/areas.rs, src/areas/tests.rs, src/cron.rs
Leftover from Python porting, and this way llvm-cov says cron.rs line
coverage is complete.
Change-Id: I91abe2ee59f85be5783203008c289d1f6939ff5e
=> areas: String -> &str in limit_to_refcounty()

Makefile, src/stats/tests.rs
The test data only had capital lines previously.
Change-Id: I2ae77b6d541e76b6b21fb1b01bd125f3821c05f7
=> stats: test handle_capital_progress() filtering out non-capital rows

src/stats.rs
To be able to mock this from tests.
Change-Id: I2f3496899f2397ceb9124719838ea06a92426d89
=> stats: avoid std::fs::File::open()

src/stats/tests.rs
The code skips broken rows, but there was no test for this.
Change-Id: I82d749b96661eb4e959826c796c8b66cf7ab3d4f
=> stats: test broken input for handle_topusers()

src/context.rs, src/i18n.rs
One more leftover from the Python porting, this was useful in the free
pythonanywhere hosting only.
Change-Id: Ib68916b32587269716ac9bafdbdcc88b46a642f2
=> Don't hardcode the build-time current dir anymore

src/stats.rs, src/stats/tests.rs
Because get_city_key() will return "_Empty" for "", and the second
column is a count, which can't be empty, just "0" worst case.
Change-Id: Ia986d6c8fa344566c39a827b4a8feafd73766c2d
=> stats: assume that .topcities CSV files always have 2 cols

data/relation-budapest_14.yaml, data/relation-herminamezo.yaml, data/relation-istvanmezo.yaml
- Egy II. világháború előtt átnevezett, már csak táblán látható utcanév
- Ajtósi Dürer sor 2 az már Herminamező.
=> data: budapest_14 renamed street, fix subarea boundary

src/util.rs, src/util/tests.rs
This regex always matches, add a test to make sure an empty string input
is handled correctly.
Change-Id: Icc3c8f9490d3a3bf4a5eec6087e306a8529a2171
=> util: remove not needed error handling in split_house_number()

src/util/tests.rs
Only broken cache and good cache was tested, not the "no cache" case.
Change-Id: I396a8681d5f718da35be81ebe03bf9d1621ae59f
=> util: test missing cache in build_street_reference_cache()

src/areas.rs, src/cron.rs, src/cron/tests.rs
If a relation sets housenumber-letters to true, then we normalize the
1/A style housenumers in the .txt output. The web interface already
normalized to 1a, but cron normalized to 1/A.
Fix this inconsistency.
Change-Id: I01ed121fe33c972c952b724ffc56885913f774d4
=> cron: sync letter suffix style for txt output with the web

src/util/tests.rs
Only broken cache and good cache was tested, not the "no cache" case.
Change-Id: I80c1bc381969c235fc73568058858db648c1acb7
=> util: test missing cache in build_reference_cache()

src/util.rs, src/util/tests.rs
And add a test to ensure the expected behavior.
Change-Id: I97496741890aa54a03239ba6344547b0a545c307
=> util: remove not needed error handling in split_house_number_by_separator()

src/wsgi/tests.rs
It wanted to test when the osm streets are missing for a relation, but
the test had no relations at all, so this passed even if the tested code
was broken.
Change-Id: I2d39db318f1dae261b7618e377fb80cfa1c0f9d7
=> wsgi: improve test_handle_invalid_refstreets_no_osm_sreets()

INSTALL.adoc
Forgot to update this in commit 4e2f2f19ea4a2a34cf3268973e25d1337ba1aab4
(Don't hardcode the build-time current dir anymore, 2022-05-19).
Change-Id: I7c3baccd6e48fcbe69cf22ace7e01c163faf8450
=> Fix install doc wrt crontab entry

src/wsgi.rs, src/wsgi/tests.rs
There are 3 cases here:
- we don't filter for this county
- we filter for this county and we have settlements
- we filter for this county but we don't have settlements
Make sure we generate the expected output in all cases.
Change-Id: I9183f4cd6cd091ab7d1686c076f9feba67d97baf
=> wsgi: add some handle_main_filters_refcounty() tests

Makefile, src/wsgi_additional/tests.rs
And run tests on only one thread when measuring coverage, that seems to
avoid unexpected uncovered lines (happened at least once out of 10
cases).
Change-Id: I7188036f2ab7ff159da2b3757d3827230fd67d93
=> wsgi_additional: test sorting in additional_streets_view_txt()

src/context/tests.rs, src/cron/tests.rs, src/parse_access_log/tests.rs, src/stats/tests.rs, src/wsgi/tests.rs
It's much less code this way and the intention was already to set it
everywhere where matters.
Change-Id: Ib3f44dabbca56f1384db3493179ff213ad1a4640
=> make_test_context: default to mocked time.now()

Makefile, src/context/system.rs, tools/ci-build.sh
Main benefit is that llvm-based coverage is much more mature, and
already found many untested code where tarpaulin claimed completely line
coverage already.
Also make the webpack build output more silent by default.
Change-Id: I0d9f701bfc8985ab4209653a406803c1748eef3b
=> Code coverage: switch to 'cargo llvm-cov'

src/context/tests.rs
This way it can't happen that we forget to mock the network in a test
and they start to talk to real overpass servers by accident.
Change-Id: I9044a98b1b200ae9bdc644c434d0c4f44d5a0295
=> make_test_context: default to mocked network

src/context/tests.rs
This way it can't happen that we forget to mock the subprocess in a test
and they start to talk to real subprocesses by accident.
Change-Id: I086b5ceb81a1b9b90ef4f0516fd580d5952a19bb
=> make_test_context: default to mocked subprocess

src/areas.rs, src/areas/tests.rs, src/cache.rs, src/cron.rs, src/util.rs, src/util/tests.rs, src/wsgi.rs
This is less code and allows not emptying the osm_housenumbers cache in
Relation::set_config(), leading to a faster cron.
Change-Id: Idf50fcd90af08c622101e5a8561f8d9989211b5b
=> areas: only convert to lowercase letter style at the end of txt/chkl output

src/stats.rs
Then a manual fixup is possible: typically today's missing data can be
approximated with yesterday's outdated data.
Change-Id: I8659f2e923b0cdc020493333e5a3c2bb23a286e3
=> stats: say which .citycount is missing if returning early

src/main.rs
Iterating over the keys of a HashMap is not efficient.
Change-Id: Ie90f9854fac36db7de21d7857310a504ba376f3f
=> main: use HashMap::get()

.github/workflows/tests.yml, src/areas.rs, src/yattag.rs
Use `write!` to avoid introducing an extra, avoidable heap allocation.
Change-Id: If6d3b86798c09b194f8ff784cca53288f844c211
=> Update to Rust 1.62

Makefile, src/context/tests.rs, src/webframe.rs, src/webframe/tests.rs, src/wsgi.rs, src/wsgi/tests.rs
This way:
- refdir/ and workdir/ only contains data
- target/ contains built code / generated data
Change-Id: Ia54b6edc5f053d7eb0e245d9770a67a658f3beba
=> Rename workdir/osm.min.css to target/browser/osm.min.css

src/validator/tests.rs
Change-Id: Id57d438b0d05ce5d28f0ecb1c3434796d58977b4
=> validator: rename assert_failure_msg2() back to assert_failure_msg()

INSTALL.adoc
The validator is not a standalone binary anymore, but otherwise this
still works as of v7.4.
Change-Id: I153e17f7f608e4e90e1f7dcdc4bc57205efd61f3
=> Update Windows build instructions

src/validator/tests.rs, tests/data/relation-gazdagret-filter-invalid-good2.yaml
If this goes wrong, serde will catch this for us without explicit code.
Change-Id: I924a4cea31876180f1dfbfb5bf308feb7297998f
=> validator: remove redundant relation-gazdagret-filter-invalid-good2 testcase

.github/workflows/tests.yml, src/util.rs
Also fix this new clippy warning:
> unnecessary use of `to_string`
Change-Id: If48898b25e113becc39b58698efc40caf03966d4
=> Update to rust 1.63

Cargo.toml, src/yattag.rs
Found by locally making yattag a public module. Also fix the version
number in Cargo.toml.
Change-Id: I814a540a97054577e2331cf8e8659b4454440d33
=> yattag: document Doc::new() and HtmlTable

src/cache_yamls.rs, src/cache_yamls/tests.rs, src/validator/tests.rs, tests/data/relations.yaml
Allows folding tests/data/relations.yaml into code.
Change-Id: I28dcad6d40756f208dfdd678c81848444779a497
=> cache_yaml: don't read relations.yaml directly from the file-system

src/validator/tests.rs
serde already does type checking for us.
Change-Id: I936cfd4a629c1048f44d110d73bf2714dc001dfd
=> validator: remove redundant test_relation_bad_key_name

data/relation-balatonboglar.yaml, src/validator.rs, src/validator/tests.rs
We indent with 2 spaces and even serde rejects tabs in some cases. In
other cases it accepts them, but not Python's yaml parser. Just avoid
tabs, like we already enforce that for Rust code.
Change-Id: I2eb113972c8a4d6a9b322409c5fc705ac1412ac3
=> validator: catch tabs in yaml files

INSTALL.adoc, src/context.rs, src/context/tests.rs
Useful for the validator that doesn't need a config, really.
Change-Id: Id2c5fc98673b1f1c45d80e8ff411c91aa2a92ef8
=> context: don't fail if wsgi.ini is missing

tests/data/refcounty-names.yaml
No test reads this from the filesystem, they provide it from code.
Change-Id: I42dc19c67955e130b03df0147517c05eeef7c576
=> tests: remove no longer needed refcounty-names.yaml

src/areas.rs, src/areas/tests.rs, src/cache.rs, src/missing_housenumbers.rs, src/util.rs, src/util/tests.rs, src/wsgi.rs
Because .street and .house_numbers is more readable than .0 and .1.
Change-Id: I5ea8737bbc064b70c97730d4cb3a217fc4fed86a
=> util: turn NumberedStreet into a struct

tools/sync-ref.sh
wget needs a special option for me locally, but not on the server. curl
seems to work everywhere.
Change-Id: I393c30e3a0ec43fc2b3f898a6c8a9816161e87ec
=> sync-ref: switch from wget to curl

src/validator/tests.rs
Serde checks this for us.
Change-Id: I183d6c1852f595169cf00c008c4966773ecbc092
=> validator: remove redundant test_relation_filters_valid_bad_type()

src/validator/tests.rs
Serde checks this for us.
Change-Id: I51c93fbdfa9180bbf0de2a9d2c742bdf4e802d7f
=> validator: remove redundant test_relation_filters_bad_subkey()

src/areas.rs, src/areas/tests.rs, src/cache.rs, src/missing_housenumbers.rs, src/wsgi.rs
Mostly because if this can be persisted on disk (e.g. as json), then
that would allow getting rid of the separate text and html caches.
Change-Id: I2055d86725157e22c8b955a449f732ba16a85b56
=> areas: give Relation::get_missing_housenumbers return value a named type

NEWS.adoc, doc/README.adoc, src/area_files.rs, src/areas.rs, src/cache.rs, src/cache/tests.rs, src/util.rs, src/wsgi_json.rs, src/wsgi_json/tests.rs
This is exposing the raw diff result, this is the input of the txt and
html outputs.
Also add caching for this, which can be a replacement for the current
txt and language-specific html caches.
Change-Id: Ie79b9d613e8c91166a2fea06775ed386db350748
=> wsgi: add a /missing-housenumbers/.../view-result.json endpoint

src/areas.rs, src/areas/tests.rs, src/cache/tests.rs, src/cron/tests.rs, src/wsgi/tests.rs
Which means that the HTML cache can be removed in the future, since
write_missing_housenumbers() is no longer expensive. Includes:
- fix wsgi::tests::test_missing_housenumbers_well_formed
- fix wsgi::tests::test_missing_housenumbers_compat_relation
- fix wsgi::tests::test_missing_housenumbers_compat
- fix cron::tests::test_update_missing_housenumbers
- fix cache::tests::test_is_missing_housenumbers_html_cached
- fix areas::tests::test_relation_write_missing_housenumbers_sorting
- fix areas::tests::test_relation_write_missing_housenumbers_interpolation_all
- fix areas::tests::test_relation_write_missing_housenumbers_empty
- fix areas::tests::test_relation_write_missing_housenumbers
Change-Id: I35fed5a98e3632bfb7817d5b388d6b6e50ec7d85
=> write_missing_housenumbers: use the new json cache

src/cache.rs, src/cache/tests.rs, src/wsgi/tests.rs
Which means that the txt cache can be removed in the future, since
generating the text output is no longer expensive. Includes:
- fix wsgi::tests::test_missing_housenumbers_view_result_txt_even_odd
- fix cache::tests::test_is_missing_housenumbers_txt_cached
- fix wsgi::tests::test_missing_housenumbers_view_result_txt
Change-Id: I0afcb8127823b24473aed2269e7376abc45380d8
=> cache::get_missing_housenumbers_txt: use the new json cache

src/areas.rs, src/cache/tests.rs, src/wsgi_additional/tests.rs, src/wsgi_json/tests.rs
Which means that the HTML cache can be removed in the future, since
write_additional_housenumbers() is no longer expensive. Includes:
- fix cache::tests::test_get_additional_housenumbers_html
- fix wsgi_additional::tests::test_additional_housenumbers_well_formed
Change-Id: Ia1b57f34719f5eb053f64f5450979a0c8e26bb4f
=> write_additional_housenumbers: use the new json cache

src/area_files.rs, src/cache.rs, src/cache/tests.rs, src/i18n.rs, src/i18n/tests.rs, src/wsgi_additional.rs
Because it used write_additional_housenumbers() internally, which
already uses the JSON cache. This way the locale-dependent HTML cache
can be removed.
Change-Id: Ia047b053e770e3d603bcf5f142bd2012dc948c13
=> cache: remove no longer needed get_additional_housenumbers_html()

src/area_files.rs, src/wsgi_additional.rs, src/wsgi_additional/tests.rs
Which was the last trace of the locale-dependent cache.
Change-Id: Iff833b3ff771e32131f7655a00b3b8b4a9ee3df9
=> area_files: remove no longer needed get_additional_housenumbers_htmlcache_path()

src/util.rs
Go via ctx.get_file_system() to help testing.
Change-Id: I2e4a8dbcc9b2a3887c8d4f85619032cd73fc7509
=> util: avoid File::open() in build_street_reference_cache()

INSTALL.adoc, Makefile, data/wsgi.ini.template, src/context.rs, src/main.rs, src/webframe.rs, src/webframe/tests.rs, src/wsgi.rs, src/wsgi/tests.rs, src/wsgi_additional.rs, src/wsgi_json.rs
Moving the default to code + documenting it is still simpler than all
these error handlings.
Change-Id: Ifff2ae5ca34a506a49d800c0ecac01459a9a7d0a
=> config: make the uri_prefix key optional

NEWS.adoc, src/areas.rs, src/areas/tests.rs, src/cron.rs
This is still cheap, since the 2nd iteration won't consider them new, so
it's a one-off cost.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/2592>.
Change-Id: I59e48de82e0e91eabec6ca8143e5f9a80c1ff970
=> cron: create state for new relations even if they are inactive

src/main.rs
So I don't have to search for it manually.
Change-Id: Ic39fc58785c9d58daf93e435e77a4b9b319fd886
=> sync-ref subcommand: write what is the max version of the various references

src/main.rs
It's less code and it does the same.
Change-Id: Iaa9d5ff228394852356870c21b17535226b8b374
=> sync-ref: use context::Network::urlopen()

src/areas.rs, src/cache.rs
A Relation already has a Context.
Change-Id: I0ee341aa0a906767382095c2c2b8374338946c54
=> is_missing_housenumbers_json_cached: no need to take both a ctx and a relation

src/areas.rs, src/cache.rs, src/cache/tests.rs, src/wsgi.rs, src/wsgi_json.rs
It's less code to use Relation.get_ctx().
Change-Id: Ifa22051c5dc66da71cfa3d0cbf4662b0526737ad
=> write_missing_housenumbers: avoid cloning the context

src/cache.rs
A Relation already has a Context.
Change-Id: I84d20ac55c67835093b6c34dcd8813c169873830
=> is_additional_housenumbers_json_cached: no need to take both a ctx and a relation

src/areas.rs, src/cache.rs, src/cache/tests.rs, src/wsgi_json.rs
It's less code to use Relation.get_ctx().
Change-Id: Ib08144f2b4308e76a1cc3f1448ae85b027fced52
=> write_additional_housenumbers: avoid cloning the context

Cargo.toml, src/cron.rs
These are meant to be off by default, i.e. update and overpass are true
by default.
Regression from commit 651b191f732f3030fc2fc05b144676cbbee1331f (Clean
up tcp_port from wsgi.ini.template, 2022-10-24).
Change-Id: Ice94d133febf409d9cd467329816061f53c67c05
=> cron: fix default of the --no-update and --no-overpass switches

Makefile, src/main.rs
sync-ref already goes with a dash, no need to go with the ugly
underline.
Change-Id: Ic3f780d419f11c7065925056f747ab534975c057
=> main: rename cache_yamls subcmd to cache-yamls

src/main.rs
Now the subcmd matches its URL.
Change-Id: Ic83577da277f093280b7e382e3b7b9d2c79292b5
=> main: rename missing_housenumbers to missing-housenumbers

src/main.rs
Which has the last foo_bar named subcmd, everything else was already
foo-bar.
Change-Id: If4d935a4c1412ad7b8776a61f0fde684f3866fef
=> main: rename parse_access_log to parse-access-log

src/sync_ref.rs, src/sync_ref/tests.rs
Towards adding a --mode switch: so one can choose between updating the
config (current behavior) and downloading the references (new mode).
Change-Id: I521a9252ba61867d22040c4c17323e14719a2c16
=> sync-ref: switch arg parsing to clap

tools/ci-build.sh
We use icu for this today.
Change-Id: Idb61c5acecb6c403768c9d361250335e069a84ee
=> CI: remove no longer needed locale-gen

src/webframe.rs
Even though this should not happen, since handle_static() is only called
with static/foo as argument.
Change-Id: Ie10381d47fac0936f4083aa3dc3b9b83ad8f8dc9
=> webframe: static handling: fail nicer when there is no / in path

src/yattag.rs
push_str() and format() does the same, but those know that string append
won't fail in practice.
Change-Id: Ib078d14c0fe3b1199fd4be603f1806b1a8f9346a
=> yattag: rework to avoid unwrap()

src/cron.rs, src/util.rs, src/util/tests.rs, src/webframe.rs, src/wsgi.rs, src/wsgi_additional.rs
The root of the problem is that we compare unicode strings with icu,
where API calls can fail, but rust wants a comparator that never fails.
This was solved by adding unwrap() around all uses of get_sort_key(),
but this is ugly.
Instead, it turns out that ucol::UCollator::try_from() ~never fails in
practice (even if you pass garbage to it) and we know that the input
string is valid utf8 (comes from Rust), so ustring::UChar::try_from()
won't fail in our case, either.
This means we can just use expect() around those two calls and then
get_sort_key() never fails, matching the expectations from Rust.
Change-Id: I157de8619e4c2686ac9023dc0f08ad81818314e7
=> get_sort_key: simplify error handling

src/wsgi.rs
Let's not abort just because we can't find a timetamp.
Change-Id: I2b847722e5c3b69c8f2247e6f5a3251ad4b6ed33
=> wsgi: improve error handling in get_last_modified()

Cargo.lock, Cargo.toml, package.json
Includes chartjs4, which didn't require any code changes on our side,
surprisingly.
Change-Id: Id90f41f473004d67055728c1aedf19e2e7ab909e
=> Update dependencies (2022-12)

src/parse_access_log.rs
Towards settling down on just time.
Change-Id: Ia019e441fe444479b7e3e9c71e49fd262aac2155
=> parse_access_log: switch from chrono to time

Cargo.toml, src/context/system.rs, src/lib.rs, src/main.rs, src/util.rs, src/webframe.rs
We want to display time in the local timezone, but localtime_r() is not
safe to be called on a thread.
So get the local tz offset using a lazy static and call it before
rouille starts, which is the only case where we're multithreaded.
This also allows returning a UTC timestamp in context::system and the
callers can apply to_offset(util::get_tz_offset()) on the parsed result
if they want to display the date in local time.
Change-Id: I199dc5d9b11e4ec928c88dfbd47b023c829b1978
=> Introduce util::get_tz_offset()

Cargo.lock, Cargo.toml, src/stats.rs, src/stats/tests.rs
Which means that finally chrono can be removed, which fixes
CVE-2020-26235.
Change-Id: I10a1c266041124788862f54692f8e06af8a9928c
=> stats: switch from chrono to time

src/context.rs, src/context/system.rs, src/context/tests.rs, src/cron.rs, src/cron/tests.rs, src/parse_access_log.rs, src/stats.rs, src/stats/tests.rs, src/webframe.rs
Otherwise we need to assume a timezone at the caller side, and we can't
get the current timezone when running the tests on multiple threads.
Change-Id: Icd559f88de48e634007b7f39c94be0e25f6c9ea8
=> context: let Time::now() return a timezone as well

src/stats.rs, src/stats/tests.rs
Going via unix_timestamp() + from_unix_timestamp() is unnecessary at
best.
Change-Id: I3915e9167d41796d48786fd8e12f8916b7bd59bd
=> stats: get_previous_month: return a time::OffsetDateTime

src/util.rs, src/util/tests.rs, src/webframe.rs, src/wsgi.rs
Towards just working with time::OffsetDateTime everywhere, without
serialize + load to a timestamp that has no timezone info.
Change-Id: I66f3d3c65676a9f3ce76433199123c67ae36b277
=> webframe: format_timestamp: avoid from_unix_timestamp()

src/context.rs, src/context/system.rs, src/context/tests.rs, src/cron.rs, src/cron/tests.rs, src/main.rs, src/util.rs, src/webframe.rs
Towards just working with time::OffsetDateTime everywhere, without
serialize + load to a timestamp that has no timezone info.
This also means that get_tz_offset() can be moved to context/system.rs,
so a threaded 'cargo test' passes again (getting the current timezone
from the system on a thread would fail to be safe).
Change-Id: Ide4c36fad19d1bd48641ffcb042fc83d4bd1d139
=> context::FileSystem: let getmtime() return a time::OffsetDateTime

src/areas/tests.rs, src/cache/tests.rs, src/context/tests.rs, src/cron/tests.rs, src/webframe/tests.rs, src/wsgi/tests.rs, src/wsgi_additional/tests.rs, src/wsgi_json/tests.rs
Which eliminates almost all places where we used to work with unix
timestamps (without timezone info).
Change-Id: I7e6cb60762b4c3a65dea4e9250deef45a94f62cf
=> test: FileSystem: change mtimes from f64 to time::OffsetDateTime

src/cache/tests.rs
"now" is good enough, less code, and then these tests will pass even if
now() > 9999999999.
Change-Id: I350ce9710cdd483baad22b77f37bf83e4b518222
=> cache tests: new cache is enough to be current

Cargo.toml
E.g. cargo-license reads this.
Change-Id: Iedaf2a8922a1f254b8bfe341b83d4813f6100bb7
=> cargo: declare license in the package metadata

data/wsgi.ini.template, src/context.rs, src/sync_ref.rs, src/sync_ref/tests.rs, src/util.rs, tests/wsgi.ini
Otherwise it'll be hard to parse this from toml, which would allow
type-safe access to config key values.
Change-Id: I8163af8a6a347ac5f25e49aaa178c24b198baca6
=> config: wrap the value of config keys in single quotes

NEWS.md, README.adoc
Towards merging the documentation and the website into a single,
markdown-based guide.
Change-Id: I28cbaaf828a81dba84371390ecbb9c792b1bedbc
=> NEWS: asciidoc -> markdown

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/webframe.rs, src/wsgi.rs, src/wsgi_additional.rs
Now that the guide is in markdown + the translation is in the wiki, we
can always link to the guide in general, or to the sections that add a
new area or filter noise, take advantage of this.
Change-Id: I191d44ac63c25a1d99eea8b4864507148340b235
=> Link to the relevant part of the documentation

Makefile, about.hbs, about.toml, guide/src/README.md
See
<https://github.com/EmbarkStudios/cargo-about#generate-license-information-for-your-own-project>,
this can generate a license bundle, to credit all used dependencies
correctly.
Change-Id: I91df39edda795f8467c1b5879ae851dd6687d42e
=> license: add cargo-about integration

src/webframe.rs
So if the oder of columns change, we keep working.
Change-Id: I66dc022b5be3c948075700a2ab09a37105d6dfe2
=> webframe: handle_stats_cityprogress: avoid hardcoded column indexes

src/areas.rs, src/areas/tests.rs
Change-Id: Iccb6c6670e9d4ca7120943455a2d77d6d0c467b4
=> areas: switch to typed CSV parsing for OSM housenumbers

src/webframe.rs
Which is rare, since data/ is updated frequently, so we typically a
random commit is deployed, not an exact tag; but it can still happen.
Old output for a match was:
v7.5-rc1
New output:
v7.5-rc1-0-g6ddad82e
util::git_link() works better with the later.
Change-Id: I92a50d955296b449886c6bb2e9ec01d34e19c0ff
=> webframe: fix git commit link in the footer when the commit matches a tag

src/yattag.rs
Change-Id: I5855ed9aa561dc44eeacc609a099e6d1604aa50e
=> yattag: use variables directly in the format string

src/areas.rs, src/areas/tests.rs, src/cache/tests.rs, src/cache_yamls.rs, src/cache_yamls/tests.rs, src/context.rs, src/context/system.rs, src/context/tests.rs, src/cron.rs, src/cron/tests.rs, src/i18n.rs, src/main.rs, src/missing_housenumbers.rs, src/missing_housenumbers/tests.rs, src/parse_access_log.rs, src/parse_access_log/tests.rs, src/ranges.rs, src/ranges/tests.rs, src/stats.rs, src/stats/tests.rs, src/sync_ref.rs, src/util.rs, src/util/tests.rs, src/validator.rs, src/webframe.rs, src/webframe/tests.rs, src/wsgi.rs, src/wsgi/tests.rs, src/wsgi_additional.rs, src/wsgi_json/tests.rs
More readable, similar to C++'s "foo " << bar << " baz".
Change-Id: I7d8ad6a21ec8462e4c1336859ec1779b1bfe0f32
=> Use variables directly in the format string

src/stats/tests.rs, tests/workdir/stats/2019-07-17.citycount, tests/workdir/stats/2020-04-10.citycount
If the city is only in new, but not in old, it should be ignored. This
was hard to test when the .citycount was not populated from code.
Also remove 2019-07-17.citycount, which was not used by any tests.
Change-Id: Ic733af047e1a8ce4972e423c1544c15b0839138a
=> stats: explicitly test what happens when old vs new citycount has growing keys

src/webframe.rs, src/wsgi/tests.rs
Now that .citycount has a header, need to ignore that till the data is
parsed with util::CsvRead.
Change-Id: Ia6ae7d2178e4305be4d5ceed7590ffe7a5d639b4
=> webframe: fix /housenumber-stats/hungary/cityprogress

src/webframe.rs, src/wsgi/tests.rs
Now that .zipcount has a header, need to ignore that till the data is
parsed with util::CsvRead.
Change-Id: I8b2d4b2cc989b573c39417ef8c31c8d35125617d
=> webframe: fix /housenumber-stats/hungary/zipprogress

src/cron.rs, src/util.rs
I.e. the one that is country-level, not relation-level.
Change-Id: I6df3e75d8ac233096fa1f68a10ccdba6f71ae734
=> cron: switch to typed CSV parsing for stats-level OSM housenumbers

src/stats.rs
Rust port of commit c7b98dd39848f7f6db30d2ff1e5c58e95c6256a4 (stats.py:
error handling: log missing file names, 2023-03-02).
Change-Id: I4d4b5ad6f2c0f75342acd553219004ce5ef5fd9e
=> stats.rs: error handling: log missing file names

guide/src/news.md, src/main.rs
127.0.0.1 is a fine default when HTTPS is provided by a reverse proxy on
the same host, but if running inside a container, this won't be
reachable from the outside. E.g. 0.0.0.0 is a better choice in that
case.
Change-Id: I835e8382292e5d459e7a65978c07530dc0d19523
=> rouille: add new --host parameter

tools/container/Containerfile, tools/container/build.sh, tools/container/init.sh, tools/container/run.sh
Docs still needs writing, but in short:
- build.sh can build a container if you want to run osm-gimmisn on some
hosting platform that only allows containers, not VMs
- Containerfile is used by build.sh
- run.sh can run the container, in a rootless mode
- the container will invoke init.sh as its first / only process
Change-Id: Ic0b467b88d950cc2dd4c9e1116349d6aebd1fff3
=> tools, container: import initial support

src/util.rs, src/webframe.rs, src/wsgi/tests.rs
We already wrote a different header, adjust the reading side, so
/housenumber-stats/hungary/zipprogress doesn't fail.
Change-Id: I0baee22df4f720a9e384242eb71475ea3c78fe29
=> stats: zipprogress: separate header for city and zip count

src/context.rs, src/context/tests.rs, src/cron/tests.rs, src/overpass_query/tests.rs, src/sync_ref/tests.rs, src/util/tests.rs, src/wsgi/tests.rs, src/wsgi_json/tests.rs
Avoids a clone() and we don't need the network after setting it on the
caller side.
Change-Id: Id8f44b83b89285c7df2cb7afe1e7a2a31df0d9bd
=> context: take network by value in set_network()

src/util.rs
And remove a comment that is a leftover from Python porting.
Change-Id: Ic5e63293b4f924274e3cda58fa87f171c0080c71
=> util: avoid some unwrap()

src/sync_ref.rs
- no comment at all: comes from the main housenumbers ref source
- " " comment: comes from ext, but no comment
Change-Id: Iab24a1b9f551f5b6b98a812638fe32ed56807f4c
=> sync-ref: differentiate between "ext with no comment" vs "not ext"

src/context.rs, src/context/system.rs, src/context/tests.rs, src/sync_ref.rs
This way the test db is kept in-memory, and no tests/workdir/state.db is
created.
Change-Id: I67eb3ebd37232080dfacc153b4a4d286934a0e00
=> context: introduce a Database interface

src/context.rs
'z' seems to be down for now.
Change-Id: I50e30df417c06a01def5b38abe05ce4842d6494c
=> context: change overpass URI back to the primary one

src/areas.rs, src/context.rs, src/util.rs, src/util/tests.rs
So that indexed sql can be used in the future instead of the home-grown
json cache.
Change-Id: I76a6f5bdc39b592ba713d4a5b70884d5003395e9
=> Import street reference into sql

src/areas/tests.rs, src/cache/tests.rs, src/cache_yamls/tests.rs, src/context.rs, src/context/tests.rs, src/cron/tests.rs, src/parse_access_log/tests.rs, src/stats/tests.rs, src/sync_ref/tests.rs, src/webframe/tests.rs, src/wsgi/tests.rs, src/wsgi_additional/tests.rs, src/wsgi_json/tests.rs
A simple Rc is enough, since all code runs on a single thread. This was
a leftover from Python porting.
Change-Id: I9a227fc9aaec4ce021e78afd52fb4971d2f5c4c3
=> No need to hold FileSystem by Arc

Cargo.lock, Cargo.toml, src/areas.rs, src/context.rs, src/sync_ref.rs, src/util/tests.rs
Right now all 3 places create their own sql connections, which is not a
big problem, but in case more sql usage is introduced in the future,
then this connect / disconnect all the time is a waste.
Also, the tests use a :memory: connection, so in case you create a table
in one function and you try to select form it in an other function, it
won't work in the :memory: case to reconnect between the two functions.
Solving this is a bit tricky, since we pass around an immutable Context
and we want to lazy-create this (so the test Context can inject its
memory database), which means inferior mutability, twice.
Solve the lazy part by using OnceCell, we already indirectly depend on
the once_cell crate anyway. The remaining problem is how to have a
mutable connection (for transactions) inside an …
=> context: lazy-create a shared database connection

src/context.rs, src/context/tests.rs, src/stats/tests.rs
Similar to 83d640b94701eb55bf21f361470fc14db6c4e9de (No need to hold
FileSystem by Arc, 2023-04-15).
Change-Id: I2dd282fa89da5c92fd60353ad21e32ebac92a9f6
=> No need to hold Time by Arc

src/area_files.rs, src/areas.rs, src/areas/tests.rs, src/context.rs, src/context/tests.rs, src/cron.rs, src/cron/tests.rs, src/parse_access_log.rs, src/parse_access_log/tests.rs, src/wsgi.rs, src/wsgi/tests.rs
Change-Id: Idc9ec08eaf8e7db51548064b2c0dd16baf3f5c1e
=> areas: track osm housenumber coverages in sql instead of separate files

src/areas.rs, src/cache.rs, src/context.rs, src/context/tests.rs, src/wsgi.rs, src/wsgi_additional.rs, src/wsgi_additional/tests.rs
Gets rid of that DB hack at the end of make_test_context().
Change-Id: I7183e44edfc1c698cc4d479cabc0dd0a6fc028a5
=> areas: avoid clone() in Relation::new()

src/area_files.rs, src/areas.rs, src/areas/tests.rs, src/context.rs, src/cron.rs, src/cron/tests.rs, src/wsgi.rs, src/wsgi/tests.rs
Change-Id: I3f5ec263f5e7a85654b14e4b57922921f68da5fa
=> areas: track osm street coverages in sql instead of separate files

src/fixtures/network/sync-ref.html, src/sync_ref.rs
We assumed that the filename always have a date, but this may not be
true. Just ignore those files.
Change-Id: I96ae446e913e3e0665eaaf39fa78628c02d49395
=> sync-ref: ignore files without dates

src/webframe.rs
The object ID is a link, the type is not, it's how additional streets
has it.
Change-Id: Id98f7c5f5eeae7152e0693fa7ac3c02fb4e562f5
=> stats, invalid-addr-cities: make this more consistent with additional streets

Makefile, src/context.rs, src/lib.rs, src/sql.rs
Mostly because soon we'll need some DB schema migration and context is
not meant to contain much logic, apart from abstracting away
time/network/sql/etc.
Change-Id: I455087f0a153c2247b57c79e2e66241e1583d4e7
=> Extract the sql module from context

src/sync_ref.rs
ref-housenumbers were already invalidated in sql, do the same for
streets.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3028>.
Change-Id: I3259fbe32a539ebf9bcddd12be8490102a12d49f
=> sync-ref: fix missing invalidation of ref-streets cache

Cargo.lock, Cargo.toml, package.json, src/sync_ref.rs, src/sync_ref/tests.rs
There is some incompatile change in the html_parser crate, the input
can't be parsed as-is. If the header is replaced with the standard html5
header, then no need to skip a first-line comment before the real root.
Change-Id: Ief20bba0e8daf9e3f5469d0c29c4c962cbc1bcdd
=> Update dependencies (2023-06)

src/sql.rs
After commit 09b011097f34f8e89b04a9aedfcd75ab64e95959 (data:
street-housenumbers-hungary.overpassql: add timestamp, fixme,
2023-06-01), to be written in stats::update_invalid_addr_cities(), to be
read in webframe::handle_invalid_addr_cities().
Change-Id: I8a480b2e8c00124aac15ec65c7f004136f1ed324
=> sql: add timestamp and fixme cols for the stats_invalid_addr_cities table

src/stats.rs
So that later the web interface can show this.
Change-Id: I35947eeb8f9851fbe4e3a956eacbb845d07028bb
=> stats, update_invalid_addr_cities: track timestamp/fixme cols from overpass

tools/container/Containerfile
The container file is meant to show how to run this on latest Fedora.
Change-Id: Ib768d1d5e4b62fee98c24fd717ef961f7877aaa1
=> tools, container: update to Fedora 38

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/webframe.rs
This was already in the DB, just let the web interface show them.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/2985>.
Change-Id: I94ebaf767f6ac8bce2a8ba583bf64eee9ee4a9a0
=> stats, invalid-addr-cities: show timestamp & fixme columns

tools/container/run.sh
guide/src/installation.md explains how to run sync-ref instead.
Change-Id: I355fd85a3497edce0b1c4d2fc7216a7cb188601b
=> tools, container: drop not needed REF_URL

src/browser/stats.ts
This was like this before the chartjs3 migration, then it was lost, it
seems.
Change-Id: Ide8c1107e9daec43f6b40105fa93bb33bd7e1135
=> browser, stats: don't begin the y axis in the usertotal chart

src/browser/stats.ts
Tree shaking dropped the filler code, so it was not enough to set 'fill:
true'.  Also one more place missed the beginAtZero option.
With this, the look of the charts appear very similar to the old chart2
rendering.
Change-Id: Ide30332d0e6313095bf2cfe9968b4da081bf644f
=> browser, stats: restore data set fill for two charts

src/stats.rs
So that 'cargo run -- cron --mode stats --no-overpass' runs again more
than once a day without errors.
Change-Id: I782a2b4c7da0efc0b69a005cfeddf9c86aee795c
=> stats: replace 'insert' with 'insert or update' for the stats_invalid_addr_cities_counts table

src/stats.rs, src/stats/tests.rs
Which means once enough data is collected, all that remains is the web
part to chart this.
Change-Id: I03a3ae14ce57b2febe761d688512d62156339f14
=> stats: add a new invalidAddrCities key to the stats json

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/browser/stats.ts, src/webframe.rs, src/wsgi/tests.rs
This was already in stats.json, just the web / JS part was missing.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/2986>.
Change-Id: I8b8c626f0aece5c7e484ff20f7f6ede65604ecfe
=> stats: add an invalid-addr-cities chart

src/cron.rs, src/cron/tests.rs, src/sql.rs
It's much easier to query the date when it's in sql. Start tracking
this, so the query can switch to working from sql in 2 weeks.
Change-Id: I173836816258b1643a95f7272689ee341dbfa754
=> cron, stats: start tracking workdir/stats/<date>.count files in sql as well

src/cron.rs, src/cron/tests.rs, src/stats.rs, src/stats/tests.rs
This is less code and we never look at the whole-country CSV from the
past, only for today.
The original idea was to have some idea about new rows in that CSV, but
these days we have a @timestamp column for that.
Change-Id: I802f2370c8b98c6f213fa13881f3fc3eb1ebe5f6
=> cron, stats: switch from <date>.csv to whole-country.csv

guide/src/news.md, po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/webframe.rs, src/webframe/tests.rs, src/wsgi.rs, src/wsgi/tests.rs
The stats page continues to serve charts. The lints page provides
verification tools.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/2987>.
Change-Id: I592adde28d83ce1c6d797d47aed387c70fc39cb0
=> stats: extract 2 lints from the stats page to an own lints page

src/cron.rs, src/cron/tests.rs, src/sql.rs
Similar to commit 40a8ac313a161a747467a0558eff137caa839ab0 (cron, stats:
start tracking workdir/stats/<date>.count files in sql as well,
2023-06-26).
Change-Id: I81caf3059872bfdd8ac5bb587bfedbe37f8b7775
=> cron, stats: start tracking workdir/stats/<date>.usercount files in sql as well

.github/workflows/tests.yml, Cargo.lock, Cargo.toml, guide/src/news.md, package.json
We now have an std::cell::OnceCell, but don't use it, because
get_or_try_init() is still behind the unstable library feature
'once_cell_try'.
Change-Id: I19c94128d37b8b7f4ceaaa0f6fc64ca38ab7d377
=> Update dependencies (2023-07)

src/cron.rs
This can be removed in the future.
Change-Id: I3470b50fe63de518ab215993aa57184c1d8c9446
=> cron: mark garbage collector of csv files as old-style

Cargo.lock, Cargo.toml
Not that interesting and this fixes
<https://github.com/advisories/GHSA-g98v-hv3f-hcfr>.
Change-Id: Ib53307956436330314edec92bc47eb3889d398cb
=> clap: disable color support

package.json, src/cron.rs, src/cron/tests.rs
There is only workdir/stats/whole-country.csv by now, but that's updated
daily, so it won't be ever removed.
Change-Id: I1a721da289385ac15e18037441e89c984d15f1a0
=> cron: no need to clean up old CSV files

guide/src/news.md, src/areas.rs, src/areas/tests.rs, src/cron.rs
The idea is that in case /lints/whole-country/invalid-relations points
out a problem, then check for a fix for that problem daily, so the fixed
relation disappears on the next day (even for inactive relations), not
only at the start of the next month.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/2988>.
Change-Id: I3095b5a9e0dc9033ab04efc66018ba1fd8774ea0
=> cron: enable inactive relations which are invalid

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/fixtures/network/overpass-additional-streets.json, src/fixtures/network/overpass-additional-streets.overpassql, src/wsgi.rs, src/wsgi/tests.rs, src/wsgi_additional.rs, src/wsgi_additional/tests.rs
The core of this is the new additional_streets_view_gpx() function:
- run the query we originally just produced and the user had to
copy&paste into overpass-turbo
- for each street:
- look up the way in the overpass result
- look up the first node in that way
This allows generating some simple GPX result ourself, without reaching
out to the external overpass-turbo.
This is meant to be much more easier on mobile than the old way.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3018>.
Change-Id: I4e861216e35dfbb5f255d9d007fe2a4f302b6a56
=> additional streets: add gpx output

src/areas.rs, src/validator.rs, src/validator/tests.rs
serde_yaml doesn't catch this, but serde_json will complain about this
later, so just reject this.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3174>.
Change-Id: I9ede5f8c7279d69d5da5b3591e986fbcd055ff15
=> validator: catch useless filter key with null value

src/areas.rs, src/areas/tests.rs, src/missing_housenumbers/tests.rs, src/util.rs, src/util/tests.rs
This can happen two ways:
- trying to filter out from reference: but it's no longer in the ref
- trying to silence some missing OSM object: but the OSM object is there
This is just the lint collection, still need to record the result
somewhere and present it on the web UI.
Change-Id: Ifacf03ff6569be8262a41dcd6060ef3bf683f8e3
=> areas: find unused 'invalid' list items

src/areas.rs, src/areas/tests.rs, src/cache.rs, src/sql.rs
Do this when the missing-housenumbers cache is not hit, so a cached case
won't empty previously found lints.
The web interface still has to show this somewhere.
Change-Id: I334fac79827f929a84214fedb90a6f633c5645ec
=> areas: write lint results to sql

src/areas.rs, src/areas/tests.rs
At the moment just serializes to string, but perhaps converion from
string will be also added later.
Change-Id: Ica609b1b9e15b56af6f5d9bf4662398d3e9a7349
=> Add stronger type to RelationLint::source

data/relation-budapest_01.yaml
Based on </missing-housenumbers/budapest_01/view-result> output, none of
this is needed is practice.
Change-Id: I3a58a1edac5dff6d9cbdd4d52c4f2a0da733ad2a
=> data: budapest_01: clean up filters

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/areas.rs, src/areas/tests.rs, src/wsgi.rs
Decouple the machine-readable name (stored in sql) from the
human-readable name, presented (and localized) on the web UI.
Change-Id: I10e3142559cf2a9b42e3956cbd134e525b60e0b1
=> relation lints: implement l10n for source

data/relation-budapest_11.yaml
=> data: budapest 11: clean up filters, part 2

src/areas.rs, src/areas/tests.rs, src/util.rs, src/util/tests.rs, src/wsgi.rs, src/wsgi/tests.rs
Similar to flagging osm housenumbers which are in the invalid list.
Change-Id: I80c8b7701badc9bcb140c6be97cf3cbe14cfdd0c
=> relation lints: also flag osm housenumbers outside the declared ranges

src/areas.rs, src/areas/tests.rs
It's enough to show one occurrence, which is consistent with the
additional streets output.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/3073>.
Change-Id: I670bcbe99f5b15dbf84fb8ca590afec7cd12e92b
=> relation lints: deduplicate findings

src/wsgi_additional.rs
Still fails with:
/osm/additional-streets/balatonfuzfo/view-result.gpx
but gives the problematic object id.
Change-Id: I317d915b6042e139323b9a087f683b98a8712c9a
=> Better error message for gpx when a 'street' is a node

src/wsgi.rs
Before:
Internal error when serving /osm/additional-streets/balatonfuzfo/view-result.gpx
our_application() failed
Caused by:
street 6697355203 has no nodes
After:
Internal error when serving /osm/additional-streets/balatonfuzfo/view-result.gpx
our_application() failed
Caused by:
0: our_application_gpx() failed
1: additional_streets_view_gpx() failed
2: street 6697355203 has no nodes
Change-Id: Ib3bcb393fa62f3be25705e4811af70d3ad5d8b93
=> wsgi: improve error handling while serving .gpx

src/wsgi_additional.rs, src/wsgi_additional/tests.rs
If we have a relation, then use the coordinate of its first member.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/3288>.
Change-Id: Ia927e930decd82ec61b94a45b282ac6fa24f81f2
=> additional streets gpx: handle relations

data/relation-balatonalmadi.yaml, data/relation-hodmezovasarhely.yaml
- balatonalmadi: the two values were the same, remove one.
- hodmezovasarhely: the first key was invalid (a 1:1 mapping is
required, the first value was used elsewhere already), remove it.
Change-Id: Ia220290831c4c7ddad5e88a59a929a09f01a7616
=> data: fix duplicated keys

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/wsgi.rs
Unused filter means either the 'invalid' item is outside the declared
ranges or the item is deleted from the reference.
Change-Id: I013163fd577d1685d96a3f4d6062a6cd114f62d9
=> relation lint, web ui: deleted from reference -> unused filter

src/areas.rs, src/util.rs
Note that here we don't fall back to 0 / "" for the osm id / type: if we
have no OSM info, that's an error, normalize() should get the row of the
OSM object.
With this, /missing-housenumbers/.../view-lints has rows like:
<street name>, invalid housenumbers, <housenumber>, created in OSM, <osm id as link>, <osm type>
While the osm id and type used to be just empty.
Change-Id: I8a75b30763d282a5e8d3b4dcabf97debd9c628bb
=> relation lint: track osm type/id for the create-in-osm + invalid case

src/areas.rs, src/areas/tests.rs, tests/workdir/street-housenumbers-reference-gh964.lst, tests/workdir/streets-gh964.csv
There were two problems here:
1) OSM data is in 42/A format already, so 42a for an invalid item won't
work for contains().
2) The check_housenumber_letters case in normalize() didn't annote the
result with osm type/ID, so we couldn't link the object, while that
should be always possible in the created-in-osm case.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3073#issuecomment-1756816929>.
Change-Id: I0a4e2b7665d768ef4ca5834b3823de35cb57de7f
=> relation lint: add missing normalize for the housenumber-letter case for invalids

src/cron.rs, src/sql.rs
See
<https://stackoverflow.com/questions/66904339/sqlite-on-conflict-two-or-more-columns>
wrt "insert or update" when the unique constraint is on multiple
columns.
Change-Id: If56938b75b311350437092caca6c0cc3fe3445e3
=> cron: start tracking .citycount in SQL as well

src/cron.rs, src/sql.rs
We never diff this data, so this is easier than .citycount which is
diffed between now and a month ago.
Change-Id: I7f99fff96163ac54225aa2447f28736ee89ca141
=> cron: start tracking .topusers in SQL as well

src/sql.rs
Old version was 8, incrementing to 9 is enough.
Change-Id: I81cac70b353635e85559b6ce54fbf2af86ef8769
=> sql: fix typo

src/cron.rs, src/sql.rs
Which was the last metric stored in workdir/stats/<date>.something files
and not in SQL.
Change-Id: Id39113955952630bd6288050f979fe82856d0e32
=> cron: start tracking .zipcount in SQL as well

src/cron.rs, src/cron/tests.rs, src/stats.rs
Nobody consumes them anymore.
And also do the sorting at sqlite level on stats.rs, that's faster than
a manual sort on the Rust level.
Change-Id: Ie0e9fe196822f7773f46071e3cc64582a262ff77
=> cron: stop writing .topusers files

src/areas.rs, src/areas/tests.rs
Because that gives us info like timestamp_osm_base and
timestamp_areas_base.
This just builds the query, it's not yet sent.
Change-Id: I03bf05929cd1a369bf83128fa1c66e75d992b509
=> areas: produce query for a relation's streets, in json format

src/area_files.rs, src/cron.rs, src/cron/tests.rs, src/fixtures/network/overpass-streets-gazdagret.json, src/wsgi.rs, src/wsgi/tests.rs, src/wsgi_json.rs, src/wsgi_json/tests.rs
Do this for all the 3 "UI": html, json and cron.
No reading of the osm/areas timestamps yet.
Change-Id: Id5c0d61cc83003bf45b771ee939f565f84d5d1df
=> wsgi, html: also store osm streets in sql

src/sql.rs
Similar to per-relation CSV files kind of provided a fast access to the
streets of a given relation.
Change-Id: I8b007510c47c7d4675bf5534d2921df17962fe9e
=> sql: fix missing index on osm_streets

Cargo.lock, Cargo.toml, src/area_files.rs
These two timestamps show the osm db date, not just the query date,
which is much more useful. This was not previously visible with CSV
query, but the newer JSON query contains the info.
Change-Id: I1ac0c456c6dc468f83e6d98e1bbc562a799965a5
=> osm streets: store timestamps in sql

src/area_files.rs, src/stats.rs
This is the timestamp of the overpass query, to know when to invalidate
the cache.
Change-Id: Ic12103e1c62bfc1a16789acacd7d2ebb828ab531
=> osm streets, sql: store mtime

src/area_files.rs, src/area_files/tests.rs, src/cron.rs, src/fixtures/network/overpass-streets-duplicate.json
Failed like this:
2023-12-01 00:11:57 [INFO] update_osm_streets, json: start: budapest_10
2023-12-01 00:11:58 [ERROR] main: unhandled error: our_main_inner failed
Caused by:
0: UNIQUE constraint failed: osm_streets.relation, osm_streets.osm_id
1: Error code 2067: A UNIQUE constraint failed
=> cron: ignore duplicated streets in relations from overpass

src/area_files.rs, src/areas.rs, src/areas/tests.rs, src/cron.rs, src/cron/tests.rs, src/missing_housenumbers/tests.rs, src/wsgi.rs, src/wsgi/tests.rs, src/wsgi_json/tests.rs
Also adjust the /streets/.../view-result page to take data from sql.
Remove test_relation_get_osm_streets_bad_overpass which is no longer
relevant, data from sql is always well-formed.
Same for test_relation_get_osm_streets_csv_error.
Same for test_relation_get_osm_streets_error.
Same for test_update_ref_housenumbers_xml_as_csv.
Note that get_osm_streets() now reads from SQL, but there are still uses
of the CSV file, so not yet removing them.
Change-Id: I51a50235c38f1a142fedcc2ba86802efeca15862
=> relation files: get osm streets from sql

src/stats.rs, src/wsgi.rs, src/wsgi/tests.rs
This now passes when tests/workdir/streets-budafok.csv is removed.
Change-Id: I3879650f5f338ce5db478e299a9cf75ce2a4dcaf
=> wsgi, missing_housenumbers_view_txt: take osm streets mtime from sql

src/wsgi.rs, src/wsgi/tests.rs
This now passes when tests/workdir/streets-budafok.csv is removed.
Change-Id: I6efeaa6330b37522e0804ab34fa34cffd6905ff1
=> wsgi, missing housenumbers, chkl: take osm streets mtime from sql

src/areas/tests.rs
This way it passes even if tests/workdir/streets-gazdagret.csv is
missing.
Change-Id: If84cf7c8cc72c75535b7456a09064206ad6e2ae7
=> areas, test_relation_files_write_osm_streets: port to sql

src/cron/tests.rs
Still 14 tests fail when tests/workdir/streets-gazdagret.csv is deleted.
Change-Id: I0bc896b0e5182ad7828dee2e7c649d447d3dbf68
=> cron: port test_update_osm_streets_http_error() to sql

src/wsgi/tests.rs, src/wsgi_additional/tests.rs
OSM streets are now in sql, so it doesn't matter is the path is hidden
or not.
Change-Id: I6ef4054875d61893ff7ed6a210c595f69f3b6d5c
=> wsgi: no need to hide these files manually anymore

src/area_files.rs, src/cron.rs, src/cron/tests.rs
The HTML UI and the JSON API still does it, though.
Change-Id: Iea95273f59a6738d5e83b206b9daef32fa1b8db0
=> cron: stop writing OSM streets as CSV

src/fixtures/network/overpass-streets-ujbuda.json, src/wsgi.rs, src/wsgi/tests.rs
The JSON API still does it, though.
Change-Id: I464d72d57ddda500a64765699186f3dffdbafa84
=> HTML UI: stop writing OSM streets as CSV

src/area_files.rs, src/areas/tests.rs, src/cron/tests.rs, src/fixtures/network/overpass-streets-gazdagret.csv, src/fixtures/network/overpass-streets-ujbuda.csv, src/wsgi/tests.rs, src/wsgi_additional/tests.rs, src/wsgi_json.rs, src/wsgi_json/tests.rs
Which allows removing the last traces of OSM streets as CSV files.
Everything is in SQL now, including the 2 (osm, areas) dates of the
streets.
Addresses the streets part of
<https://github.com/vmiklos/osm-gimmisn/issues/3105>.
Change-Id: Icb671f569c533fa6961b3167e69db3ed4bd50233
=> JSON API: stop writing OSM streets as CSV

src/webframe.rs, src/wsgi/tests.rs
Although something is odd, _Invalid for today is 212704, which is way
more than expected, need to investigate later.
Change-Id: I014e4c20ec138b57db6fc5b4cf69736c81a71e6a
=> citycounty: port webframe to sql

src/util.rs, src/util/tests.rs
This went wrong in commit eef5e67591a9453d81a1de8e4782f0c267f8f0b2
(/lints/whole-country/invalid-addr-cities: make this case-sensitive,
2023-11-19), now .citycount files again contain no _Inlilid keys (i.e.
'City' was accepted as valid, but not 'city', make sure our input is not
lowercase, either.)
Change-Id: I8cfdb37c46c568e0ec1ce2595268138556ad73fc
=> util: make get_city_key() case-sensitive as well

src/areas.rs, src/areas/tests.rs
Similar to commit 69960e4131d799ac6f99174341bfcec2c022d9a9 (areas:
produce query for a relation's streets, in json format, 2023-11-17).
Change-Id: Ia2f44997a98f0c318944879cd1bbbb5384ef3966
=> areas: produce query for a relation's housenumbers, in json format

src/area_files/tests.rs, src/fixtures/network/overpass-housenumbers-duplicate.json, src/fixtures/network/overpass-housenumbers-gazdagret.json
Similar to commit ac9e7eb136565d68c021b93c613887f3fd8fd0ab (cron: ignore
duplicated streets in relations from overpass, 2023-12-02).
Deduplicate the old test data and add an explicit duplicated test
instead.
Change-Id: I8ddf682f769774ee9f5a0b95d7b2e68cbacb2469
=> cron: ignore duplicated housenumbers in relations from overpass

src/area_files.rs, src/areas.rs, src/areas/tests.rs, src/cron/tests.rs, src/fixtures/network/overpass-additional-streets.json, src/fixtures/network/overpass-additional-streets.overpassql, src/util.rs, src/util/tests.rs, src/wsgi.rs, src/wsgi/tests.rs, src/wsgi_additional/tests.rs, src/wsgi_json/tests.rs
Similar to commit e7565760a370d522daa410584f19361f1690f037 (relation
files: get osm streets from sql, 2023-12-03).
Patterns:
- osm housenumbers, gazdagret: test_relation_get_additional_housenumbers
is an example test to seed the db
Change-Id: I6c3965a7563b832f9ec1c52d0bbc2b2daf2f12ef
=> relation files: get osm housenumbers from sql

src/wsgi.rs, src/wsgi/tests.rs
Similar to commit 285129e831afca301860722cb735b4b4a1b0a783 (wsgi,
missing_housenumbers_view_txt: take osm streets mtime from sql,
2023-12-05).
Change-Id: I9aba1b5c0160203a7ae665258a58d0536ccf10ac
=> wsgi, missing_housenumbers_view_txt: take osm housenumbers mtime from sql

src/wsgi.rs, src/wsgi/tests.rs
Similar to commit 7813b58b3d1470c3c017f44d86c1abfd1e286e1c (wsgi,
missing housenumbers, chkl: take osm streets mtime from sql,
2023-12-07).
Change-Id: Iccd29c3d816ae51478785a31abb5c122e0e60cee
=> wsgi, missing housenumbers, chkl: take osm housenumbers mtime from sql

src/wsgi.rs, src/wsgi/tests.rs
Similar to commit 8cd1bdccd7262455646fe0f4fabfdb0ca2b57de0 (wsgi,
missing housenumbers, html: take osm streets mtime from sql,
2023-12-09).
Change-Id: If8478cb487d502d2789c82885bfb412ecf6ee0ef
=> wsgi, missing housenumbers, html: take osm housenumbers mtime from sql

src/areas.rs, src/areas/tests.rs
Similar to commit 38fbcbf93f7d94dc9019d14b9707305ea55a8052 (areas: port
Relation::is_new() and is_invalid() to sql, 2023-12-11).
Change-Id: I8acdc58fca10ef311cf4bc335fca9bb55fd1d98b
=> areas: port Relation::is_new() and is_invalid() to sql wrt osm housenumbers

src/cache.rs
Similar to commit f0b24c55e97a5e44338d65a53670a6d196899510 (cache: port
osm street mtime from csv to sql, 2023-12-12).
Change-Id: Iaedd63e6e3b3e24b6981130c1879f5dba2448632
=> cache: port osm housenumber mtime from csv to sql

src/areas.rs, src/areas/tests.rs, src/cron/tests.rs, src/wsgi/tests.rs, src/wsgi_additional/tests.rs, src/wsgi_json/tests.rs, tests/workdir/street-housenumbers-budafok.csv, tests/workdir/street-housenumbers-empty.csv, tests/workdir/street-housenumbers-gh286.csv, tests/workdir/street-housenumbers-gh296.csv, tests/workdir/street-housenumbers-gh299.csv, tests/workdir/street-housenumbers-gh303.csv, tests/workdir/street-housenumbers-gh3073.csv, tests/workdir/street-housenumbers-gh385.csv, tests/workdir/street-housenumbers-gh414.csv, tests/workdir/street-housenumbers-gh611.csv, tests/workdir/street-housenumbers-gh754.csv, tests/workdir/street-housenumbers-gh830.csv, tests/workdir/street-housenumbers-gh964.csv, tests/workdir/street-housenumbers-test.csv
Allows getting rid of tests/workdir/street-housenumbers-gh964.csv.
Change-Id: I40615f4189d99a160135317fcacdbfcd40c87756
=> Relation::get_osm_streets: port osm housenumbers to sql

src/wsgi.rs, src/wsgi/tests.rs
Similar to d4f14913e429a8e0194e2e61cd1ffa522a497ff4 (HTML UI: stop
writing OSM streets as CSV, 2023-12-24).
Change-Id: I70e21c7689c60da33513b3f426fb4e25eb7c6deb
=> HTML UI: stop writing OSM housenumbers as CSV

src/stats.rs, src/stats/tests.rs
OSM names are not converted to lowercase(), the CITY column of the ref
names still do that.
Fixes the empty green part of
/housenumber-stats/whole-country/#_capital-progress.
Change-Id: I01aaec0f642f8e526a8d57029c93e2341a453a0b
=> stats: fix handle_capital_progress()

src/parse_access_log.rs, src/parse_access_log/tests.rs, src/stats.rs, src/stats/tests.rs
Which means no need to do manual error handling when a .citycount file
is missing for a given date.
Change-Id: Icfffff8b27e6a582535487fafa4b85826d584a08
=> stats, handle_topcities: work from sql

src/stats/tests.rs
git grep 'conn.execute(' src/*/tests.rs
shows 480 other places where this could be done, do it only at a single
place as a start, because it's a more compact way of seeding the DB.
Change-Id: I00de45b5318c404c328b67cfa3bb8bb40ddffb73
=> stats: use execute_batch() in test_handle_topcities()

src/cron.rs, src/cron/tests.rs, src/util.rs
Nobody reads them, SQL is used instead.
Change-Id: I318c7e2307cb43633679dbfc2353dae30949dbef
=> cron: stop writing .citycount files

src/areas.rs, src/areas/tests.rs
The osm housenumber string was split by ';' already, no reason to not do
the same for ',' as well.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3558>.
Change-Id: Ic9766a3540f058b4bb373a9cf7a65bdf66baf909
=> areas, osm housenumber split: handle ','

src/areas.rs, src/sql.rs, src/stats.rs
This deprecates workdir/<relation>-additional-streets.count files.
Change-Id: If780b19ed3619efe808f5a0d221b35fc9ee6d8db
=> additional street counts: start tracking these in sql as well

src/area_files.rs, src/areas.rs, src/cron/tests.rs, src/stats.rs, src/wsgi.rs, src/wsgi/tests.rs, src/wsgi_additional/tests.rs
Can now remove workdir/<relation>-additional-streets.count files.
Change-Id: I28b42ea655323ecaac4f88c993163b1fc8f5ecbf
=> additional street counts: port the web UI to SQL

src/areas.rs, src/sql.rs, src/stats.rs
This deprecates workdir/<relation>-additional-housenumbers.count files.
Change-Id: I13800e2688600215128374528ba0794414f9520e
=> additional housenumber counts: start tracking these in sql as well

guide/src/hacking.md, src/areas.rs, src/areas/tests.rs, src/cron.rs, src/cron/tests.rs, src/webframe.rs, src/wsgi.rs, src/wsgi/tests.rs, src/wsgi_additional.rs, src/wsgi_additional/tests.rs
This deprecates workdir/streets-reference-<relation>.lst files. We still
write them, but they are no longer read.
23 tests failed:
- areas::tests::test_relation_get_additional_streets: missing refcounty
/ refsettlement in test data
- test_relation_get_missing_streets: same
- test_relation_get_ref_streets: same
- areas::tests::test_relations_is_inactive: same
- areas::tests::test_relations_is_inactive_no_ref_streets: removed, ref
streets are now always available
- areas::tests::test_write_missing_streets_empty: set refcounty and
refsettlement to something non-existing
- wsgi_additional::tests::test_streets_street_from_housenr_well_formed:
same
- cron::tests::test_our_main: update_ref_streets() is removed.
- wsgi::tests::test_handle_invalid_refstreets: missing refcounty /
refsettlement in …
=> areas: take ref streets directly from sql

src/areas/tests.rs
Change-Id: I223c7c92425d2c23bf0563f5d9224ad40db951b1
=> areas tests: use more execute_batch()

po/hu/osm-gimmisn.po, po/osm-gimmisn.pot, src/cron.rs, src/webframe.rs, src/webframe/tests.rs
So one doesn't have to wait till the next cronjob to see a newer
/lints/whole-country/invalid-addr-cities output.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3768>.
Change-Id: Idf621e4b30b6c2509646308618f0a66249bb980d
=> New /lints/whole-country/invalid-addr-cities/update-result endpoint

src/util.rs, src/util/tests.rs
This was a leftover from times where gen_link() also did an automatic
redirect so the "..." signalled the reload is in progress. We don't load
anything automatically: if JS is enabled, then gen_link() is typically
not visible as we do a json request instead from JS.
Change-Id: I6dd267e554c3adef606e6d8d1bbaa7dc61a54318
=> util: avoid ... in gen_link()

.github/workflows/tests.yml
E.g. <https://github.com/vmiklos/osm-gimmisn/actions/runs/8208591684>
shows 6 warnings, this is meant to fix those.
Change-Id: I249a3f0c4e12a75d4ed1cc4ce115cb02e37facf3
=> CI: update deprecated actions

src/sync_ref.rs
This would be the date of the analysis itself, not the date of the
source OSM data.
Change-Id: I127a80c29037790be2e66a9e0d9b03b411a4397b
=> GC unused stats/invalid-addr-cities

src/cron.rs, src/cron/tests.rs
SQL is simpler, at least an empty table is always available.
Change-Id: Ie736a9c0e34e590912548acc9d51b828edf55f11
=> cron: port update_stats_count() to sql

src/cron/tests.rs
It can't happen that we can garbage, while it could happen in the past
that we asked for CSV and we got XML.
Change-Id: Iecfffff1674304f16350e0fd6a55a26e3b8945a6
=> cron tests: we always get well-formed data from sql in update_stats_count()

src/webframe/tests.rs
Fixes a failure when update_stats_overpass() only updates JSON, not CSV.
Change-Id: I8a8f26760517987e31614763bfb4c1c276b9a667
=> webframe: make test_handle_invalid_addr_cities_update_json() pass without a whole-country.csv

src/sync_ref.rs, src/sync_ref/tests.rs
This is similar to '--mode download', but doesn't download anything and
doesn't touch the config, either.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3826>.
Change-Id: I3f4d77638c665d8e3af3ee05945c85072976c1ae
=> sync-ref: add a '--mode local' switch

src/sql.rs, src/sql/tests.rs, src/stats.rs
Commit 33c5c51a87e1648094b2cb6813f610ebddbe2556 (stats: it's OK to not
overwrite previous count from the same day, 2024-03-31) went a bit too
far, it's enough to ignore just one specific error here.
Change-Id: Ic5ddc0dbfda9f2a27363c9f8f703de20e26fb54e
=> stats: only ignore SQLITE_CONSTRAINT_UNIQUE errors and still handle the rest

src/validator.rs, src/validator/tests.rs
The whole point of refstreets is to map between ref and osm, so if it's
the same, then the entry should be just removed.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3850>.
Change-Id: Ie69dbcd024bfd159a5835b3890efe4c17ecebcf0
=> validator: flag osm=ref in refstreets

src/sql.rs, src/sql/tests.rs, src/stats.rs, src/webframe.rs
Getting the
/osm/lints/whole-country/invalid-addr-cities/update-result.json worked
the first time on a day, but later updates failed.
These non-first updates mostly worked, except that the non-update of the
stats chart resulted in an error. The non-update is intentional, but the
expected behavior is to not singal an error, either.  A problem since
commit c2cd175565c61d591fd83ee0a34aaa8ff1b46637 (stats: only ignore
SQLITE_CONSTRAINT_UNIQUE errors and still handle the rest, 2024-04-06),
which started to not ignore all error, but the constraint violated here
is a primary key one, but directly a unique one.
Fix the problem by ignoring SQLITE_CONSTRAINT_PRIMARYKEY instead of
SQLITE_CONSTRAINT_UNIQUE, which means a manual update of the stats won't
affect the recorded data for charts, and this …
=> lints, invalid-addr-cities: fix ignoring unique constraint failure

src/webframe.rs, src/webframe/tests.rs
The intention was to still return a valid json in the error case, with
a non-empty "error" key. We returned
```
<!DOCTYPE html>
<pre>Internal error when serving ...
```
instead, fix this.
Change-Id: I15a17287bc1abd33380e83f691b5cfe88c76361a
=> webframe: improve error reporting in the JSON case

src/area_files.rs, src/areas/tests.rs, src/cache.rs, src/cache/tests.rs, src/cron/tests.rs, src/sql.rs, src/stats.rs, src/wsgi/tests.rs
- new missing-housenumbers-cache/<relation> key in the mtimes table
- new missing_housenumbers_cache table
Towards emptying these when the reference is updated.
Change-Id: I76b412cf9122d8430976151a8c19c3a9c7df0750
=> Store missing housenumbers json cache in sql

src/sync_ref.rs
See cache::is_missing_housenumbers_json_cached(), this cache doesn't
depend on the ref streets, so best to empty it on ref update.
Change-Id: I9ab303f5b4f6f0a9ec611f782da206d3c6e78d47
=> sync-ref: empty missing-housenumbers cache on ref update

src/context.rs, src/sql.rs, src/sql/tests.rs
Reportedly we ended up in a situation where the version was still 15,
but 16's table / index was created already.
Change-Id: I9342be8e8f04775c9c47dd6fb1900606c6f6b213
=> sql: run schema upgrades in transaction

src/areas/tests.rs, src/cron/tests.rs, src/sync_ref.rs, src/util.rs, src/util/tests.rs, src/wsgi.rs, src/wsgi/tests.rs
It's less code and does the same.
Change-Id: I7cc4328e7e4ae7c059c0790754b394729caaff69
=> util::build_street_reference_index: just take a ctx, no need to take a connection

src/areas.rs, src/util.rs, src/util/tests.rs
It's less code this way.
Change-Id: I0b9db53d09468bd0f39f2d5ae1aec69aa415d6b3
=> util::build_reference_index: simplify this, don't require an sql connection

src/areas.rs, src/areas/tests.rs, src/cron.rs, src/cron/tests.rs, src/sync_ref.rs, src/wsgi.rs, src/wsgi/tests.rs, src/wsgi_json.rs, src/wsgi_json/tests.rs
Towards migrating away from
workdir/street-housenumbers-reference-<relation>.lst files.
Change-Id: I667cbee2b22d203c42ea73ffffe6de4722be62c1
=> sync-ref: load the ref housenumbers into sql right after getting them

src/areas/tests.rs, tests/workdir/street-housenumbers-reference-gh964.lst
12 more to go.
Change-Id: I79f84e4e752a9347a6e8d9519f789c64bd74459d
=> areas, tests: move gh964 housenumbers ref to sql

src/areas/tests.rs, tests/workdir/street-housenumbers-reference-gh414.lst
12 more to go.
Change-Id: I81671ec83f76e6ba7682b5a094b5eba3de4010ed
=> areas, tests: move gh414 housenumbers ref to sql

src/areas/tests.rs, src/cache.rs, src/wsgi.rs, src/wsgi/tests.rs, tests/workdir/street-housenumbers-reference-gh3073.lst
9 more to go.
Change-Id: I3138ca63e585c9ff9136dd2b3ebbc2e4f76cb832
=> areas, tests: move gh3073 housenumbers ref to sql

src/areas/tests.rs, tests/workdir/street-housenumbers-reference-gh303.lst
8 more to go.
Change-Id: I852f334c5ff57e3e6863c09e19e1a026666ee8cf
=> areas, tests: move gh303 housenumbers ref to sql

src/areas/tests.rs, tests/workdir/street-housenumbers-reference-gh299.lst
7 more to go.
Change-Id: Ia772f83f970acd9199cdbb66794ccfc06b2b9837
=> areas, tests: move gh299 housenumbers ref to sql

src/areas/tests.rs, tests/workdir/street-housenumbers-reference-gh296.lst
6 more to go.
Change-Id: If39bcc5e53065ba01d2fce47c11cc8477e53335a
=> areas, tests: move gh296 housenumbers ref to sql

src/areas/tests.rs, tests/workdir/street-housenumbers-reference-gh286.lst
5 more to go.
Change-Id: I1d638f8f04969d79e4e5658ddb00c37fb4e52142
=> areas, tests: move gh286 housenumbers ref to sql

src/missing_housenumbers/tests.rs, tests/workdir/street-housenumbers-reference-gh195.lst
3 more to go.
Change-Id: I88432356e0caed502b6eb7a76b858431598b06cc
=> areas, tests: move gh195 housenumbers ref to sql

src/areas/tests.rs
Change-Id: Ia15487231d845e298d7a04ca8d0ccee28d43fb82
=> Fix areas::tests::test_relation_get_missing_housenumbers to work without street-housenumbers-reference-gazdagret.lst

src/areas/tests.rs
Change-Id: If8aa9e3d8f92a8cecc3a0037c96a52f4a802e3bd
=> Fix areas::tests::test_relation_write_missing_housenumbers to work without street-housenumbers-reference-gazdagret.lst

src/wsgi/tests.rs
Change-Id: I6ba2a5be6801bc04413bb90f036b98b008e0cf7e
=> Fix wsgi::tests::test_missing_housenumbers_well_formed to work without street-housenumbers-reference-gazdagret.lst

src/wsgi/tests.rs
Change-Id: I9c5b3251178c1ae169ce04f1b52e5594360e5370
=> Fix wsgi::tests::test_missing_housenumbers_view_result_chkl_even_odd to work without street-housenumbers-reference-gazdagret.lst

src/areas/tests.rs
1 more to go.
Change-Id: I57e2a3a289109002fccc944d3b8703e83a2b776d
=> areas, tests: move 'empty' housenumbers ref to sql

src/wsgi/tests.rs
Change-Id: I5b6448d5c622d70913be02e5a1f1c47659682270
=> Fix wsgi::tests::test_missing_housenumbers_compat_relation to work without tests/workdir/street-housenumbers-reference-budafok.lst

src/wsgi_json/tests.rs, tests/workdir/street-housenumbers-reference-budafok.lst
With this, no tests assert the internal details of get_ref_housenumbers().
Change-Id: Ifa5b95c34b19e2c277d82be989bc0f1dccc4e498
=> areas, tests: move budafok housenumbers ref to sql

src/areas.rs
E.g. 17/B, 17, 17/D should show up as '17', not something random when
housenumber letters are disabled.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/4088>.
Change-Id: I3964f3afd4dd4f1c4d358029bffec63ebe50403c
=> areas: sort housenumbers in Relation::get_ref_housenumbers()

src/sync_ref.rs
Similar to how it's done for missing housenumbers.
Change-Id: I7925be182d1ccbdfb29052273128e1abee714177
=> sync-ref: empty additional-housenumbers cache on ref update

src/cache.rs, src/cache/tests.rs
And add a test that get_missing_housenumbers_json() doesn't use the
cache when data/relation-<name>.yaml is newer.
Change-Id: I014316cd8d4ae2dd62e024bb24f3833c5a9e61a4
=> cache: drop references to get_ref_housenumbers_path()

src/context/tests.rs, src/cron.rs, src/cron/tests.rs
It's not really read by anyone, sql is now used directly.
Change-Id: I0894fc20d78ec512e58725994d8673633e401b1d
=> cron: no need to update ref housenumbers

src/areas/tests.rs
Change-Id: Ibae32e4edee34ace94281011053349130d84ee48
=> areas tests: no need to mock ref housenumbers files anymore

src/cache/tests.rs
Change-Id: Ie485b789262f08f8d3e6ad85de69e786704aa20d
=> cache tests: no need to mock ref housenumbers files anymore

src/cron/tests.rs
Change-Id: Ia1c3e7d80dea50ce606a39cd02eb85a2add9e505
=> cron tests: no need to mock ref housenumbers files anymore

src/missing_housenumbers/tests.rs
Change-Id: Icf3e4343a692e11af55979248d9b231c0de1ae1d
=> missing_housenumbers tests: no need to mock ref housenumbers files anymore

src/wsgi_json/tests.rs
Which was the last trace of
workdir/street-housenumbers-reference-<relation>.lst files, obsoleted by
SQL originally in commit 455a6992c0b2a815968da537923f5806bff5258e
(sync-ref: insert housenumbers / ext housenumbers into indexed sql,
2023-04-06).
Change-Id: I98093a59f43361ebf974934f59fcba77e4ab3e7b
=> wsgi_json tests: no need to mock ref housenumbers files anymore

src/areas/tests.rs, src/wsgi/tests.rs, src/wsgi_json/tests.rs
Change-Id: I1bea42a1a30f71480e156efba15d2f953b55a79d
=> tests: remove last trace of workdir/cache... json files, replaced by sql

src/parse_access_log.rs
Found by clippy 1.80.0.
Change-Id: I2a9057ac2665e5aaa16641102edde4a322d69050
=> parse_access_log: fix missing indentation in doc list item

src/wsgi/tests.rs
This went wrong in commit 05e322ff642eb2e5871636939b9b093b41edbd4b
(Improve the wsgi test, 2019-10-26), from:
self.assertTrue(parser.toolbar_overpass_link, "/osm/street-housenumbers/gazdagret/update-result")
to
results = root.findall("body/div[@id='toolbar']/a[@href='/osm/suspicious-streets/gazdagret/view-result']")
Change-Id: Ie743a3690d7ac402de77863e2bacc621309ecf44
=> wsgi tests: fix test_housenumbers_view_result_update_result_link()

src/wsgi/tests.rs
Change-Id: I927040ada22bcfcaa80faa66399d4191e99db5be
=> wsgi: use more execute_batch() in tests

data/relation-budapest_11.yaml
Change-Id: I14707fa0a27379f7b5df36ba6292c05c0bfff8ba
=> data, `budapest_11`: extend Gulyás köz filter

src/areas.rs, src/areas/tests.rs, src/validator.rs, src/validator/tests.rs
These are not parsed, they are used as a filter as-is, apart from
dropping slashes and converting to lowercase before comparison.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3892>.
Change-Id: I6d907cbb2afabd6169c576d96ea12ab5dc7a090e
=> areas: allow hyphens in invalid items

src/areas.rs, src/areas/tests.rs
/missing-housenumbers/.../view-lints listed the new range invalids as
unused, when they were used, fixed that.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/3892>.
Change-Id: Iafa0a351145c26a1acf75c22dc4457ee385b177e
=> areas, hyphen in invalid: fix usage tracking

src/areas.rs
a-b didn't filter out a-b*, but it should.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/3892#issuecomment-2366926826>.
Change-Id: I029c17250922c3dbe190586a8d21c9c0d67dbf47
=> areas, range in invalid items: fix handling of extended housenumbers

src/areas/tests.rs
Fails with 2a5c361833364666ee252a1d5d638d232be7544f (areas, range in
invalid items: fix handling of extended housenumbers, 2024-09-25)
reverted:
thread 'areas::tests::test_relation_get_missing_housenumbers_invalid_hyphens' panicked at src/areas/tests.rs:1429:5:
assertion `left == right` failed
left: [("mystreet", ["1*", "2*", "44", "46", "48/A", "50/A"])]
right: [("mystreet", ["44", "46", "48/A", "50/A"])]
I.e. the trailing '*' was not stripped off, so 1-2 didn't filter out
anything.
Change-Id: I42776ad32a21f239768f62cd59f6529a98d56a29
=> areas: test range items in invalid lists with extended housenumbers

src/areas.rs, src/areas/tests.rs, src/wsgi.rs
Going via a String is good enough, and it's less code.
Change-Id: I83c3f57a0140892bb3bc2e9b5933629e6c77b4ad
=> areas: avoid directly depending on rusqlite in RelationLintSource

src/areas.rs, src/areas/tests.rs, src/wsgi.rs
Going via a String is good enough, and it's less code.
With this, we have a direct dependency on rusqlite only in the sql and
context modules.
Change-Id: Ief9d540801bfb9a7290c78b46f2380ccbd0e7360
=> areas: avoid directly depending on rusqlite in RelationLintReason

src/context.rs, src/context/system.rs, src/context/tests.rs, src/main.rs, src/webframe.rs, src/wsgi/tests.rs
curl -d 'payload=%7B%22ref%22%3A%22refs%2Fheads%2Fmaster%22%7D' http://127.0.0.1:8000/osm/webhooks/github
used to fail with:
curl: (52) Empty reply from server
because exit() was performed before sending the HTTP response.
Set up a channel instead to be able to request a shutdown, this gives us
a clean shutdown path.
Change-Id: Ic654bf4a65a051b4d9876eb4b4c47782f5814d1a
=> Implement graceful shutdown

Cargo.lock, Cargo.toml
Change-Id: Ibb2157cd37a0a8c13f1ea1234e70651744ae0ea3
=> Fix build on Fedora 41, which requires a newer rust_icu_sys, due to clang 19

tools/container/Containerfile
After the trouble with clang 19 was fixed.
Change-Id: I843056dced29b0c108210cc962960e507430fb32
=> tools, container: mark Fedora 41 as working now

guide/src/installation.md, tools/container/Containerfile
If the toolchain is needed only in the builder, then the final image
size is reduced from 2.91 GB to 365 MB.
Change-Id: I9326709664bcb05d62b29311084f4177aabfa6b1
=> container: split to a builder and a final one

src/cron.rs, src/sql.rs
No need to have this in a separate file. Various code still reads the
old place, so don't remove that yet.
Change-Id: Ibddae335d9445e482bb374ebbf7ab9f0ed0ef0ef
=> cron: write workdir/stats/ref.count to sql as well

src/cache_yamls.rs, src/sql.rs
No need to have this in a separate file. Various code still reads the
old place, so don't remove that yet.
Change-Id: Iec7a06f0b5d40fe70124b4e922d5ec5e43487cbf
=> cache_yamls: write workdir/stats/relations.json to sql as well

tools/container/Containerfile
365 MB -> 257 MB, 70% of original by installing less of git ('git pull'
is enough) + cleaning the dnf cache which won't be needed later.
Change-Id: I680f21e96a7eded0522eb4ee28d75e0a723967d4
=> container: further reduce the final container

Makefile, src/area_files.rs, src/lib.rs, src/serde.rs
serde::Deserialize generates a lot of code, and test coverage of that is
not interesting, so ignore it.
Change-Id: I4031eba2fdfd6196e4f69debdbba6c8717cbf9b5
=> Split out serde types into a new file

src/wsgi_json.rs, src/wsgi_json/tests.rs
This was in sql since commit 14e2f1b6d43350c787bdc78882fc2acc4e0d4328
(cache_yamls: write workdir/stats/relations.json to sql as well,
2024-11-30), add a new non-static endpoint to expose it, so the JS code
can switch to it.
Change-Id: If6d8fd5a1f020a4c6ddef293183631838a4aabec
=> wsgi_json: take relations.json from sql

src/cache_yamls.rs, src/cache_yamls/tests.rs
The only consumer takes it from sql by now.
Change-Id: I88eddf46a36cefa14714080ec9a26c845e08946f
=> cache-yaml: stop writing relations.json to the filesystem

about.toml
Accept one more version of the unicode license, the point is to avoid
copyleft.
Change-Id: I9b492ef01e7ebdd25d2af6ae52af92a13e6ad7dd
=> Fix 'make guide'

src/sql.rs
This is meant to contain not too many elements (thousands) and only read
linearly, so no index on this for now.
Change-Id: I19e9dfe2e1917d5cc7734422fafb61d4478057b3
=> housenumberless-settlements: add sql table to store type/id of settlements by name

src/areas.rs, src/webframe.rs, src/webframe/tests.rs
It's not yet linked from /housenumber-stats/whole-country/ ("stats
page") yet.
Change-Id: I310ee4602399fb30dcedeea8bdabb89b942015f5
=> housenumberless-settlements, webframe: add /housenumberless-settlements endpoint

data/relation-szekesfehervar.yaml
Alvinci köz, Aradi utca, Balatoni út, Brassói utca, Székely utca, Vörösmarty tér
=> data: szekesfehervar: add street filters

src/webframe.rs
Showing when did we do the whole-country housenumbers fetch the last
time.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/4372>.
Change-Id: Id24afd61ef1423cb970b0d4a1a1a283baa4eefd2
=> housenumberless-settlements: add date footer

src/areas.rs, src/areas/tests.rs
Otherwise the relevant invalid item may be lost in normalize_invalids():
debug, get_ref_housenumbers: before normalize_invalids(), street_invalid is ["47", "57", "61", "61-63", "63", "65-77"]
debug, get_ref_housenumbers: after normalize_invalids(), street_invalid is ["47", "57", "61", "61", "63", "65"]
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/4506>.
Change-Id: I8aba5a93500708685650d3d5711fda359b8df50b
=> areas, hyphens in invalid items: search for these before normalize

src/browser/main.ts, src/browser/stats.ts, tsconfig.json
See <https://www.typescriptlang.org/tsconfig/#strictNullChecks>,
previously the type system simply ignored any problem around null and
undefined.
In practice turn on 'strict', but the only sub-check that caused a build
error was strictNullChecks. Also means that noImplicitAny is now
redundant, so drop it.
Change-Id: I3328b5f243b5e426048d7d453e71f019cad65f82
=> tsconfig: enable strictNullChecks option

src/util.rs
rustc 1.87 started to warn about this.
Change-Id: I8dea3a3d4b175da222a81569fb2d2aa36b7257f5
=> util: fix unnecessary `let` binding

src/validator.rs, src/validator/tests.rs
Previously only 40-60 or 50a-b was accepted, but having a letter only on
the right hand side is OK, too.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/4586>.
Change-Id: I8f3ef1a5563bbb676cc12e718dff38acb19b644e
=> validator: accept 192-216d in an invalid list

src/wsgi.rs, src/wsgi/tests.rs
test_handle_streets_update_result_well_formed() has all the setup to do
an actual update, add a sane user agent there to make sure we don't
start to reject those by accident.
Change-Id: I5fd2a3c1566d3b5e5510718920fdb5d2bd2b42f9
=> wsgi: list one more bad user agent, add positive test

src/wsgi.rs
We specify almost no colors in CSS, so just allow browsers to handle
this.
Addresses <https://github.com/vmiklos/osm-gimmisn/issues/4671>.
Change-Id: Ib09f515254b531f78b23d2cda172c82605a51689
=> wsgi: allow browsers to apply dark mode

src/areas/tests.rs, src/util.rs, src/util/tests.rs
Improves #4671.
Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark
=> util: make colored house numbers lighter in dark mode

src/browser/main.ts, src/browser/stats.ts, tsconfig.json
Non-erasably syntax is typically sort of deprecated in TS and we don't
need it.
Change-Id: Ibd34351b9b3d781e77e00c56920c9822211fd741
=> browser: rework to only use erasable syntax

src/areas.rs, src/areas/tests.rs
42/a/b would be parsed as 42, which is not useful, ignore addr:unit in
this case so 42/a is kept as in the past.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/4710>.
Change-Id: I083bb3d1d1ec0698985fdfe69e8f92aced129e95
=> areas, osm housenumbers, addr:unit: ignore when housenumber contains slash

data/relation-szabadbattyan.yaml, src/areas.rs, src/areas/tests.rs
Turns out this (in general) does more harm than good, so add a flag to
turn it on per relation and disable it by default.
Enable it for the one relation that triggered the initial request.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/4710>.
Change-Id: I7ae9d2bb4e3b3c72852806c65cc6aad2a96b83bf
=> areas, osm housenumbers, addr:unit: add relation flag & disable by default

src/areas.rs, src/areas/tests.rs
1-7/A-B was parsed as 1+7/A+B, which was turned into 1+7+0, so 1-7
didn't expand into 1+3+5+7 anymore since we started to consider
addr:unit.
The original need was to parse addr:housenumber=7 and addr:unit=C into
7/C.
Fix the problem by ignoring addr:unit if it contains a hyphen.
Related to <https://github.com/vmiklos/osm-gimmisn/issues/4710>.
Change-Id: Ie2dfc59d25404a5d3ac1dee2c34db1996caa1bed
=> areas, osm housenumbers, addr:unit: ignore unit if it contains a hyphen
